// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assistant.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO assistant_messages (id, thread_id, role, content, evidence, proposal_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, thread_id, role, content, evidence, proposal_id, created_at
`

type CreateMessageParams struct {
	ID         string
	ThreadID   string
	Role       string
	Content    string
	Evidence   []byte
	ProposalID pgtype.Text
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (AssistantMessage, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ThreadID,
		arg.Role,
		arg.Content,
		arg.Evidence,
		arg.ProposalID,
	)
	var i AssistantMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Role,
		&i.Content,
		&i.Evidence,
		&i.ProposalID,
		&i.CreatedAt,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO assistant_threads (id, org_id, user_id, title, context, attached_insight)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, user_id, title, context, attached_insight, created_at
`

type CreateThreadParams struct {
	ID              string
	OrgID           string
	UserID          string
	Title           string
	Context         []byte
	AttachedInsight pgtype.Text
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (AssistantThread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Title,
		arg.Context,
		arg.AttachedInsight,
	)
	var i AssistantThread
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Title,
		&i.Context,
		&i.AttachedInsight,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadForUser = `-- name: GetThreadForUser :one
SELECT id, org_id, user_id, title, context, attached_insight, created_at FROM assistant_threads WHERE id = $1 AND user_id = $2
`

type GetThreadForUserParams struct {
	ID     string
	UserID string
}

// Ownership-fenced fetch (the viewer must own the thread).
func (q *Queries) GetThreadForUser(ctx context.Context, arg GetThreadForUserParams) (AssistantThread, error) {
	row := q.db.QueryRow(ctx, getThreadForUser, arg.ID, arg.UserID)
	var i AssistantThread
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Title,
		&i.Context,
		&i.AttachedInsight,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesForThread = `-- name: ListMessagesForThread :many
SELECT id, thread_id, role, content, evidence, proposal_id, created_at FROM assistant_messages WHERE thread_id = $1 ORDER BY created_at
`

func (q *Queries) ListMessagesForThread(ctx context.Context, threadID string) ([]AssistantMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesForThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistantMessage
	for rows.Next() {
		var i AssistantMessage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Role,
			&i.Content,
			&i.Evidence,
			&i.ProposalID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsForUserInOrg = `-- name: ListThreadsForUserInOrg :many
SELECT id, org_id, user_id, title, context, attached_insight, created_at FROM assistant_threads
WHERE user_id = $1 AND org_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListThreadsForUserInOrgParams struct {
	UserID string
	OrgID  string
	Limit  int32
}

// Threads the user owns in ONE org, newest first. The disable gate is applied
// at the org level BEFORE this runs (a disabled org's threads are hidden, not
// filtered here — they simply are not queried).
func (q *Queries) ListThreadsForUserInOrg(ctx context.Context, arg ListThreadsForUserInOrgParams) ([]AssistantThread, error) {
	rows, err := q.db.Query(ctx, listThreadsForUserInOrg, arg.UserID, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistantThread
	for rows.Next() {
		var i AssistantThread
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Title,
			&i.Context,
			&i.AttachedInsight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
