// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bindings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeBindingsToTarget = `-- name: ActiveBindingsToTarget :many
SELECT b.id, b.source_id, s.name AS source_name
FROM bindings b JOIN services s ON s.id = b.source_id
WHERE b.target_id = $1 AND b.status <> 'revoked'
`

type ActiveBindingsToTargetRow struct {
	ID         string
	SourceID   string
	SourceName string
}

// U6 dependents: services that will knowingly break if the target dies.
func (q *Queries) ActiveBindingsToTarget(ctx context.Context, targetID pgtype.Text) ([]ActiveBindingsToTargetRow, error) {
	rows, err := q.db.Query(ctx, activeBindingsToTarget, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveBindingsToTargetRow
	for rows.Next() {
		var i ActiveBindingsToTargetRow
		if err := rows.Scan(&i.ID, &i.SourceID, &i.SourceName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBinding = `-- name: GetBinding :one
SELECT id, source_id, target_type, target_id, provider, provider_config, secret_ref, intent, scope, status, rotated_at, created_at FROM bindings WHERE id = $1
`

func (q *Queries) GetBinding(ctx context.Context, id string) (Binding, error) {
	row := q.db.QueryRow(ctx, getBinding, id)
	var i Binding
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetType,
		&i.TargetID,
		&i.Provider,
		&i.ProviderConfig,
		&i.SecretRef,
		&i.Intent,
		&i.Scope,
		&i.Status,
		&i.RotatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertBinding = `-- name: InsertBinding :one

INSERT INTO bindings (id, source_id, target_type, target_id, intent, scope, secret_ref)
VALUES ($1, $2, 'service', $3, $4, $5, $6)
RETURNING id, source_id, target_type, target_id, provider, provider_config, secret_ref, intent, scope, status, rotated_at, created_at
`

type InsertBindingParams struct {
	ID        string
	SourceID  string
	TargetID  pgtype.Text
	Intent    pgtype.Text
	Scope     string
	SecretRef pgtype.Text
}

// T3.6: bindings. Credentials are in Secrets via secret_ref, never in rows.
func (q *Queries) InsertBinding(ctx context.Context, arg InsertBindingParams) (Binding, error) {
	row := q.db.QueryRow(ctx, insertBinding,
		arg.ID,
		arg.SourceID,
		arg.TargetID,
		arg.Intent,
		arg.Scope,
		arg.SecretRef,
	)
	var i Binding
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetType,
		&i.TargetID,
		&i.Provider,
		&i.ProviderConfig,
		&i.SecretRef,
		&i.Intent,
		&i.Scope,
		&i.Status,
		&i.RotatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBindingsForSource = `-- name: ListBindingsForSource :many
SELECT id, source_id, target_type, target_id, provider, provider_config, secret_ref, intent, scope, status, rotated_at, created_at FROM bindings WHERE source_id = $1 AND status <> 'revoked' ORDER BY created_at
`

func (q *Queries) ListBindingsForSource(ctx context.Context, sourceID string) ([]Binding, error) {
	rows, err := q.db.Query(ctx, listBindingsForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Binding
	for rows.Next() {
		var i Binding
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetType,
			&i.TargetID,
			&i.Provider,
			&i.ProviderConfig,
			&i.SecretRef,
			&i.Intent,
			&i.Scope,
			&i.Status,
			&i.RotatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeBinding = `-- name: RevokeBinding :one
UPDATE bindings SET status = 'revoked', rotated_at = now()
WHERE id = $1 AND status <> 'revoked'
RETURNING id, source_id, target_type, target_id, provider, provider_config, secret_ref, intent, scope, status, rotated_at, created_at
`

func (q *Queries) RevokeBinding(ctx context.Context, id string) (Binding, error) {
	row := q.db.QueryRow(ctx, revokeBinding, id)
	var i Binding
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetType,
		&i.TargetID,
		&i.Provider,
		&i.ProviderConfig,
		&i.SecretRef,
		&i.Intent,
		&i.Scope,
		&i.Status,
		&i.RotatedAt,
		&i.CreatedAt,
	)
	return i, err
}
