// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBudget = `-- name: GetBudget :one

SELECT org_id, limit_cents, alert_thresholds, updated_at FROM budgets WHERE org_id = $1
`

// T11.6: the hard spend cap (B1 budget).
func (q *Queries) GetBudget(ctx context.Context, orgID string) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudget, orgID)
	var i Budget
	err := row.Scan(
		&i.OrgID,
		&i.LimitCents,
		&i.AlertThresholds,
		&i.UpdatedAt,
	)
	return i, err
}

const sumOrgMonthlyEstimate = `-- name: SumOrgMonthlyEstimate :one
SELECT coalesce(sum(s.monthly_estimate_cents), 0)::bigint AS cents
FROM services s
JOIN environments e ON e.id = s.env_id
JOIN projects p ON p.id = e.project_id
WHERE p.org_id = $1 AND s.status <> 'deleting'
`

// The org's committed monthly run-rate: Σ active services' monthly estimates
// across all its projects/envs. The hard cap projects against this (+ plan fee)
// at the accept gate. `deleting` services are on their way out, so excluded;
// everything else is counted (conservative — the cap must never under-count).
func (q *Queries) SumOrgMonthlyEstimate(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumOrgMonthlyEstimate, orgID)
	var cents int64
	err := row.Scan(&cents)
	return cents, err
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budgets (org_id, limit_cents, alert_thresholds)
VALUES ($1, $2, $3)
ON CONFLICT (org_id) DO UPDATE
    SET limit_cents = EXCLUDED.limit_cents,
        alert_thresholds = EXCLUDED.alert_thresholds,
        updated_at = now()
RETURNING org_id, limit_cents, alert_thresholds, updated_at
`

type UpsertBudgetParams struct {
	OrgID           string
	LimitCents      pgtype.Int8
	AlertThresholds []int32
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, upsertBudget, arg.OrgID, arg.LimitCents, arg.AlertThresholds)
	var i Budget
	err := row.Scan(
		&i.OrgID,
		&i.LimitCents,
		&i.AlertThresholds,
		&i.UpdatedAt,
	)
	return i, err
}
