// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBudget = `-- name: GetBudget :one

SELECT org_id, limit_cents, alert_thresholds, updated_at FROM budgets WHERE org_id = $1
`

// T11.6: the hard spend cap (B1 budget).
func (q *Queries) GetBudget(ctx context.Context, orgID string) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudget, orgID)
	var i Budget
	err := row.Scan(
		&i.OrgID,
		&i.LimitCents,
		&i.AlertThresholds,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budgets (org_id, limit_cents, alert_thresholds)
VALUES ($1, $2, $3)
ON CONFLICT (org_id) DO UPDATE
    SET limit_cents = EXCLUDED.limit_cents,
        alert_thresholds = EXCLUDED.alert_thresholds,
        updated_at = now()
RETURNING org_id, limit_cents, alert_thresholds, updated_at
`

type UpsertBudgetParams struct {
	OrgID           string
	LimitCents      pgtype.Int8
	AlertThresholds []int32
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, upsertBudget, arg.OrgID, arg.LimitCents, arg.AlertThresholds)
	var i Budget
	err := row.Scan(
		&i.OrgID,
		&i.LimitCents,
		&i.AlertThresholds,
		&i.UpdatedAt,
	)
	return i, err
}
