// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboards.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWidget = `-- name: AddWidget :one
INSERT INTO dashboard_widgets (id, dashboard_id, source, query, viz, pos)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, dashboard_id, source, query, viz, pos, created_at
`

type AddWidgetParams struct {
	ID          string
	DashboardID string
	Source      string
	Query       string
	Viz         string
	Pos         []byte
}

func (q *Queries) AddWidget(ctx context.Context, arg AddWidgetParams) (DashboardWidget, error) {
	row := q.db.QueryRow(ctx, addWidget,
		arg.ID,
		arg.DashboardID,
		arg.Source,
		arg.Query,
		arg.Viz,
		arg.Pos,
	)
	var i DashboardWidget
	err := row.Scan(
		&i.ID,
		&i.DashboardID,
		&i.Source,
		&i.Query,
		&i.Viz,
		&i.Pos,
		&i.CreatedAt,
	)
	return i, err
}

const createDashboard = `-- name: CreateDashboard :one
INSERT INTO dashboards (id, org_id, name, scope, visibility, owner_id, layout)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, name, scope, visibility, owner_id, prebuilt, layout, created_at
`

type CreateDashboardParams struct {
	ID         string
	OrgID      string
	Name       string
	Scope      string
	Visibility string
	OwnerID    string
	Layout     []byte
}

func (q *Queries) CreateDashboard(ctx context.Context, arg CreateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, createDashboard,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Scope,
		arg.Visibility,
		arg.OwnerID,
		arg.Layout,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Scope,
		&i.Visibility,
		&i.OwnerID,
		&i.Prebuilt,
		&i.Layout,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDashboard = `-- name: DeleteDashboard :exec
DELETE FROM dashboards WHERE id = $1
`

func (q *Queries) DeleteDashboard(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDashboard, id)
	return err
}

const getDashboard = `-- name: GetDashboard :one
SELECT id, org_id, name, scope, visibility, owner_id, prebuilt, layout, created_at FROM dashboards WHERE id = $1
`

func (q *Queries) GetDashboard(ctx context.Context, id string) (Dashboard, error) {
	row := q.db.QueryRow(ctx, getDashboard, id)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Scope,
		&i.Visibility,
		&i.OwnerID,
		&i.Prebuilt,
		&i.Layout,
		&i.CreatedAt,
	)
	return i, err
}

const listDashboardsForOrg = `-- name: ListDashboardsForOrg :many
SELECT id, org_id, name, scope, visibility, owner_id, prebuilt, layout, created_at FROM dashboards
WHERE org_id = $1 AND ($2::text = '' OR scope = $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListDashboardsForOrgParams struct {
	OrgID   string
	Column2 string
	Limit   int32
}

// Visibility is applied in the handler (owner-aware); this returns the org's
// dashboards newest-first, optionally filtered to one scope string.
func (q *Queries) ListDashboardsForOrg(ctx context.Context, arg ListDashboardsForOrgParams) ([]Dashboard, error) {
	rows, err := q.db.Query(ctx, listDashboardsForOrg, arg.OrgID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dashboard
	for rows.Next() {
		var i Dashboard
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Scope,
			&i.Visibility,
			&i.OwnerID,
			&i.Prebuilt,
			&i.Layout,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWidgetsForDashboard = `-- name: ListWidgetsForDashboard :many
SELECT id, dashboard_id, source, query, viz, pos, created_at FROM dashboard_widgets WHERE dashboard_id = $1 ORDER BY created_at
`

func (q *Queries) ListWidgetsForDashboard(ctx context.Context, dashboardID string) ([]DashboardWidget, error) {
	rows, err := q.db.Query(ctx, listWidgetsForDashboard, dashboardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardWidget
	for rows.Next() {
		var i DashboardWidget
		if err := rows.Scan(
			&i.ID,
			&i.DashboardID,
			&i.Source,
			&i.Query,
			&i.Viz,
			&i.Pos,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDashboard = `-- name: UpdateDashboard :one
UPDATE dashboards
SET name = COALESCE($2, name),
    visibility = COALESCE($3, visibility),
    layout = COALESCE($4, layout)
WHERE id = $1
RETURNING id, org_id, name, scope, visibility, owner_id, prebuilt, layout, created_at
`

type UpdateDashboardParams struct {
	ID         string
	Name       pgtype.Text
	Visibility pgtype.Text
	Layout     []byte
}

func (q *Queries) UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, updateDashboard,
		arg.ID,
		arg.Name,
		arg.Visibility,
		arg.Layout,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Scope,
		&i.Visibility,
		&i.OwnerID,
		&i.Prebuilt,
		&i.Layout,
		&i.CreatedAt,
	)
	return i, err
}
