// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeployment = `-- name: GetDeployment :one
SELECT id, number, env_id, service_id, git_sha, state, actor, canary_percent, gates, migrations, annotation, promoted_from, rollback_of, created_at FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.EnvID,
		&i.ServiceID,
		&i.GitSha,
		&i.State,
		&i.Actor,
		&i.CanaryPercent,
		&i.Gates,
		&i.Migrations,
		&i.Annotation,
		&i.PromotedFrom,
		&i.RollbackOf,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeployment = `-- name: InsertDeployment :one
INSERT INTO deployments (id, number, env_id, service_id, git_sha, actor, promoted_from, rollback_of)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, number, env_id, service_id, git_sha, state, actor, canary_percent, gates, migrations, annotation, promoted_from, rollback_of, created_at
`

type InsertDeploymentParams struct {
	ID           string
	Number       int32
	EnvID        string
	ServiceID    string
	GitSha       string
	Actor        string
	PromotedFrom pgtype.Text
	RollbackOf   pgtype.Text
}

func (q *Queries) InsertDeployment(ctx context.Context, arg InsertDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, insertDeployment,
		arg.ID,
		arg.Number,
		arg.EnvID,
		arg.ServiceID,
		arg.GitSha,
		arg.Actor,
		arg.PromotedFrom,
		arg.RollbackOf,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.EnvID,
		&i.ServiceID,
		&i.GitSha,
		&i.State,
		&i.Actor,
		&i.CanaryPercent,
		&i.Gates,
		&i.Migrations,
		&i.Annotation,
		&i.PromotedFrom,
		&i.RollbackOf,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploymentsForEnv = `-- name: ListDeploymentsForEnv :many
SELECT id, number, env_id, service_id, git_sha, state, actor, canary_percent, gates, migrations, annotation, promoted_from, rollback_of, created_at FROM deployments WHERE env_id = $1 ORDER BY number DESC
`

func (q *Queries) ListDeploymentsForEnv(ctx context.Context, envID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsForEnv, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.EnvID,
			&i.ServiceID,
			&i.GitSha,
			&i.State,
			&i.Actor,
			&i.CanaryPercent,
			&i.Gates,
			&i.Migrations,
			&i.Annotation,
			&i.PromotedFrom,
			&i.RollbackOf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDeploymentNumber = `-- name: NextDeploymentNumber :one

SELECT coalesce(max(number), 0)::int + 1 FROM deployments WHERE env_id = $1
`

// T4.3: deployments. number assignment locks the env row's history via the
// unique (env_id, number) — the insert retries on collision in code.
func (q *Queries) NextDeploymentNumber(ctx context.Context, envID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextDeploymentNumber, envID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const previousDeployment = `-- name: PreviousDeployment :one
SELECT id, number, env_id, service_id, git_sha, state, actor, canary_percent, gates, migrations, annotation, promoted_from, rollback_of, created_at FROM deployments
WHERE env_id = $1 AND service_id = $2 AND number < $3
  AND state IN ('live', 'rolled_back')
ORDER BY number DESC
LIMIT 1
`

type PreviousDeploymentParams struct {
	EnvID     string
	ServiceID string
	Number    int32
}

// The most recent EARLIER deployment of the same service that carried an
// image (reached live or was itself later rolled back — i.e. it worked).
func (q *Queries) PreviousDeployment(ctx context.Context, arg PreviousDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, previousDeployment, arg.EnvID, arg.ServiceID, arg.Number)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.EnvID,
		&i.ServiceID,
		&i.GitSha,
		&i.State,
		&i.Actor,
		&i.CanaryPercent,
		&i.Gates,
		&i.Migrations,
		&i.Annotation,
		&i.PromotedFrom,
		&i.RollbackOf,
		&i.CreatedAt,
	)
	return i, err
}

const setDeploymentState = `-- name: SetDeploymentState :one
UPDATE deployments SET state = $3 WHERE id = $1 AND state = $2 RETURNING id, number, env_id, service_id, git_sha, state, actor, canary_percent, gates, migrations, annotation, promoted_from, rollback_of, created_at
`

type SetDeploymentStateParams struct {
	ID      string
	State   string
	State_2 string
}

func (q *Queries) SetDeploymentState(ctx context.Context, arg SetDeploymentStateParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, setDeploymentState, arg.ID, arg.State, arg.State_2)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.EnvID,
		&i.ServiceID,
		&i.GitSha,
		&i.State,
		&i.Actor,
		&i.CanaryPercent,
		&i.Gates,
		&i.Migrations,
		&i.Annotation,
		&i.PromotedFrom,
		&i.RollbackOf,
		&i.CreatedAt,
	)
	return i, err
}
