// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimEmailDelivery = `-- name: ClaimEmailDelivery :one

INSERT INTO email_deliveries (id, event_id, org_id, recipient, template, template_version, provider, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'sent')
ON CONFLICT (event_id, recipient) DO NOTHING
RETURNING id
`

type ClaimEmailDeliveryParams struct {
	ID              string
	EventID         string
	OrgID           pgtype.Text
	Recipient       string
	Template        string
	TemplateVersion int32
	Provider        string
}

// T10.4: the email delivery ledger (idempotent by event_id + recipient).
// Claim the (event, recipient) pair BEFORE sending: if a row already exists
// (the event was re-processed), no id is returned and the caller skips the send
// — the claim is the idempotency gate, the UNIQUE constraint the backstop.
func (q *Queries) ClaimEmailDelivery(ctx context.Context, arg ClaimEmailDeliveryParams) (string, error) {
	row := q.db.QueryRow(ctx, claimEmailDelivery,
		arg.ID,
		arg.EventID,
		arg.OrgID,
		arg.Recipient,
		arg.Template,
		arg.TemplateVersion,
		arg.Provider,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getEmailDelivery = `-- name: GetEmailDelivery :one
SELECT id, event_id, org_id, recipient, template, template_version, status, provider, provider_id, error, created_at FROM email_deliveries WHERE event_id = $1 AND recipient = $2
`

type GetEmailDeliveryParams struct {
	EventID   string
	Recipient string
}

func (q *Queries) GetEmailDelivery(ctx context.Context, arg GetEmailDeliveryParams) (EmailDelivery, error) {
	row := q.db.QueryRow(ctx, getEmailDelivery, arg.EventID, arg.Recipient)
	var i EmailDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OrgID,
		&i.Recipient,
		&i.Template,
		&i.TemplateVersion,
		&i.Status,
		&i.Provider,
		&i.ProviderID,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingMailEvents = `-- name: ListPendingMailEvents :many
SELECT e.id, e.org_id, e.kind, e.via, e.actor, e.action, e.subject, e.at, e.detail FROM events e
LEFT JOIN email_deliveries d ON d.event_id = e.id
WHERE e.action = ANY($1::text[]) AND d.id IS NULL
ORDER BY e.at ASC
LIMIT 100
`

// The durable outbox scan: spine events whose action triggers mail but which
// have no delivery yet. The spine + delivery ledger ARE the outbox — no row is
// lost on restart, and Dispatch is idempotent, so re-scanning is safe.
func (q *Queries) ListPendingMailEvents(ctx context.Context, actions []string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listPendingMailEvents, actions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Via,
			&i.Actor,
			&i.Action,
			&i.Subject,
			&i.At,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailDeliveryFailed = `-- name: MarkEmailDeliveryFailed :exec
UPDATE email_deliveries SET status = 'failed', error = $2 WHERE id = $1
`

type MarkEmailDeliveryFailedParams struct {
	ID    string
	Error pgtype.Text
}

func (q *Queries) MarkEmailDeliveryFailed(ctx context.Context, arg MarkEmailDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markEmailDeliveryFailed, arg.ID, arg.Error)
	return err
}

const markEmailDeliverySent = `-- name: MarkEmailDeliverySent :exec
UPDATE email_deliveries SET status = 'sent', provider_id = $2, error = NULL WHERE id = $1
`

type MarkEmailDeliverySentParams struct {
	ID         string
	ProviderID pgtype.Text
}

func (q *Queries) MarkEmailDeliverySent(ctx context.Context, arg MarkEmailDeliverySentParams) error {
	_, err := q.db.Exec(ctx, markEmailDeliverySent, arg.ID, arg.ProviderID)
	return err
}
