// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: estimates.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptEstimate = `-- name: AcceptEstimate :one
UPDATE estimates SET accepted_at = now()
WHERE id = $1 AND env_id = $2 AND accepted_at IS NULL AND expires_at > now()
RETURNING id, org_id, env_id, services, lines, total_cents, expires_at, accepted_at, created_at
`

type AcceptEstimateParams struct {
	ID    string
	EnvID pgtype.Text
}

// One-shot: only a live, unaccepted, env-matching estimate flips.
func (q *Queries) AcceptEstimate(ctx context.Context, arg AcceptEstimateParams) (Estimate, error) {
	row := q.db.QueryRow(ctx, acceptEstimate, arg.ID, arg.EnvID)
	var i Estimate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EnvID,
		&i.Services,
		&i.Lines,
		&i.TotalCents,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEstimate = `-- name: GetEstimate :one
SELECT id, org_id, env_id, services, lines, total_cents, expires_at, accepted_at, created_at FROM estimates WHERE id = $1
`

func (q *Queries) GetEstimate(ctx context.Context, id string) (Estimate, error) {
	row := q.db.QueryRow(ctx, getEstimate, id)
	var i Estimate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EnvID,
		&i.Services,
		&i.Lines,
		&i.TotalCents,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertEstimate = `-- name: InsertEstimate :one

INSERT INTO estimates (id, org_id, env_id, services, lines, total_cents, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, env_id, services, lines, total_cents, expires_at, accepted_at, created_at
`

type InsertEstimateParams struct {
	ID         string
	OrgID      pgtype.Text
	EnvID      pgtype.Text
	Services   []byte
	Lines      []byte
	TotalCents int64
	ExpiresAt  pgtype.Timestamptz
}

// T3.1: estimates. Acceptance (createService, T3.3) marks accepted_at and
// checks env match + liveness — the estimate-before-provision law.
func (q *Queries) InsertEstimate(ctx context.Context, arg InsertEstimateParams) (Estimate, error) {
	row := q.db.QueryRow(ctx, insertEstimate,
		arg.ID,
		arg.OrgID,
		arg.EnvID,
		arg.Services,
		arg.Lines,
		arg.TotalCents,
		arg.ExpiresAt,
	)
	var i Estimate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EnvID,
		&i.Services,
		&i.Lines,
		&i.TotalCents,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}
