// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :one

INSERT INTO events (id, org_id, kind, via, actor, action, subject, detail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, kind, via, actor, action, subject, at, detail
`

type AppendEventParams struct {
	ID      string
	OrgID   string
	Kind    string
	Via     string
	Actor   string
	Action  string
	Subject string
	Detail  []byte
}

// The events spine (T2.5). Keyset pagination over (at, id) — offset drifts
// under append. Every query is org-fenced; cross-org cursors yield nothing.
func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.ID,
		arg.OrgID,
		arg.Kind,
		arg.Via,
		arg.Actor,
		arg.Action,
		arg.Subject,
		arg.Detail,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Via,
		&i.Actor,
		&i.Action,
		&i.Subject,
		&i.At,
		&i.Detail,
	)
	return i, err
}

const listOrgEventsAsc = `-- name: ListOrgEventsAsc :many
SELECT id, org_id, kind, via, actor, action, subject, at, detail FROM events
WHERE org_id = $1
  AND ($3::text IS NULL OR kind = $3)
  AND ($4::timestamptz IS NULL OR (at, id) > ($4::timestamptz, $5::text))
ORDER BY at ASC, id ASC
LIMIT $2
`

type ListOrgEventsAscParams struct {
	OrgID   string
	Limit   int32
	Kind    pgtype.Text
	AfterAt pgtype.Timestamptz
	AfterID pgtype.Text
}

// SSE replay: everything strictly AFTER the cursor, oldest first.
func (q *Queries) ListOrgEventsAsc(ctx context.Context, arg ListOrgEventsAscParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listOrgEventsAsc,
		arg.OrgID,
		arg.Limit,
		arg.Kind,
		arg.AfterAt,
		arg.AfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Via,
			&i.Actor,
			&i.Action,
			&i.Subject,
			&i.At,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgEventsDesc = `-- name: ListOrgEventsDesc :many
SELECT id, org_id, kind, via, actor, action, subject, at, detail FROM events
WHERE org_id = $1
  AND ($3::text IS NULL OR kind = $3)
  AND ($4::text IS NULL OR actor = $4)
  AND ($5::text IS NULL OR action = $5)
  AND ($6::timestamptz IS NULL OR (at, id) < ($6::timestamptz, $7::text))
ORDER BY at DESC, id DESC
LIMIT $2
`

type ListOrgEventsDescParams struct {
	OrgID    string
	Limit    int32
	Kind     pgtype.Text
	Actor    pgtype.Text
	Action   pgtype.Text
	BeforeAt pgtype.Timestamptz
	BeforeID pgtype.Text
}

func (q *Queries) ListOrgEventsDesc(ctx context.Context, arg ListOrgEventsDescParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listOrgEventsDesc,
		arg.OrgID,
		arg.Limit,
		arg.Kind,
		arg.Actor,
		arg.Action,
		arg.BeforeAt,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Via,
			&i.Actor,
			&i.Action,
			&i.Subject,
			&i.At,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
