// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package store

import (
	"context"
)

const createRepoLink = `-- name: CreateRepoLink :one
INSERT INTO repo_links (id, org_id, service_id, repo, branch)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, service_id, repo, branch, created_at
`

type CreateRepoLinkParams struct {
	ID        string
	OrgID     string
	ServiceID string
	Repo      string
	Branch    string
}

func (q *Queries) CreateRepoLink(ctx context.Context, arg CreateRepoLinkParams) (RepoLink, error) {
	row := q.db.QueryRow(ctx, createRepoLink,
		arg.ID,
		arg.OrgID,
		arg.ServiceID,
		arg.Repo,
		arg.Branch,
	)
	var i RepoLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ServiceID,
		&i.Repo,
		&i.Branch,
		&i.CreatedAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :one
INSERT INTO github_deliveries (id, delivery_id, event, action, repo, payload)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (delivery_id) DO NOTHING
RETURNING id, delivery_id, event, action, repo, payload, received_at
`

type InsertDeliveryParams struct {
	ID         string
	DeliveryID string
	Event      string
	Action     string
	Repo       string
	Payload    []byte
}

// ON CONFLICT DO NOTHING makes redelivery idempotent; zero rows = duplicate.
func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (GithubDelivery, error) {
	row := q.db.QueryRow(ctx, insertDelivery,
		arg.ID,
		arg.DeliveryID,
		arg.Event,
		arg.Action,
		arg.Repo,
		arg.Payload,
	)
	var i GithubDelivery
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.Event,
		&i.Action,
		&i.Repo,
		&i.Payload,
		&i.ReceivedAt,
	)
	return i, err
}

const linksForRepo = `-- name: LinksForRepo :many
SELECT id, org_id, service_id, repo, branch, created_at FROM repo_links WHERE org_id = $1 AND repo = $2
`

type LinksForRepoParams struct {
	OrgID string
	Repo  string
}

func (q *Queries) LinksForRepo(ctx context.Context, arg LinksForRepoParams) ([]RepoLink, error) {
	rows, err := q.db.Query(ctx, linksForRepo, arg.OrgID, arg.Repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoLink
	for rows.Next() {
		var i RepoLink
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ServiceID,
			&i.Repo,
			&i.Branch,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstallationDeleted = `-- name: MarkInstallationDeleted :execrows
UPDATE github_installations SET deleted_at = now()
WHERE installation_id = $1 AND deleted_at IS NULL
`

func (q *Queries) MarkInstallationDeleted(ctx context.Context, installationID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markInstallationDeleted, installationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const orgForInstallation = `-- name: OrgForInstallation :one
SELECT org_id FROM github_installations WHERE installation_id = $1 AND deleted_at IS NULL
`

func (q *Queries) OrgForInstallation(ctx context.Context, installationID int64) (string, error) {
	row := q.db.QueryRow(ctx, orgForInstallation, installationID)
	var org_id string
	err := row.Scan(&org_id)
	return org_id, err
}

const upsertInstallation = `-- name: UpsertInstallation :one

INSERT INTO github_installations (id, org_id, installation_id, account_login)
VALUES ($1, $2, $3, $4)
ON CONFLICT (installation_id) DO UPDATE SET deleted_at = NULL, account_login = EXCLUDED.account_login
RETURNING id, org_id, installation_id, account_login, created_at, deleted_at
`

type UpsertInstallationParams struct {
	ID             string
	OrgID          string
	InstallationID int64
	AccountLogin   string
}

// T4.1: GitHub integration.
func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, upsertInstallation,
		arg.ID,
		arg.OrgID,
		arg.InstallationID,
		arg.AccountLogin,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
