// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
INSERT INTO members (id, org_id, user_id, role) VALUES ($1, $2, $3, $4) RETURNING id, org_id, user_id, role, created_at
`

type AddMemberParams struct {
	ID     string
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, addMember,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Role,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const countActiveSessionsForUser = `-- name: CountActiveSessionsForUser :one
SELECT count(*) FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) CountActiveSessionsForUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (id, name) VALUES ($1, $2) RETURNING id, name, created_at
`

type CreateOrgParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.ID, arg.Name)
	var i Org
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token_hash, device, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, device, created_at, last_seen_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	TokenHash []byte
	Device    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Device,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Device,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (id, kind, user_id, org_id, name, scope, prefix, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, kind, user_id, org_id, name, scope, prefix, token_hash, expires_at, last_used_at, created_at, revoked_at
`

type CreateTokenParams struct {
	ID        string
	Kind      string
	UserID    pgtype.Text
	OrgID     pgtype.Text
	Name      string
	Scope     string
	Prefix    string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.ID,
		arg.Kind,
		arg.UserID,
		arg.OrgID,
		arg.Name,
		arg.Scope,
		arg.Prefix,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.Scope,
		&i.Prefix,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, created_at, updated_at
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
	Name         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, user_id, token_hash, device, created_at, last_seen_at, expires_at, revoked_at FROM sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Device,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveTokenByHash = `-- name: GetActiveTokenByHash :one
SELECT id, kind, user_id, org_id, name, scope, prefix, token_hash, expires_at, last_used_at, created_at, revoked_at FROM tokens
WHERE token_hash = $1 AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetActiveTokenByHash(ctx context.Context, tokenHash []byte) (Token, error) {
	row := q.db.QueryRow(ctx, getActiveTokenByHash, tokenHash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.Scope,
		&i.Prefix,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM members WHERE org_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.OrgID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPersonalTokens = `-- name: ListPersonalTokens :many
SELECT id, kind, user_id, org_id, name, scope, prefix, token_hash, expires_at, last_used_at, created_at, revoked_at FROM tokens
WHERE kind = 'personal' AND user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPersonalTokens(ctx context.Context, userID pgtype.Text) ([]Token, error) {
	rows, err := q.db.Query(ctx, listPersonalTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.Scope,
			&i.Prefix,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesForOrg = `-- name: ListPoliciesForOrg :many
SELECT id, org_id, project_id, key, enforcement, config, created_at FROM policies WHERE org_id = $1
`

func (q *Queries) ListPoliciesForOrg(ctx context.Context, orgID string) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPoliciesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Key,
			&i.Enforcement,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePersonalToken = `-- name: RevokePersonalToken :execrows
UPDATE tokens SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND kind = 'personal' AND revoked_at IS NULL
`

type RevokePersonalTokenParams struct {
	ID     string
	UserID pgtype.Text
}

func (q *Queries) RevokePersonalToken(ctx context.Context, arg RevokePersonalTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePersonalToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const touchTokenUsed = `-- name: TouchTokenUsed :exec
UPDATE tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchTokenUsed, id)
	return err
}
