// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInvoiceForPeriod = `-- name: GetInvoiceForPeriod :one
SELECT id, org_id, period, status, total_cents, lines, tax, closed_at, created_at, updated_at FROM invoices WHERE org_id = $1 AND period = $2
`

type GetInvoiceForPeriodParams struct {
	OrgID  string
	Period string
}

func (q *Queries) GetInvoiceForPeriod(ctx context.Context, arg GetInvoiceForPeriodParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceForPeriod, arg.OrgID, arg.Period)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Period,
		&i.Status,
		&i.TotalCents,
		&i.Lines,
		&i.Tax,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, org_id, period, status, total_cents, lines, tax, closed_at, created_at, updated_at FROM invoices WHERE org_id = $1 ORDER BY period DESC
`

func (q *Queries) ListInvoices(ctx context.Context, orgID string) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Period,
			&i.Status,
			&i.TotalCents,
			&i.Lines,
			&i.Tax,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInvoiceStatus = `-- name: SetInvoiceStatus :one
UPDATE invoices SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, org_id, period, status, total_cents, lines, tax, closed_at, created_at, updated_at
`

type SetInvoiceStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, setInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Period,
		&i.Status,
		&i.TotalCents,
		&i.Lines,
		&i.Tax,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInvoiceForPeriod = `-- name: UpsertInvoiceForPeriod :one

INSERT INTO invoices (id, org_id, period, status, total_cents, lines, tax, closed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (org_id, period) DO NOTHING
RETURNING id, org_id, period, status, total_cents, lines, tax, closed_at, created_at, updated_at
`

type UpsertInvoiceForPeriodParams struct {
	ID         string
	OrgID      string
	Period     string
	Status     string
	TotalCents int64
	Lines      []byte
	Tax        []byte
	ClosedAt   pgtype.Timestamptz
}

// T11.3: invoices.
// Idempotent monthly close: one invoice per (org, period). A re-close returns
// the EXISTING row unchanged (ON CONFLICT DO NOTHING → then the caller reads it)
// — the meter is frozen once, never double-billed.
func (q *Queries) UpsertInvoiceForPeriod(ctx context.Context, arg UpsertInvoiceForPeriodParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, upsertInvoiceForPeriod,
		arg.ID,
		arg.OrgID,
		arg.Period,
		arg.Status,
		arg.TotalCents,
		arg.Lines,
		arg.Tax,
		arg.ClosedAt,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Period,
		&i.Status,
		&i.TotalCents,
		&i.Lines,
		&i.Tax,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
