// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metering.sql

package store

import (
	"context"
)

const insertUsageEvent = `-- name: InsertUsageEvent :one

INSERT INTO usage_events (id, org_id, project_id, env_id, service_id, meter, edge, product, rate_cents, quantity, detail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, project_id, env_id, service_id, meter, edge, product, rate_cents, quantity, at, detail
`

type InsertUsageEventParams struct {
	ID        string
	OrgID     string
	ProjectID string
	EnvID     string
	ServiceID string
	Meter     string
	Edge      string
	Product   string
	RateCents int64
	Quantity  int64
	Detail    []byte
}

// T3.7: raw metering (D10). Append-only; rollup is T6.3.
func (q *Queries) InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, insertUsageEvent,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvID,
		arg.ServiceID,
		arg.Meter,
		arg.Edge,
		arg.Product,
		arg.RateCents,
		arg.Quantity,
		arg.Detail,
	)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvID,
		&i.ServiceID,
		&i.Meter,
		&i.Edge,
		&i.Product,
		&i.RateCents,
		&i.Quantity,
		&i.At,
		&i.Detail,
	)
	return i, err
}

const listUsageEventsForOrg = `-- name: ListUsageEventsForOrg :many
SELECT id, org_id, project_id, env_id, service_id, meter, edge, product, rate_cents, quantity, at, detail FROM usage_events WHERE org_id = $1 ORDER BY at
`

func (q *Queries) ListUsageEventsForOrg(ctx context.Context, orgID string) ([]UsageEvent, error) {
	rows, err := q.db.Query(ctx, listUsageEventsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageEvent
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ServiceID,
			&i.Meter,
			&i.Edge,
			&i.Product,
			&i.RateCents,
			&i.Quantity,
			&i.At,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
