// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa.sql

package store

import (
	"context"
)

const confirmTotp = `-- name: ConfirmTotp :exec
UPDATE mfa_totp SET confirmed_at = now() WHERE user_id = $1
`

func (q *Queries) ConfirmTotp(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, confirmTotp, userID)
	return err
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :execrows
UPDATE recovery_codes SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type ConsumeRecoveryCodeParams struct {
	UserID   string
	CodeHash []byte
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const deleteTotp = `-- name: DeleteTotp :exec
DELETE FROM mfa_totp WHERE user_id = $1
`

func (q *Queries) DeleteTotp(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteTotp, userID)
	return err
}

const getTotp = `-- name: GetTotp :one
SELECT user_id, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, confirmed_at, created_at FROM mfa_totp WHERE user_id = $1
`

func (q *Queries) GetTotp(ctx context.Context, userID string) (MfaTotp, error) {
	row := q.db.QueryRow(ctx, getTotp, userID)
	var i MfaTotp
	err := row.Scan(
		&i.UserID,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedDek,
		&i.DekNonce,
		&i.KekID,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO recovery_codes (id, user_id, code_hash) VALUES ($1, $2, $3)
`

type InsertRecoveryCodeParams struct {
	ID       string
	UserID   string
	CodeHash []byte
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.ID, arg.UserID, arg.CodeHash)
	return err
}

const setMfaEnabled = `-- name: SetMfaEnabled :exec
UPDATE users SET mfa_enabled = $2 WHERE id = $1
`

type SetMfaEnabledParams struct {
	ID         string
	MfaEnabled bool
}

func (q *Queries) SetMfaEnabled(ctx context.Context, arg SetMfaEnabledParams) error {
	_, err := q.db.Exec(ctx, setMfaEnabled, arg.ID, arg.MfaEnabled)
	return err
}

const upsertTotpEnrollment = `-- name: UpsertTotpEnrollment :exec

INSERT INTO mfa_totp (user_id, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, confirmed_at)
VALUES ($1, $2, $3, $4, $5, $6, NULL)
ON CONFLICT (user_id) DO UPDATE SET
    ciphertext = EXCLUDED.ciphertext, nonce = EXCLUDED.nonce,
    wrapped_dek = EXCLUDED.wrapped_dek, dek_nonce = EXCLUDED.dek_nonce,
    kek_id = EXCLUDED.kek_id, confirmed_at = NULL, created_at = now()
`

type UpsertTotpEnrollmentParams struct {
	UserID     string
	Ciphertext []byte
	Nonce      []byte
	WrappedDek []byte
	DekNonce   []byte
	KekID      string
}

// T7.1: MFA.
func (q *Queries) UpsertTotpEnrollment(ctx context.Context, arg UpsertTotpEnrollmentParams) error {
	_, err := q.db.Exec(ctx, upsertTotpEnrollment,
		arg.UserID,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedDek,
		arg.DekNonce,
		arg.KekID,
	)
	return err
}
