// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Binding struct {
	ID             string
	SourceID       string
	TargetType     string
	TargetID       pgtype.Text
	Provider       pgtype.Text
	ProviderConfig []byte
	SecretRef      pgtype.Text
	Intent         pgtype.Text
	Scope          string
	Status         string
	RotatedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type Deployment struct {
	ID            string
	Number        int32
	EnvID         string
	ServiceID     string
	GitSha        string
	State         string
	Actor         string
	CanaryPercent pgtype.Int4
	Gates         []byte
	Migrations    []byte
	Annotation    pgtype.Text
	PromotedFrom  pgtype.Text
	RollbackOf    pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type Environment struct {
	ID             string
	ProjectID      string
	Name           string
	RegionOverride pgtype.Text
	Kind           string
	PolicyFlags    []byte
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type Estimate struct {
	ID         string
	OrgID      pgtype.Text
	EnvID      pgtype.Text
	Services   []byte
	Lines      []byte
	TotalCents int64
	ExpiresAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Event struct {
	ID      string
	OrgID   string
	Kind    string
	Via     string
	Actor   string
	Action  string
	Subject string
	At      pgtype.Timestamptz
	Detail  []byte
}

type Invite struct {
	ID        string
	OrgID     string
	Email     string
	Role      string
	Status    string
	InviterID string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Member struct {
	ID        string
	OrgID     string
	UserID    string
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Org struct {
	ID                  string
	Name                string
	CreatedAt           pgtype.Timestamptz
	Slug                string
	HomeRegion          string
	Plan                string
	DeletionScheduledAt pgtype.Timestamptz
}

type Policy struct {
	ID          string
	OrgID       string
	ProjectID   pgtype.Text
	Key         string
	Enforcement string
	Config      []byte
	CreatedAt   pgtype.Timestamptz
}

type Project struct {
	ID                  string
	OrgID               string
	Name                string
	CellID              string
	DeletionScheduledAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

type Secret struct {
	ID         string
	OrgID      string
	ProjectID  pgtype.Text
	EnvID      pgtype.Text
	Name       string
	Version    int32
	Ciphertext []byte
	Nonce      []byte
	WrappedDek []byte
	DekNonce   []byte
	KekID      string
	CreatedBy  string
	CreatedAt  pgtype.Timestamptz
}

type Service struct {
	ID                   string
	EnvID                string
	Name                 string
	Product              string
	Intent               pgtype.Text
	Status               string
	Shape                []byte
	Scaling              []byte
	Override             []byte
	ProvisioningSteps    []byte
	MonthlyEstimateCents int64
	EstimateID           pgtype.Text
	CellID               string
	CreatedAt            pgtype.Timestamptz
}

type Session struct {
	ID         string
	UserID     string
	TokenHash  []byte
	Device     string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Subscription struct {
	OrgID       string
	Plan        string
	AnchorDay   int32
	Status      string
	TrialEndsAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Token struct {
	ID         string
	Kind       string
	UserID     pgtype.Text
	OrgID      pgtype.Text
	Name       string
	Scope      string
	Prefix     string
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type UsageEvent struct {
	ID        string
	OrgID     string
	ProjectID string
	EnvID     string
	ServiceID string
	Meter     string
	Edge      string
	Product   string
	RateCents int64
	Quantity  int64
	At        pgtype.Timestamptz
	Detail    []byte
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
