// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notify.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWebhookDelivery = `-- name: ClaimWebhookDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event_id, id, status, attempts)
VALUES ($1, $2, $3, 'pending', 1)
ON CONFLICT (webhook_id, event_id) DO UPDATE
    SET status = 'pending', attempts = webhook_deliveries.attempts + 1, updated_at = now()
    WHERE webhook_deliveries.status NOT IN ('sent', 'skipped')
      AND webhook_deliveries.attempts < 5
RETURNING id
`

type ClaimWebhookDeliveryParams struct {
	WebhookID string
	EventID   string
	ID        string
}

// Claim the (webhook, event) as `pending` BEFORE POSTing — written first so a
// crash mid-send leaves an honest reclaimable pending, never a phantom sent.
// A `sent`/`skipped` row is terminal (no id → skip); attempts capped so a
// permanent failure dead-letters instead of hot-looping.
func (q *Queries) ClaimWebhookDelivery(ctx context.Context, arg ClaimWebhookDeliveryParams) (string, error) {
	row := q.db.QueryRow(ctx, claimWebhookDelivery, arg.WebhookID, arg.EventID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (id, org_id, url, events, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, url, events, status, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, created_at
`

type CreateWebhookParams struct {
	ID         string
	OrgID      string
	Url        string
	Events     []string
	Ciphertext []byte
	Nonce      []byte
	WrappedDek []byte
	DekNonce   []byte
	KekID      string
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.ID,
		arg.OrgID,
		arg.Url,
		arg.Events,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedDek,
		arg.DekNonce,
		arg.KekID,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Events,
		&i.Status,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedDek,
		&i.DekNonce,
		&i.KekID,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationPrefs = `-- name: GetNotificationPrefs :one
SELECT user_id, channels, quiet_hours, updated_at FROM notification_prefs WHERE user_id = $1
`

func (q *Queries) GetNotificationPrefs(ctx context.Context, userID string) (NotificationPref, error) {
	row := q.db.QueryRow(ctx, getNotificationPrefs, userID)
	var i NotificationPref
	err := row.Scan(
		&i.UserID,
		&i.Channels,
		&i.QuietHours,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, org_id, url, events, status, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, created_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id string) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Events,
		&i.Status,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedDek,
		&i.DekNonce,
		&i.KekID,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (id, user_id, event_id, kind, title, body, link)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
RETURNING id, user_id, event_id, kind, title, body, link, read, created_at
`

type InsertNotificationParams struct {
	ID      string
	UserID  string
	EventID pgtype.Text
	Kind    string
	Title   string
	Body    string
	Link    string
}

// The bell route: a per-user projection of a spine event. Idempotent per
// (user, event) so a re-routed event never double-rings the bell.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.ID,
		arg.UserID,
		arg.EventID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveWebhooksForOrg = `-- name: ListActiveWebhooksForOrg :many
SELECT id, org_id, url, events, status, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, created_at FROM webhooks
WHERE org_id = $1 AND status = 'active'
  AND (cardinality(events) = 0 OR $2::text = ANY(events))
`

type ListActiveWebhooksForOrgParams struct {
	OrgID string
	Kind  string
}

// The webhook route: active webhooks in the org whose filter matches the event
// kind (an empty filter matches every kind).
func (q *Queries) ListActiveWebhooksForOrg(ctx context.Context, arg ListActiveWebhooksForOrgParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooksForOrg, arg.OrgID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.Events,
			&i.Status,
			&i.Ciphertext,
			&i.Nonce,
			&i.WrappedDek,
			&i.DekNonce,
			&i.KekID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.user_id, n.event_id, n.kind, n.title, n.body, n.link, n.read, n.created_at FROM notifications n
WHERE n.user_id = $1
  AND ($3::bool IS NOT TRUE OR n.read = false)
  AND (
    $4::text IS NULL
    OR n.created_at < (SELECT c.created_at FROM notifications c WHERE c.id = $4)
    OR (n.created_at = (SELECT c.created_at FROM notifications c WHERE c.id = $4) AND n.id < $4)
  )
ORDER BY n.created_at DESC, n.id DESC
LIMIT $2
`

type ListNotificationsParams struct {
	UserID string
	Limit  int32
	Unread pgtype.Bool
	Cursor pgtype.Text
}

// Newest-first bell history for a user, keyset-paginated on (created_at, id) —
// ids are random hex (not time-sortable), so the cursor resolves the last row's
// created_at and pages strictly older, with id as the stable tiebreak.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.Limit,
		arg.Unread,
		arg.Cursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMemberRecipients = `-- name: ListOrgMemberRecipients :many

SELECT m.user_id, u.email FROM members m JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
`

type ListOrgMemberRecipientsRow struct {
	UserID string
	Email  string
}

// T10.3: notification routing matrix — bell store, per-user prefs, org webhooks,
// and the webhook delivery outbox (same claim-before-send shape as email).
// The bell/email recipient set for an org event: every member, with the email
// address the email route needs. Per-member prefs gate the actual routing.
func (q *Queries) ListOrgMemberRecipients(ctx context.Context, orgID string) ([]ListOrgMemberRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listOrgMemberRecipients, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgMemberRecipientsRow
	for rows.Next() {
		var i ListOrgMemberRecipientsRow
		if err := rows.Scan(&i.UserID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWebhookEvents = `-- name: ListPendingWebhookEvents :many
SELECT e.id, e.org_id, e.kind, e.via, e.actor, e.action, e.subject, e.at, e.detail, w.id AS webhook_id
FROM events e
JOIN webhooks w
  ON w.org_id = e.org_id AND w.status = 'active'
 AND e.at >= w.created_at -- never backfill events that predate the webhook
 AND (cardinality(w.events) = 0 OR e.kind = ANY(w.events))
LEFT JOIN webhook_deliveries d ON d.webhook_id = w.id AND d.event_id = e.id
WHERE d.id IS NULL OR (d.status NOT IN ('sent', 'skipped') AND d.attempts < 5)
ORDER BY e.at ASC
LIMIT 100
`

type ListPendingWebhookEventsRow struct {
	ID        string
	OrgID     string
	Kind      string
	Via       string
	Actor     string
	Action    string
	Subject   string
	At        pgtype.Timestamptz
	Detail    []byte
	WebhookID string
}

// The durable outbox scan: spine events whose kind an active webhook subscribes
// to and which have no TERMINAL delivery for that webhook (sent/skipped) and are
// not dead-lettered. The spine + ledger ARE the outbox (lossless on restart).
func (q *Queries) ListPendingWebhookEvents(ctx context.Context) ([]ListPendingWebhookEventsRow, error) {
	rows, err := q.db.Query(ctx, listPendingWebhookEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingWebhookEventsRow
	for rows.Next() {
		var i ListPendingWebhookEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Via,
			&i.Actor,
			&i.Action,
			&i.Subject,
			&i.At,
			&i.Detail,
			&i.WebhookID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, org_id, url, events, status, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, created_at FROM webhooks WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWebhooks(ctx context.Context, orgID string) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.Events,
			&i.Status,
			&i.Ciphertext,
			&i.Nonce,
			&i.WrappedDek,
			&i.DekNonce,
			&i.KekID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read = true
WHERE user_id = $1 AND id = ANY($2::text[])
`

type MarkNotificationsReadParams struct {
	UserID string
	Ids    []string
}

// Bulk mark-read, scoped to the owner: ids the caller doesn't own are untouched
// (WHERE user_id) — never a 404 that leaks another user's id space.
func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, arg.UserID, arg.Ids)
	return err
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :exec
UPDATE webhook_deliveries SET status = 'failed', status_code = $2, error = $3, updated_at = now() WHERE id = $1
`

type MarkWebhookDeliveryFailedParams struct {
	ID         string
	StatusCode pgtype.Int4
	Error      pgtype.Text
}

func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryFailed, arg.ID, arg.StatusCode, arg.Error)
	return err
}

const markWebhookDeliverySent = `-- name: MarkWebhookDeliverySent :exec
UPDATE webhook_deliveries SET status = 'sent', status_code = $2, error = NULL, updated_at = now() WHERE id = $1
`

type MarkWebhookDeliverySentParams struct {
	ID         string
	StatusCode pgtype.Int4
}

func (q *Queries) MarkWebhookDeliverySent(ctx context.Context, arg MarkWebhookDeliverySentParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliverySent, arg.ID, arg.StatusCode)
	return err
}

const upsertNotificationPrefs = `-- name: UpsertNotificationPrefs :one
INSERT INTO notification_prefs (user_id, channels, quiet_hours)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
    SET channels = EXCLUDED.channels, quiet_hours = EXCLUDED.quiet_hours, updated_at = now()
RETURNING user_id, channels, quiet_hours, updated_at
`

type UpsertNotificationPrefsParams struct {
	UserID     string
	Channels   []byte
	QuietHours []byte
}

func (q *Queries) UpsertNotificationPrefs(ctx context.Context, arg UpsertNotificationPrefsParams) (NotificationPref, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPrefs, arg.UserID, arg.Channels, arg.QuietHours)
	var i NotificationPref
	err := row.Scan(
		&i.UserID,
		&i.Channels,
		&i.QuietHours,
		&i.UpdatedAt,
	)
	return i, err
}
