// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orgs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM members WHERE org_id = $1
`

func (q *Queries) CountMembers(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (id, org_id, email, role, inviter_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, email, role, status, inviter_id, created_at, expires_at
`

type CreateInviteParams struct {
	ID        string
	OrgID     string
	Email     string
	Role      string
	InviterID string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.InviterID,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InviterID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createOrgFull = `-- name: CreateOrgFull :one

INSERT INTO orgs (id, slug, name, home_region)
VALUES ($1, $2, $3, $4)
RETURNING id, name, created_at, slug, home_region, plan, deletion_scheduled_at
`

type CreateOrgFullParams struct {
	ID         string
	Slug       string
	Name       string
	HomeRegion string
}

// T2.7: org / member / invite governance. Slug is immutable — no query ever
// updates it. Invite expiry is computed against expires_at, never cron-flipped.
func (q *Queries) CreateOrgFull(ctx context.Context, arg CreateOrgFullParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrgFull,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.HomeRegion,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Slug,
		&i.HomeRegion,
		&i.Plan,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (org_id) VALUES ($1) RETURNING org_id, plan, anchor_day, status, trial_ends_at, created_at
`

func (q *Queries) CreateSubscription(ctx context.Context, orgID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, orgID)
	var i Subscription
	err := row.Scan(
		&i.OrgID,
		&i.Plan,
		&i.AnchorDay,
		&i.Status,
		&i.TrialEndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, org_id, email, role, status, inviter_id, created_at, expires_at FROM invites WHERE id = $1
`

func (q *Queries) GetInvite(ctx context.Context, id string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InviterID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT m.id, m.org_id, m.user_id, m.role, m.created_at, u.email, u.name
FROM members m JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1 AND m.id = $2
`

type GetMemberParams struct {
	OrgID string
	ID    string
}

type GetMemberRow struct {
	ID        string
	OrgID     string
	UserID    string
	Role      string
	CreatedAt pgtype.Timestamptz
	Email     string
	Name      string
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, arg.OrgID, arg.ID)
	var i GetMemberRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, created_at, slug, home_region, plan, deletion_scheduled_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Slug,
		&i.HomeRegion,
		&i.Plan,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const getPendingInviteByEmail = `-- name: GetPendingInviteByEmail :one
SELECT id, org_id, email, role, status, inviter_id, created_at, expires_at FROM invites
WHERE org_id = $1 AND lower(email) = lower($2) AND status = 'pending'
`

type GetPendingInviteByEmailParams struct {
	OrgID string
	Lower string
}

func (q *Queries) GetPendingInviteByEmail(ctx context.Context, arg GetPendingInviteByEmailParams) (Invite, error) {
	row := q.db.QueryRow(ctx, getPendingInviteByEmail, arg.OrgID, arg.Lower)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InviterID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const isMemberEmail = `-- name: IsMemberEmail :one
SELECT EXISTS (
    SELECT 1 FROM members m JOIN users u ON u.id = m.user_id
    WHERE m.org_id = $1 AND lower(u.email) = lower($2)
)
`

type IsMemberEmailParams struct {
	OrgID string
	Lower string
}

func (q *Queries) IsMemberEmail(ctx context.Context, arg IsMemberEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMemberEmail, arg.OrgID, arg.Lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, org_id, email, role, status, inviter_id, created_at, expires_at FROM invites WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context, orgID string) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.InviterID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.id, m.org_id, m.user_id, m.role, m.created_at, u.email, u.name
FROM members m JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY m.created_at
`

type ListMembersRow struct {
	ID        string
	OrgID     string
	UserID    string
	Role      string
	CreatedAt pgtype.Timestamptz
	Email     string
	Name      string
}

func (q *Queries) ListMembers(ctx context.Context, orgID string) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgTokens = `-- name: ListOrgTokens :many
SELECT id, kind, user_id, org_id, name, scope, prefix, token_hash, expires_at, last_used_at, created_at, revoked_at, permissions FROM tokens
WHERE kind = 'org' AND org_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListOrgTokens(ctx context.Context, orgID pgtype.Text) ([]Token, error) {
	rows, err := q.db.Query(ctx, listOrgTokens, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.Scope,
			&i.Prefix,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT o.id, o.name, o.created_at, o.slug, o.home_region, o.plan, o.deletion_scheduled_at FROM orgs o
JOIN members m ON m.org_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at
`

func (q *Queries) ListOrgsForUser(ctx context.Context, userID string) ([]Org, error) {
	rows, err := q.db.Query(ctx, listOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Slug,
			&i.HomeRegion,
			&i.Plan,
			&i.DeletionScheduledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :one
DELETE FROM members WHERE org_id = $1 AND id = $2 RETURNING id, org_id, user_id, role, created_at
`

type RemoveMemberParams struct {
	OrgID string
	ID    string
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, removeMember, arg.OrgID, arg.ID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllPersonalTokensForUser = `-- name: RevokeAllPersonalTokensForUser :exec
UPDATE tokens SET revoked_at = now()
WHERE kind = 'personal' AND user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllPersonalTokensForUser(ctx context.Context, userID pgtype.Text) error {
	_, err := q.db.Exec(ctx, revokeAllPersonalTokensForUser, userID)
	return err
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec

UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// G6 removal semantics (design spec): "sessions + tokens revoked
// immediately"; G8: "if the org removes you, every personal token dies with
// the membership."
func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsForUser, userID)
	return err
}

const scheduleOrgDeletion = `-- name: ScheduleOrgDeletion :execrows
UPDATE orgs SET deletion_scheduled_at = now()
WHERE id = $1 AND deletion_scheduled_at IS NULL
`

func (q *Queries) ScheduleOrgDeletion(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, scheduleOrgDeletion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInviteStatus = `-- name: SetInviteStatus :execrows
UPDATE invites SET status = $2 WHERE id = $1 AND status = 'pending'
`

type SetInviteStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) SetInviteStatus(ctx context.Context, arg SetInviteStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInviteStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE members SET role = $3 WHERE org_id = $1 AND id = $2 RETURNING id, org_id, user_id, role, created_at
`

type UpdateMemberRoleParams struct {
	OrgID string
	ID    string
	Role  string
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.OrgID, arg.ID, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE orgs SET
    name = coalesce($2, name),
    home_region = coalesce($3, home_region)
WHERE id = $1
RETURNING id, name, created_at, slug, home_region, plan, deletion_scheduled_at
`

type UpdateOrgParams struct {
	ID         string
	Name       pgtype.Text
	HomeRegion pgtype.Text
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrg, arg.ID, arg.Name, arg.HomeRegion)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Slug,
		&i.HomeRegion,
		&i.Plan,
		&i.DeletionScheduledAt,
	)
	return i, err
}
