// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeResetToken = `-- name: ConsumeResetToken :execrows
UPDATE password_reset_tokens SET used_at = now()
WHERE id = $1 AND used_at IS NULL AND expires_at > now()
`

// Single-use: marks used only if not already used and not expired. 0 rows = the
// token was already spent or has expired.
func (q *Queries) ConsumeResetToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, consumeResetToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getResetToken = `-- name: GetResetToken :one
SELECT id, user_id, token_hash, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, expires_at, used_at, created_at FROM password_reset_tokens WHERE id = $1
`

func (q *Queries) GetResetToken(ctx context.Context, id string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getResetToken, id)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedDek,
		&i.DekNonce,
		&i.KekID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getResetTokenByHash = `-- name: GetResetTokenByHash :one
SELECT id, user_id, token_hash, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, expires_at, used_at, created_at FROM password_reset_tokens WHERE token_hash = $1
`

func (q *Queries) GetResetTokenByHash(ctx context.Context, tokenHash []byte) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedDek,
		&i.DekNonce,
		&i.KekID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertResetToken = `-- name: InsertResetToken :exec

INSERT INTO password_reset_tokens (id, user_id, token_hash, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertResetTokenParams struct {
	ID         string
	UserID     string
	TokenHash  []byte
	Ciphertext []byte
	Nonce      []byte
	WrappedDek []byte
	DekNonce   []byte
	KekID      string
	ExpiresAt  pgtype.Timestamptz
}

// T7.2: password reset tokens.
func (q *Queries) InsertResetToken(ctx context.Context, arg InsertResetTokenParams) error {
	_, err := q.db.Exec(ctx, insertResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedDek,
		arg.DekNonce,
		arg.KekID,
		arg.ExpiresAt,
	)
	return err
}

const listPendingResetEmails = `-- name: ListPendingResetEmails :many
SELECT t.id FROM password_reset_tokens t
LEFT JOIN email_deliveries d ON d.event_id = t.id
WHERE t.expires_at > now() AND t.used_at IS NULL
  AND (d.id IS NULL OR (d.status NOT IN ('sent', 'skipped') AND d.attempts < 5))
ORDER BY t.created_at ASC
LIMIT 100
`

// Account-level email outbox: reset tokens still valid that have no terminal
// email delivery yet. The reset-token row is the durable trigger (account auth
// is not an org-spine fact); email_deliveries (keyed by the token id) is the
// idempotency ledger, shared with the org-event outbox.
func (q *Queries) ListPendingResetEmails(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPendingResetEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           string
	PasswordHash string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}
