// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrgMembers = `-- name: CountOrgMembers :one
SELECT count(*) FROM members WHERE org_id = $1
`

func (q *Queries) CountOrgMembers(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgMembers, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPolicyViolations30d = `-- name: CountPolicyViolations30d :one
SELECT count(*) FROM events
WHERE org_id = $1
  AND action = 'authz.denied'
  AND at > now() - interval '30 days'
  AND detail->>'denied_by' LIKE 'policy:' || $2 || '%'
`

type CountPolicyViolations30dParams struct {
	OrgID   string
	Column2 pgtype.Text
}

// Warn-mode telemetry (G12): denials attributed to this policy key on the spine
// in the trailing 30 days — what makes promote-to-enforce a data-backed click.
func (q *Queries) CountPolicyViolations30d(ctx context.Context, arg CountPolicyViolations30dParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPolicyViolations30d, arg.OrgID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSameKeyPolicies = `-- name: CountSameKeyPolicies :one
SELECT count(*) FROM policies
WHERE org_id = $1 AND key = $2
  AND (project_id IS NULL OR project_id IS NOT DISTINCT FROM $3)
`

type CountSameKeyPoliciesParams struct {
	OrgID     string
	Key       string
	ProjectID pgtype.Text
}

// Conflict detection for dry-run: existing policies of the same key attached at
// an overlapping scope (org-wide, or the same project).
func (q *Queries) CountSameKeyPolicies(ctx context.Context, arg CountSameKeyPoliciesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSameKeyPolicies, arg.OrgID, arg.Key, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPolicyByID = `-- name: GetPolicyByID :one
SELECT id, org_id, project_id, key, enforcement, config, created_at, rule, description, version, enforce_from, last_change_event, updated_at FROM policies WHERE id = $1
`

func (q *Queries) GetPolicyByID(ctx context.Context, id string) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByID, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Key,
		&i.Enforcement,
		&i.Config,
		&i.CreatedAt,
		&i.Rule,
		&i.Description,
		&i.Version,
		&i.EnforceFrom,
		&i.LastChangeEvent,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPolicy = `-- name: InsertPolicy :one

INSERT INTO policies (id, org_id, project_id, key, enforcement, rule, config, description, enforce_from, version, last_change_event)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 1, $10)
RETURNING id, org_id, project_id, key, enforcement, config, created_at, rule, description, version, enforce_from, last_change_event, updated_at
`

type InsertPolicyParams struct {
	ID              string
	OrgID           string
	ProjectID       pgtype.Text
	Key             string
	Enforcement     string
	Rule            []byte
	Config          []byte
	Description     pgtype.Text
	EnforceFrom     pgtype.Timestamptz
	LastChangeEvent pgtype.Text
}

// T12.1: policy authoring (CRUD + versioning). Evaluation queries live in
// identity.sql (ListPoliciesForOrg); these are the authoring surface.
func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, insertPolicy,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Key,
		arg.Enforcement,
		arg.Rule,
		arg.Config,
		arg.Description,
		arg.EnforceFrom,
		arg.LastChangeEvent,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Key,
		&i.Enforcement,
		&i.Config,
		&i.CreatedAt,
		&i.Rule,
		&i.Description,
		&i.Version,
		&i.EnforceFrom,
		&i.LastChangeEvent,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPolicyVersion = `-- name: InsertPolicyVersion :exec
INSERT INTO policy_versions (id, policy_id, version, key, enforcement, rule, config, description, enforce_from, change_event, changed_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertPolicyVersionParams struct {
	ID          string
	PolicyID    string
	Version     int32
	Key         string
	Enforcement string
	Rule        []byte
	Config      []byte
	Description pgtype.Text
	EnforceFrom pgtype.Timestamptz
	ChangeEvent pgtype.Text
	ChangedBy   string
}

func (q *Queries) InsertPolicyVersion(ctx context.Context, arg InsertPolicyVersionParams) error {
	_, err := q.db.Exec(ctx, insertPolicyVersion,
		arg.ID,
		arg.PolicyID,
		arg.Version,
		arg.Key,
		arg.Enforcement,
		arg.Rule,
		arg.Config,
		arg.Description,
		arg.EnforceFrom,
		arg.ChangeEvent,
		arg.ChangedBy,
	)
	return err
}

const listPoliciesPage = `-- name: ListPoliciesPage :many
SELECT id, org_id, project_id, key, enforcement, config, created_at, rule, description, version, enforce_from, last_change_event, updated_at FROM policies WHERE org_id = $1 ORDER BY created_at DESC, id
`

func (q *Queries) ListPoliciesPage(ctx context.Context, orgID string) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPoliciesPage, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Key,
			&i.Enforcement,
			&i.Config,
			&i.CreatedAt,
			&i.Rule,
			&i.Description,
			&i.Version,
			&i.EnforceFrom,
			&i.LastChangeEvent,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyVersions = `-- name: ListPolicyVersions :many
SELECT id, policy_id, version, key, enforcement, rule, config, description, enforce_from, change_event, changed_by, created_at FROM policy_versions WHERE policy_id = $1 ORDER BY version DESC
`

func (q *Queries) ListPolicyVersions(ctx context.Context, policyID string) ([]PolicyVersion, error) {
	rows, err := q.db.Query(ctx, listPolicyVersions, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyVersion
	for rows.Next() {
		var i PolicyVersion
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Version,
			&i.Key,
			&i.Enforcement,
			&i.Rule,
			&i.Config,
			&i.Description,
			&i.EnforceFrom,
			&i.ChangeEvent,
			&i.ChangedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSameKeyPolicies = `-- name: ListSameKeyPolicies :many
SELECT id, org_id, project_id, key, enforcement, config, created_at, rule, description, version, enforce_from, last_change_event, updated_at FROM policies
WHERE org_id = $1 AND key = $2
  AND (project_id IS NULL OR project_id IS NOT DISTINCT FROM $3)
`

type ListSameKeyPoliciesParams struct {
	OrgID     string
	Key       string
	ProjectID pgtype.Text
}

func (q *Queries) ListSameKeyPolicies(ctx context.Context, arg ListSameKeyPoliciesParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listSameKeyPolicies, arg.OrgID, arg.Key, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Key,
			&i.Enforcement,
			&i.Config,
			&i.CreatedAt,
			&i.Rule,
			&i.Description,
			&i.Version,
			&i.EnforceFrom,
			&i.LastChangeEvent,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicyRow = `-- name: UpdatePolicyRow :one
UPDATE policies SET
    enforcement = $2,
    rule = $3,
    config = $4,
    description = $5,
    enforce_from = $6,
    version = version + 1,
    last_change_event = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, org_id, project_id, key, enforcement, config, created_at, rule, description, version, enforce_from, last_change_event, updated_at
`

type UpdatePolicyRowParams struct {
	ID              string
	Enforcement     string
	Rule            []byte
	Config          []byte
	Description     pgtype.Text
	EnforceFrom     pgtype.Timestamptz
	LastChangeEvent pgtype.Text
}

// Bumps the version and stamps the audit link; the caller writes the matching
// policy_versions history row in the same transaction.
func (q *Queries) UpdatePolicyRow(ctx context.Context, arg UpdatePolicyRowParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicyRow,
		arg.ID,
		arg.Enforcement,
		arg.Rule,
		arg.Config,
		arg.Description,
		arg.EnforceFrom,
		arg.LastChangeEvent,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Key,
		&i.Enforcement,
		&i.Config,
		&i.CreatedAt,
		&i.Rule,
		&i.Description,
		&i.Version,
		&i.EnforceFrom,
		&i.LastChangeEvent,
		&i.UpdatedAt,
	)
	return i, err
}
