// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnvironments = `-- name: CountEnvironments :one
SELECT count(*) FROM environments WHERE project_id = $1
`

func (q *Queries) CountEnvironments(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironments, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects WHERE org_id = $1 AND deletion_scheduled_at IS NULL
`

func (q *Queries) CountProjects(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (id, project_id, name, region_override, kind, implicit)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, region_override, kind, policy_flags, expires_at, created_at, implicit, deletion_scheduled_at, torn_down_at
`

type CreateEnvironmentParams struct {
	ID             string
	ProjectID      string
	Name           string
	RegionOverride pgtype.Text
	Kind           string
	Implicit       bool
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.RegionOverride,
		arg.Kind,
		arg.Implicit,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RegionOverride,
		&i.Kind,
		&i.PolicyFlags,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Implicit,
		&i.DeletionScheduledAt,
		&i.TornDownAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (id, org_id, name)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, cell_id, deletion_scheduled_at, created_at
`

type CreateProjectParams struct {
	ID    string
	OrgID string
	Name  string
}

// T3.2: projects + environments. cell_id never leaves the store layer (D8).
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.ID, arg.OrgID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CellID,
		&i.DeletionScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project_id, name, region_override, kind, policy_flags, expires_at, created_at, implicit, deletion_scheduled_at, torn_down_at FROM environments WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RegionOverride,
		&i.Kind,
		&i.PolicyFlags,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Implicit,
		&i.DeletionScheduledAt,
		&i.TornDownAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, name, cell_id, deletion_scheduled_at, created_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CellID,
		&i.DeletionScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, project_id, name, region_override, kind, policy_flags, expires_at, created_at, implicit, deletion_scheduled_at, torn_down_at FROM environments WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListEnvironments(ctx context.Context, projectID string) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.RegionOverride,
			&i.Kind,
			&i.PolicyFlags,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Implicit,
			&i.DeletionScheduledAt,
			&i.TornDownAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForOrg = `-- name: ListProjectsForOrg :many
SELECT p.id, p.org_id, p.name, p.cell_id, p.deletion_scheduled_at, p.created_at,
       (SELECT count(*) FROM environments e WHERE e.project_id = p.id) AS env_count
FROM projects p
WHERE p.org_id = $1
ORDER BY p.created_at
`

type ListProjectsForOrgRow struct {
	ID                  string
	OrgID               string
	Name                string
	CellID              string
	DeletionScheduledAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	EnvCount            int64
}

func (q *Queries) ListProjectsForOrg(ctx context.Context, orgID string) ([]ListProjectsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listProjectsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsForOrgRow
	for rows.Next() {
		var i ListProjectsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CellID,
			&i.DeletionScheduledAt,
			&i.CreatedAt,
			&i.EnvCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgForEnvironment = `-- name: OrgForEnvironment :one
SELECT p.org_id FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE e.id = $1
`

// The events EnvResolver seam (T2.5) closes with this join.
func (q *Queries) OrgForEnvironment(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, orgForEnvironment, id)
	var org_id string
	err := row.Scan(&org_id)
	return org_id, err
}

const renameEnvironment = `-- name: RenameEnvironment :one
UPDATE environments SET name = $2 WHERE id = $1 RETURNING id, project_id, name, region_override, kind, policy_flags, expires_at, created_at, implicit, deletion_scheduled_at, torn_down_at
`

type RenameEnvironmentParams struct {
	ID   string
	Name string
}

func (q *Queries) RenameEnvironment(ctx context.Context, arg RenameEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, renameEnvironment, arg.ID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RegionOverride,
		&i.Kind,
		&i.PolicyFlags,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Implicit,
		&i.DeletionScheduledAt,
		&i.TornDownAt,
	)
	return i, err
}

const renameProject = `-- name: RenameProject :one
UPDATE projects SET name = $2 WHERE id = $1 RETURNING id, org_id, name, cell_id, deletion_scheduled_at, created_at
`

type RenameProjectParams struct {
	ID   string
	Name string
}

func (q *Queries) RenameProject(ctx context.Context, arg RenameProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, renameProject, arg.ID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CellID,
		&i.DeletionScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const scheduleEnvDeletion = `-- name: ScheduleEnvDeletion :execrows
UPDATE environments SET deletion_scheduled_at = now()
WHERE id = $1 AND deletion_scheduled_at IS NULL
`

func (q *Queries) ScheduleEnvDeletion(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, scheduleEnvDeletion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scheduleProjectDeletion = `-- name: ScheduleProjectDeletion :execrows
UPDATE projects SET deletion_scheduled_at = now()
WHERE id = $1 AND deletion_scheduled_at IS NULL
`

func (q *Queries) ScheduleProjectDeletion(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, scheduleProjectDeletion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
