// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quota.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuotaUsage = `-- name: GetQuotaUsage :many
SELECT org_id, meter, period, used, rate_cents, computed_at FROM quota_usage WHERE org_id = $1 AND period = $2 ORDER BY meter
`

type GetQuotaUsageParams struct {
	OrgID  string
	Period string
}

func (q *Queries) GetQuotaUsage(ctx context.Context, arg GetQuotaUsageParams) ([]QuotaUsage, error) {
	rows, err := q.db.Query(ctx, getQuotaUsage, arg.OrgID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaUsage
	for rows.Next() {
		var i QuotaUsage
		if err := rows.Scan(
			&i.OrgID,
			&i.Meter,
			&i.Period,
			&i.Used,
			&i.RateCents,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spanEdgesForOrg = `-- name: SpanEdgesForOrg :many
SELECT service_id, edge, product, rate_cents, at FROM usage_events
WHERE org_id = $1 AND meter = 'service_span' AND at < $2
ORDER BY service_id, at
`

type SpanEdgesForOrgParams struct {
	OrgID string
	At    pgtype.Timestamptz
}

type SpanEdgesForOrgRow struct {
	ServiceID string
	Edge      string
	Product   string
	RateCents int64
	At        pgtype.Timestamptz
}

func (q *Queries) SpanEdgesForOrg(ctx context.Context, arg SpanEdgesForOrgParams) ([]SpanEdgesForOrgRow, error) {
	rows, err := q.db.Query(ctx, spanEdgesForOrg, arg.OrgID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpanEdgesForOrgRow
	for rows.Next() {
		var i SpanEdgesForOrgRow
		if err := rows.Scan(
			&i.ServiceID,
			&i.Edge,
			&i.Product,
			&i.RateCents,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertQuotaUsage = `-- name: UpsertQuotaUsage :exec

INSERT INTO quota_usage (org_id, meter, period, used, rate_cents, computed_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (org_id, meter, period)
DO UPDATE SET used = EXCLUDED.used, rate_cents = EXCLUDED.rate_cents, computed_at = now()
`

type UpsertQuotaUsageParams struct {
	OrgID     string
	Meter     string
	Period    string
	Used      int64
	RateCents int64
}

// T6.3: the rollup. RollupServiceSpans recomputes one org+period from the
// RAW spans — pure derivation, idempotent by construction (upsert of a
// deterministic aggregate; raw events are never touched).
//
// Span seconds: close edges pair with the latest earlier open edge per
// service; spans still open at rollup time accrue to the period bound.
func (q *Queries) UpsertQuotaUsage(ctx context.Context, arg UpsertQuotaUsageParams) error {
	_, err := q.db.Exec(ctx, upsertQuotaUsage,
		arg.OrgID,
		arg.Meter,
		arg.Period,
		arg.Used,
		arg.RateCents,
	)
	return err
}
