// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reconcile.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpServiceGeneration = `-- name: BumpServiceGeneration :one
UPDATE services
SET desired = $2, generation = generation + 1
WHERE id = $1
RETURNING id, env_id, name, product, intent, status, shape, scaling, override, provisioning_steps, monthly_estimate_cents, estimate_id, cell_id, created_at, desired, generation, observed_generation, last_reconciled_at
`

type BumpServiceGenerationParams struct {
	ID      string
	Desired []byte
}

// Every desired-state EDIT bumps the generation so the agent re-reconciles.
// A freshly created service is already outstanding (observed 0 < generation 1),
// so creation needs no bump. Wiring this into updateService/deleteService (so
// shape edits and deletes reach the cell) is provisioning-side and OUT of
// US-1.3's scope — tracked as a follow-up (US-1.3a). Reconciler endpoints never
// call this; only desired-state writers do.
func (q *Queries) BumpServiceGeneration(ctx context.Context, arg BumpServiceGenerationParams) (Service, error) {
	row := q.db.QueryRow(ctx, bumpServiceGeneration, arg.ID, arg.Desired)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Name,
		&i.Product,
		&i.Intent,
		&i.Status,
		&i.Shape,
		&i.Scaling,
		&i.Override,
		&i.ProvisioningSteps,
		&i.MonthlyEstimateCents,
		&i.EstimateID,
		&i.CellID,
		&i.CreatedAt,
		&i.Desired,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LastReconciledAt,
	)
	return i, err
}

const getCell = `-- name: GetCell :one

SELECT id, region, status, agent_last_seen_at, created_at FROM cells WHERE id = $1
`

// US-1.3: the reconciler protocol (D9/A2.5, e1-substrate-design.md §2). The
// control plane writes desired state; the cell-agent converges actual and
// reports back. Nothing in this file provisions anything.
// Cell lookup for token scoping. An unknown cell is a 404 at the handler — a
// reconciler token must never learn which other cells exist.
func (q *Queries) GetCell(ctx context.Context, id string) (Cell, error) {
	row := q.db.QueryRow(ctx, getCell, id)
	var i Cell
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.Status,
		&i.AgentLastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDesiredForCell = `-- name: ListDesiredForCell :many
SELECT id, env_id, name, product, intent, status, shape, scaling,
       desired, generation, observed_generation, cell_id, last_reconciled_at
FROM services
WHERE cell_id = $1 AND observed_generation < generation AND generation > $2
ORDER BY generation, id
LIMIT $3
`

type ListDesiredForCellParams struct {
	CellID     string
	Generation int64
	Limit      int32
}

type ListDesiredForCellRow struct {
	ID                 string
	EnvID              string
	Name               string
	Product            string
	Intent             pgtype.Text
	Status             string
	Shape              []byte
	Scaling            []byte
	Desired            []byte
	Generation         int64
	ObservedGeneration int64
	CellID             string
	LastReconciledAt   pgtype.Timestamptz
}

// The agent's poll: every service in this cell with OUTSTANDING work — desired
// has moved ahead of what the cell has converged (observed_generation <
// generation). This is the level-triggered controller shape: the control plane
// knows what needs reconciling, so the agent needs no client-side cursor (a
// per-row generation cannot be a cell-wide cursor — that starves new services).
// The full desired doc rides every row, so the agent never diffs by memory.
// since_generation ($2) is an optional additional lower bound (0 = all work).
func (q *Queries) ListDesiredForCell(ctx context.Context, arg ListDesiredForCellParams) ([]ListDesiredForCellRow, error) {
	rows, err := q.db.Query(ctx, listDesiredForCell, arg.CellID, arg.Generation, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDesiredForCellRow
	for rows.Next() {
		var i ListDesiredForCellRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Name,
			&i.Product,
			&i.Intent,
			&i.Status,
			&i.Shape,
			&i.Scaling,
			&i.Desired,
			&i.Generation,
			&i.ObservedGeneration,
			&i.CellID,
			&i.LastReconciledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markObserved = `-- name: MarkObserved :one
UPDATE services
SET observed_generation = $2,
    last_reconciled_at  = now()
WHERE id = $1 AND generation = $2
RETURNING id, env_id, name, product, intent, status, shape, scaling, override, provisioning_steps, monthly_estimate_cents, estimate_id, cell_id, created_at, desired, generation, observed_generation, last_reconciled_at
`

type MarkObservedParams struct {
	ID                 string
	ObservedGeneration int64
}

// Status writeback's bookkeeping half: record that the cell has converged the
// CURRENT generation. The guard `generation = $2` is exact — it rejects a
// report for any generation other than the one desired holds right now:
//   - behind (agent converged an older desired that has since bumped): rejected,
//     so a stale converge never marks newer desired as done or drives status;
//   - ahead (impossible; a replay/bug reporting a generation desired never had):
//     rejected.
//
// Returns no row on rejection — the agent re-polls (the row is still outstanding)
// and converges the current generation. Idempotent: a duplicate report for the
// current generation re-sets observed to the same value.
func (q *Queries) MarkObserved(ctx context.Context, arg MarkObservedParams) (Service, error) {
	row := q.db.QueryRow(ctx, markObserved, arg.ID, arg.ObservedGeneration)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Name,
		&i.Product,
		&i.Intent,
		&i.Status,
		&i.Shape,
		&i.Scaling,
		&i.Override,
		&i.ProvisioningSteps,
		&i.MonthlyEstimateCents,
		&i.EstimateID,
		&i.CellID,
		&i.CreatedAt,
		&i.Desired,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LastReconciledAt,
	)
	return i, err
}

const touchCellHeartbeat = `-- name: TouchCellHeartbeat :exec
UPDATE cells SET agent_last_seen_at = now() WHERE id = $1
`

// The heartbeat rides the status call (§2 step 4) — there is no separate
// endpoint to forget to call.
func (q *Queries) TouchCellHeartbeat(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchCellHeartbeat, id)
	return err
}
