// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reconcile.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpServiceGeneration = `-- name: BumpServiceGeneration :one
UPDATE services
SET desired = $2, generation = generation + 1
WHERE id = $1
RETURNING id, env_id, name, product, intent, status, shape, scaling, override, provisioning_steps, monthly_estimate_cents, estimate_id, cell_id, created_at, desired, generation, observed_generation, last_reconciled_at
`

type BumpServiceGenerationParams struct {
	ID      string
	Desired []byte
}

// Every desired-state edit bumps the generation so the agent notices. Callers
// are the desired-state writers (createService, shape/scaling edits), never a
// reconciler endpoint.
func (q *Queries) BumpServiceGeneration(ctx context.Context, arg BumpServiceGenerationParams) (Service, error) {
	row := q.db.QueryRow(ctx, bumpServiceGeneration, arg.ID, arg.Desired)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Name,
		&i.Product,
		&i.Intent,
		&i.Status,
		&i.Shape,
		&i.Scaling,
		&i.Override,
		&i.ProvisioningSteps,
		&i.MonthlyEstimateCents,
		&i.EstimateID,
		&i.CellID,
		&i.CreatedAt,
		&i.Desired,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LastReconciledAt,
	)
	return i, err
}

const getCell = `-- name: GetCell :one

SELECT id, region, status, agent_last_seen_at, created_at FROM cells WHERE id = $1
`

// US-1.3: the reconciler protocol (D9/A2.5, e1-substrate-design.md §2). The
// control plane writes desired state; the cell-agent converges actual and
// reports back. Nothing in this file provisions anything.
// Cell lookup for token scoping. An unknown cell is a 404 at the handler — a
// reconciler token must never learn which other cells exist.
func (q *Queries) GetCell(ctx context.Context, id string) (Cell, error) {
	row := q.db.QueryRow(ctx, getCell, id)
	var i Cell
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.Status,
		&i.AgentLastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDesiredForCell = `-- name: ListDesiredForCell :many
SELECT id, env_id, name, product, intent, status, shape, scaling,
       desired, generation, observed_generation, cell_id, last_reconciled_at
FROM services
WHERE cell_id = $1 AND generation > $2
ORDER BY generation, id
LIMIT $3
`

type ListDesiredForCellParams struct {
	CellID     string
	Generation int64
	Limit      int32
}

type ListDesiredForCellRow struct {
	ID                 string
	EnvID              string
	Name               string
	Product            string
	Intent             pgtype.Text
	Status             string
	Shape              []byte
	Scaling            []byte
	Desired            []byte
	Generation         int64
	ObservedGeneration int64
	CellID             string
	LastReconciledAt   pgtype.Timestamptz
}

// The agent's poll: every service in this cell whose desired state has moved
// past what the agent last observed. Level-triggered — the full desired doc is
// returned every time, so the agent never diffs by memory (§2 step 2).
func (q *Queries) ListDesiredForCell(ctx context.Context, arg ListDesiredForCellParams) ([]ListDesiredForCellRow, error) {
	rows, err := q.db.Query(ctx, listDesiredForCell, arg.CellID, arg.Generation, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDesiredForCellRow
	for rows.Next() {
		var i ListDesiredForCellRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Name,
			&i.Product,
			&i.Intent,
			&i.Status,
			&i.Shape,
			&i.Scaling,
			&i.Desired,
			&i.Generation,
			&i.ObservedGeneration,
			&i.CellID,
			&i.LastReconciledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markObserved = `-- name: MarkObserved :one
UPDATE services
SET observed_generation = GREATEST(observed_generation, $2),
    last_reconciled_at  = now()
WHERE id = $1 AND generation >= $2
RETURNING id, env_id, name, product, intent, status, shape, scaling, override, provisioning_steps, monthly_estimate_cents, estimate_id, cell_id, created_at, desired, generation, observed_generation, last_reconciled_at
`

type MarkObservedParams struct {
	ID                 string
	ObservedGeneration int64
}

// Status writeback's bookkeeping half: advance observed_generation and stamp
// last_reconciled_at. The guard `generation >= $2` rejects a STALE report — a
// slow agent reporting on an older generation must not mark newer desired
// state as converged. Returns no row when the report is stale.
func (q *Queries) MarkObserved(ctx context.Context, arg MarkObservedParams) (Service, error) {
	row := q.db.QueryRow(ctx, markObserved, arg.ID, arg.ObservedGeneration)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Name,
		&i.Product,
		&i.Intent,
		&i.Status,
		&i.Shape,
		&i.Scaling,
		&i.Override,
		&i.ProvisioningSteps,
		&i.MonthlyEstimateCents,
		&i.EstimateID,
		&i.CellID,
		&i.CreatedAt,
		&i.Desired,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LastReconciledAt,
	)
	return i, err
}

const touchCellHeartbeat = `-- name: TouchCellHeartbeat :exec
UPDATE cells SET agent_last_seen_at = now() WHERE id = $1
`

// The heartbeat rides the status call (§2 step 4) — there is no separate
// endpoint to forget to call.
func (q *Queries) TouchCellHeartbeat(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchCellHeartbeat, id)
	return err
}
