// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secrets
WHERE org_id = $1
  AND project_id IS NOT DISTINCT FROM $3::text
  AND env_id IS NOT DISTINCT FROM $4::text
  AND name = $2
`

type DeleteSecretParams struct {
	OrgID     string
	Name      string
	ProjectID pgtype.Text
	EnvID     pgtype.Text
}

// All versions of a scope+name (consumed by unbind/rotation flows).
func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret,
		arg.OrgID,
		arg.Name,
		arg.ProjectID,
		arg.EnvID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSecret = `-- name: InsertSecret :one

INSERT INTO secrets (id, org_id, project_id, env_id, name, version, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, org_id, project_id, env_id, name, version, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, created_by, created_at
`

type InsertSecretParams struct {
	ID         string
	OrgID      string
	ProjectID  pgtype.Text
	EnvID      pgtype.Text
	Name       string
	Version    int32
	Ciphertext []byte
	Nonce      []byte
	WrappedDek []byte
	DekNonce   []byte
	KekID      string
	CreatedBy  string
}

// T3.5: secrets — internal-only service; rows carry ciphertext, never
// plaintext. Reads take the latest version for a scope+name.
func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, insertSecret,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvID,
		arg.Name,
		arg.Version,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedDek,
		arg.DekNonce,
		arg.KekID,
		arg.CreatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvID,
		&i.Name,
		&i.Version,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedDek,
		&i.DekNonce,
		&i.KekID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestSecret = `-- name: LatestSecret :one
SELECT id, org_id, project_id, env_id, name, version, ciphertext, nonce, wrapped_dek, dek_nonce, kek_id, created_by, created_at FROM secrets
WHERE org_id = $1
  AND project_id IS NOT DISTINCT FROM $3::text
  AND env_id IS NOT DISTINCT FROM $4::text
  AND name = $2
ORDER BY version DESC
LIMIT 1
`

type LatestSecretParams struct {
	OrgID     string
	Name      string
	ProjectID pgtype.Text
	EnvID     pgtype.Text
}

func (q *Queries) LatestSecret(ctx context.Context, arg LatestSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, latestSecret,
		arg.OrgID,
		arg.Name,
		arg.ProjectID,
		arg.EnvID,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvID,
		&i.Name,
		&i.Version,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedDek,
		&i.DekNonce,
		&i.KekID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestSecretVersion = `-- name: LatestSecretVersion :one
SELECT coalesce(max(version), 0)::int FROM secrets
WHERE org_id = $1
  AND project_id IS NOT DISTINCT FROM $3::text
  AND env_id IS NOT DISTINCT FROM $4::text
  AND name = $2
`

type LatestSecretVersionParams struct {
	OrgID     string
	Name      string
	ProjectID pgtype.Text
	EnvID     pgtype.Text
}

func (q *Queries) LatestSecretVersion(ctx context.Context, arg LatestSecretVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, latestSecretVersion,
		arg.OrgID,
		arg.Name,
		arg.ProjectID,
		arg.EnvID,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
