// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countServicesForEnvs = `-- name: CountServicesForEnvs :one
SELECT count(*) FROM services s
JOIN environments e ON e.id = s.env_id
WHERE e.project_id = $1 AND s.status <> 'deleting'
`

func (q *Queries) CountServicesForEnvs(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countServicesForEnvs, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getService = `-- name: GetService :one
SELECT id, env_id, name, product, intent, status, shape, scaling, override, provisioning_steps, monthly_estimate_cents, estimate_id, cell_id, created_at, desired, generation, observed_generation, last_reconciled_at FROM services WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id string) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Name,
		&i.Product,
		&i.Intent,
		&i.Status,
		&i.Shape,
		&i.Scaling,
		&i.Override,
		&i.ProvisioningSteps,
		&i.MonthlyEstimateCents,
		&i.EstimateID,
		&i.CellID,
		&i.CreatedAt,
		&i.Desired,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LastReconciledAt,
	)
	return i, err
}

const insertService = `-- name: InsertService :one

INSERT INTO services (id, env_id, name, product, intent, shape, scaling, provisioning_steps, monthly_estimate_cents, estimate_id, desired)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, coalesce($11, '{}'::jsonb)
)
RETURNING id, env_id, name, product, intent, status, shape, scaling, override, provisioning_steps, monthly_estimate_cents, estimate_id, cell_id, created_at, desired, generation, observed_generation, last_reconciled_at
`

type InsertServiceParams struct {
	ID                   string
	EnvID                string
	Name                 string
	Product              string
	Intent               pgtype.Text
	Shape                []byte
	Scaling              []byte
	ProvisioningSteps    []byte
	MonthlyEstimateCents int64
	EstimateID           pgtype.Text
	Desired              interface{}
}

// T3.3: services — desired state. Status writes go through the guarded
// machine in Go; SetServiceStatus enforces the FROM state in SQL too.
// desired is the reconciler's input (US-1.3a): populated at creation from the
// shape so the agent has a real document to render from. generation defaults to
// 1, observed_generation to 0, so a fresh service is immediately outstanding.
func (q *Queries) InsertService(ctx context.Context, arg InsertServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, insertService,
		arg.ID,
		arg.EnvID,
		arg.Name,
		arg.Product,
		arg.Intent,
		arg.Shape,
		arg.Scaling,
		arg.ProvisioningSteps,
		arg.MonthlyEstimateCents,
		arg.EstimateID,
		arg.Desired,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Name,
		&i.Product,
		&i.Intent,
		&i.Status,
		&i.Shape,
		&i.Scaling,
		&i.Override,
		&i.ProvisioningSteps,
		&i.MonthlyEstimateCents,
		&i.EstimateID,
		&i.CellID,
		&i.CreatedAt,
		&i.Desired,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LastReconciledAt,
	)
	return i, err
}

const listServicesForEnv = `-- name: ListServicesForEnv :many
SELECT id, env_id, name, product, intent, status, shape, scaling, override, provisioning_steps, monthly_estimate_cents, estimate_id, cell_id, created_at, desired, generation, observed_generation, last_reconciled_at FROM services WHERE env_id = $1 ORDER BY created_at
`

func (q *Queries) ListServicesForEnv(ctx context.Context, envID string) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesForEnv, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Name,
			&i.Product,
			&i.Intent,
			&i.Status,
			&i.Shape,
			&i.Scaling,
			&i.Override,
			&i.ProvisioningSteps,
			&i.MonthlyEstimateCents,
			&i.EstimateID,
			&i.CellID,
			&i.CreatedAt,
			&i.Desired,
			&i.Generation,
			&i.ObservedGeneration,
			&i.LastReconciledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgForService = `-- name: OrgForService :one
SELECT p.org_id FROM services s
JOIN environments e ON e.id = s.env_id
JOIN projects p ON p.id = e.project_id
WHERE s.id = $1
`

func (q *Queries) OrgForService(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, orgForService, id)
	var org_id string
	err := row.Scan(&org_id)
	return org_id, err
}

const setServiceStatus = `-- name: SetServiceStatus :one
UPDATE services SET status = $3, provisioning_steps = coalesce($4, provisioning_steps)
WHERE id = $1 AND status = $2
RETURNING id, env_id, name, product, intent, status, shape, scaling, override, provisioning_steps, monthly_estimate_cents, estimate_id, cell_id, created_at, desired, generation, observed_generation, last_reconciled_at
`

type SetServiceStatusParams struct {
	ID       string
	Status   string
	Status_2 string
	Steps    []byte
}

func (q *Queries) SetServiceStatus(ctx context.Context, arg SetServiceStatusParams) (Service, error) {
	row := q.db.QueryRow(ctx, setServiceStatus,
		arg.ID,
		arg.Status,
		arg.Status_2,
		arg.Steps,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Name,
		&i.Product,
		&i.Intent,
		&i.Status,
		&i.Shape,
		&i.Scaling,
		&i.Override,
		&i.ProvisioningSteps,
		&i.MonthlyEstimateCents,
		&i.EstimateID,
		&i.CellID,
		&i.CreatedAt,
		&i.Desired,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LastReconciledAt,
	)
	return i, err
}

const updateServiceShape = `-- name: UpdateServiceShape :one
UPDATE services SET
    shape = coalesce($2, shape),
    scaling = coalesce($3, scaling),
    override = $4,
    monthly_estimate_cents = coalesce($5, monthly_estimate_cents),
    desired = coalesce($6, desired),
    generation = generation + 1
WHERE id = $1
RETURNING id, env_id, name, product, intent, status, shape, scaling, override, provisioning_steps, monthly_estimate_cents, estimate_id, cell_id, created_at, desired, generation, observed_generation, last_reconciled_at
`

type UpdateServiceShapeParams struct {
	ID                   string
	Shape                []byte
	Scaling              []byte
	Override             []byte
	MonthlyEstimateCents pgtype.Int8
	Desired              []byte
}

// A desired-state edit (US-1.3a): rewrite desired and BUMP generation so the
// service becomes outstanding (observed_generation < generation) and the cell
// re-reconciles. Without the bump a converged service would never see the edit.
func (q *Queries) UpdateServiceShape(ctx context.Context, arg UpdateServiceShapeParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateServiceShape,
		arg.ID,
		arg.Shape,
		arg.Scaling,
		arg.Override,
		arg.MonthlyEstimateCents,
		arg.Desired,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Name,
		&i.Product,
		&i.Intent,
		&i.Status,
		&i.Shape,
		&i.Scaling,
		&i.Override,
		&i.ProvisioningSteps,
		&i.MonthlyEstimateCents,
		&i.EstimateID,
		&i.CellID,
		&i.CreatedAt,
		&i.Desired,
		&i.Generation,
		&i.ObservedGeneration,
		&i.LastReconciledAt,
	)
	return i, err
}
