// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpTemplateUsage = `-- name: BumpTemplateUsage :exec
UPDATE templates SET used_by_count = used_by_count + 1 WHERE id = $1
`

func (q *Queries) BumpTemplateUsage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpTemplateUsage, id)
	return err
}

const deleteBindingsForProject = `-- name: DeleteBindingsForProject :exec
DELETE FROM bindings b USING services s, environments e
WHERE b.source_id = s.id AND s.env_id = e.id AND e.project_id = $1
`

// Instantiation COMPENSATION only (T12.4): bindings RESTRICT service deletion,
// so a failed half-instantiation clears them before the project cascade.
func (q *Queries) DeleteBindingsForProject(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, deleteBindingsForProject, projectID)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE FROM templates WHERE id = $1 AND org_id = $2
`

type DeleteTemplateParams struct {
	ID    string
	OrgID string
}

// ADR-021: deleting the recipe doesn't touch the meals — nothing references
// templates, so this is a plain delete, never a cascade into instantiations.
func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const envByName = `-- name: EnvByName :one
SELECT id, project_id, name, region_override, kind, policy_flags, expires_at, created_at, implicit, deletion_scheduled_at, torn_down_at FROM environments WHERE project_id = $1 AND name = $2
`

type EnvByNameParams struct {
	ProjectID string
	Name      string
}

func (q *Queries) EnvByName(ctx context.Context, arg EnvByNameParams) (Environment, error) {
	row := q.db.QueryRow(ctx, envByName, arg.ProjectID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RegionOverride,
		&i.Kind,
		&i.PolicyFlags,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Implicit,
		&i.DeletionScheduledAt,
		&i.TornDownAt,
	)
	return i, err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, org_id, name, visibility, version, source_project, source_env, contents, required_inputs, monthly_estimate_cents, used_by_count, updated_by, created_at, updated_at FROM templates WHERE id = $1
`

func (q *Queries) GetTemplate(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Visibility,
		&i.Version,
		&i.SourceProject,
		&i.SourceEnv,
		&i.Contents,
		&i.RequiredInputs,
		&i.MonthlyEstimateCents,
		&i.UsedByCount,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteProject = `-- name: HardDeleteProject :exec
DELETE FROM projects WHERE id = $1
`

// Instantiation COMPENSATION only: cascade removes envs -> services -> secrets.
// Normal deletion is the scheduled soft path — never this.
func (q *Queries) HardDeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, hardDeleteProject, id)
	return err
}

const insertTemplate = `-- name: InsertTemplate :one

INSERT INTO templates (id, org_id, name, visibility, source_project, source_env, contents, required_inputs, monthly_estimate_cents, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, org_id, name, visibility, version, source_project, source_env, contents, required_inputs, monthly_estimate_cents, used_by_count, updated_by, created_at, updated_at
`

type InsertTemplateParams struct {
	ID                   string
	OrgID                string
	Name                 string
	Visibility           string
	SourceProject        string
	SourceEnv            string
	Contents             []byte
	RequiredInputs       []byte
	MonthlyEstimateCents int64
	UpdatedBy            string
}

// T12.4: templates (ADR-021 frozen copies).
func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, insertTemplate,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Visibility,
		arg.SourceProject,
		arg.SourceEnv,
		arg.Contents,
		arg.RequiredInputs,
		arg.MonthlyEstimateCents,
		arg.UpdatedBy,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Visibility,
		&i.Version,
		&i.SourceProject,
		&i.SourceEnv,
		&i.Contents,
		&i.RequiredInputs,
		&i.MonthlyEstimateCents,
		&i.UsedByCount,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBindingsForEnv = `-- name: ListBindingsForEnv :many
SELECT b.id, b.source_id, b.target_type, b.target_id, b.provider, b.provider_config, b.secret_ref, b.intent, b.scope, b.status, b.rotated_at, b.created_at FROM bindings b
JOIN services s ON s.id = b.source_id
WHERE s.env_id = $1 AND b.status <> 'revoked'
`

// capture input: every binding whose SOURCE service lives in the env.
func (q *Queries) ListBindingsForEnv(ctx context.Context, envID string) ([]Binding, error) {
	rows, err := q.db.Query(ctx, listBindingsForEnv, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Binding
	for rows.Next() {
		var i Binding
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetType,
			&i.TargetID,
			&i.Provider,
			&i.ProviderConfig,
			&i.SecretRef,
			&i.Intent,
			&i.Scope,
			&i.Status,
			&i.RotatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, org_id, name, visibility, version, source_project, source_env, contents, required_inputs, monthly_estimate_cents, used_by_count, updated_by, created_at, updated_at FROM templates WHERE org_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListTemplates(ctx context.Context, orgID string) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Visibility,
			&i.Version,
			&i.SourceProject,
			&i.SourceEnv,
			&i.Contents,
			&i.RequiredInputs,
			&i.MonthlyEstimateCents,
			&i.UsedByCount,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectByName = `-- name: ProjectByName :one
SELECT id, org_id, name, cell_id, deletion_scheduled_at, created_at FROM projects WHERE org_id = $1 AND name = $2 AND deletion_scheduled_at IS NULL
`

type ProjectByNameParams struct {
	OrgID string
	Name  string
}

func (q *Queries) ProjectByName(ctx context.Context, arg ProjectByNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, projectByName, arg.OrgID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CellID,
		&i.DeletionScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates SET
    name = coalesce($3, name),
    visibility = coalesce($4, visibility),
    contents = coalesce($5, contents),
    required_inputs = coalesce($6, required_inputs),
    monthly_estimate_cents = coalesce($7, monthly_estimate_cents),
    version = version + 1,
    updated_by = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, visibility, version, source_project, source_env, contents, required_inputs, monthly_estimate_cents, used_by_count, updated_by, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID                   string
	UpdatedBy            string
	Name                 pgtype.Text
	Visibility           pgtype.Text
	Contents             []byte
	RequiredInputs       []byte
	MonthlyEstimateCents pgtype.Int8
}

// version increments on every edit; contents NULL = keep (coalesce).
func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.UpdatedBy,
		arg.Name,
		arg.Visibility,
		arg.Contents,
		arg.RequiredInputs,
		arg.MonthlyEstimateCents,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Visibility,
		&i.Version,
		&i.SourceProject,
		&i.SourceEnv,
		&i.Contents,
		&i.RequiredInputs,
		&i.MonthlyEstimateCents,
		&i.UsedByCount,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
