#!/usr/bin/env node
// One-way projection: tasks/** → GitHub issues (A1: overwrite-always, idempotent, never syncs back).
// Issues are disposable views. Requires gh CLI auth. Usage: node sync.mjs [--only ID] [--dry-run]
import { execFileSync } from "node:child_process";
import { loadTasks } from "./lib.mjs";

const REPO = "steloit/cloud";
const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const only = args.includes("--only") ? args[args.indexOf("--only") + 1] : null;

const gh = (ghArgs, input) =>
  execFileSync("gh", ghArgs, { encoding: "utf8", input, maxBuffer: 10 * 1024 * 1024 });

const tasks = loadTasks(true);
const byId = new Map(tasks.map((t) => [t.meta.id, t]));
const relPath = (f) => f.replace(/^.*\/(tasks\/)/, "$1");

function desiredBody(t) {
  const m = t.meta;
  const path = relPath(t.file);
  const dep = (d) => {
    const dt = byId.get(d);
    return dt?.meta.issue ? `#${dt.meta.issue} (${d})` : `\`${d}\``;
  };
  const epicRef = m.epic && byId.get(m.epic)?.meta.issue ? `${m.epic} (#${byId.get(m.epic).meta.issue})` : m.epic;
  const metaLine = [
    `**Status:** ${m.status}`, `**Phase:** ${m.phase}`,
    m.sprint != null ? `**Sprint:** ${m.sprint}` : null,
    `**Priority:** ${m.priority}`, `**Epic:** ${epicRef}`,
    m.estimate ? `**Estimate:** ${m.estimate}` : null,
  ].filter(Boolean).join(" · ");
  const deps = (m.deps ?? []).length ? `\n**Depends on:** ${m.deps.map(dep).join(" · ")}` : "";
  return `📄 **Spec:** [\`${path}\`](https://github.com/${REPO}/blob/main/${path}) — the source of truth
${metaLine}${deps}

<details><summary>Full specification (generated from the repo — do not edit here)</summary>

${t.body.trim()}

</details>

<sub>Generated by spec-sync from \`${path}\`. Hand-edits to this issue are overwritten on next sync.</sub>`;
}

let updated = 0, unchanged = 0, closed = 0, skipped = 0;
for (const t of tasks) {
  const m = t.meta;
  if (only && m.id !== only) continue;
  if (!m.issue) { skipped++; continue; }
  const desired = { title: `${m.id} · ${m.title}`, body: desiredBody(t), state: m.status === "done" ? "closed" : "open" };
  const cur = JSON.parse(gh(["api", `repos/${REPO}/issues/${m.issue}`]));
  const same = cur.title === desired.title && (cur.body ?? "").trim() === desired.body.trim() && cur.state === desired.state;
  if (same) { unchanged++; continue; }
  if (dryRun) { console.log(`would update #${m.issue} (${m.id})`); updated++; continue; }
  gh(["api", "-X", "PATCH", `repos/${REPO}/issues/${m.issue}`, "-f", `title=${desired.title}`,
    "-f", `body=${desired.body}`, "-f", `state=${desired.state}`]);
  updated++;
  if (desired.state === "closed" && cur.state !== "closed") closed++;
  await new Promise((r) => setTimeout(r, 150));
}
console.log(`sync: ${updated} updated, ${unchanged} unchanged, ${closed} closed, ${skipped} no-issue`);
