/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingTeamRouteImport } from './routes/onboarding.team'
import { Route as OnboardingProjectRouteImport } from './routes/onboarding.project'
import { Route as OnboardingOrgRouteImport } from './routes/onboarding.org'
import { Route as OnboardingConnectRouteImport } from './routes/onboarding.connect'
import { Route as InviteInviteIdRouteImport } from './routes/invite.$inviteId'
import { Route as AppOrgRouteImport } from './routes/_app.$org'
import { Route as AppOrgIndexRouteImport } from './routes/_app.$org.index'
import { Route as AppOrgNewProjectRouteImport } from './routes/_app.$org.new-project'
import { Route as AppOrgProjectIndexRouteImport } from './routes/_app.$org.$project.index'
import { Route as AppOrgSettingsAuditRouteImport } from './routes/_app.$org.settings.audit'
import { Route as AppOrgProjectSvcServiceRouteImport } from './routes/_app.$org.$project.svc.$service'
import { Route as AppOrgProjectSvcServiceIndexRouteImport } from './routes/_app.$org.$project.svc.$service.index'
import { Route as AppOrgProjectSvcServiceInsightsRouteImport } from './routes/_app.$org.$project.svc.$service.insights'
import { Route as AppOrgProjectSvcServiceBranchesRouteImport } from './routes/_app.$org.$project.svc.$service.branches'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTeamRoute = OnboardingTeamRouteImport.update({
  id: '/onboarding/team',
  path: '/onboarding/team',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProjectRoute = OnboardingProjectRouteImport.update({
  id: '/onboarding/project',
  path: '/onboarding/project',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOrgRoute = OnboardingOrgRouteImport.update({
  id: '/onboarding/org',
  path: '/onboarding/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingConnectRoute = OnboardingConnectRouteImport.update({
  id: '/onboarding/connect',
  path: '/onboarding/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInviteIdRoute = InviteInviteIdRouteImport.update({
  id: '/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/$org',
  path: '/$org',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgIndexRoute = AppOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgNewProjectRoute = AppOrgNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgProjectIndexRoute = AppOrgProjectIndexRouteImport.update({
  id: '/$project/',
  path: '/$project/',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSettingsAuditRoute = AppOrgSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgProjectSvcServiceRoute = AppOrgProjectSvcServiceRouteImport.update({
  id: '/$project/svc/$service',
  path: '/$project/svc/$service',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgProjectSvcServiceIndexRoute =
  AppOrgProjectSvcServiceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceInsightsRoute =
  AppOrgProjectSvcServiceInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceBranchesRoute =
  AppOrgProjectSvcServiceBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/$org': typeof AppOrgRouteWithChildren
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/org': typeof OnboardingOrgRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/$org/new-project': typeof AppOrgNewProjectRoute
  '/$org/': typeof AppOrgIndexRoute
  '/$org/settings/audit': typeof AppOrgSettingsAuditRoute
  '/$org/$project/': typeof AppOrgProjectIndexRoute
  '/$org/$project/svc/$service': typeof AppOrgProjectSvcServiceRouteWithChildren
  '/$org/$project/svc/$service/branches': typeof AppOrgProjectSvcServiceBranchesRoute
  '/$org/$project/svc/$service/insights': typeof AppOrgProjectSvcServiceInsightsRoute
  '/$org/$project/svc/$service/': typeof AppOrgProjectSvcServiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/org': typeof OnboardingOrgRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/$org/new-project': typeof AppOrgNewProjectRoute
  '/$org': typeof AppOrgIndexRoute
  '/$org/settings/audit': typeof AppOrgSettingsAuditRoute
  '/$org/$project': typeof AppOrgProjectIndexRoute
  '/$org/$project/svc/$service/branches': typeof AppOrgProjectSvcServiceBranchesRoute
  '/$org/$project/svc/$service/insights': typeof AppOrgProjectSvcServiceInsightsRoute
  '/$org/$project/svc/$service': typeof AppOrgProjectSvcServiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/$org': typeof AppOrgRouteWithChildren
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/org': typeof OnboardingOrgRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/_app/$org/new-project': typeof AppOrgNewProjectRoute
  '/_app/$org/': typeof AppOrgIndexRoute
  '/_app/$org/settings/audit': typeof AppOrgSettingsAuditRoute
  '/_app/$org/$project/': typeof AppOrgProjectIndexRoute
  '/_app/$org/$project/svc/$service': typeof AppOrgProjectSvcServiceRouteWithChildren
  '/_app/$org/$project/svc/$service/branches': typeof AppOrgProjectSvcServiceBranchesRoute
  '/_app/$org/$project/svc/$service/insights': typeof AppOrgProjectSvcServiceInsightsRoute
  '/_app/$org/$project/svc/$service/': typeof AppOrgProjectSvcServiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/$org'
    | '/invite/$inviteId'
    | '/onboarding/connect'
    | '/onboarding/org'
    | '/onboarding/project'
    | '/onboarding/team'
    | '/$org/new-project'
    | '/$org/'
    | '/$org/settings/audit'
    | '/$org/$project/'
    | '/$org/$project/svc/$service'
    | '/$org/$project/svc/$service/branches'
    | '/$org/$project/svc/$service/insights'
    | '/$org/$project/svc/$service/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/invite/$inviteId'
    | '/onboarding/connect'
    | '/onboarding/org'
    | '/onboarding/project'
    | '/onboarding/team'
    | '/$org/new-project'
    | '/$org'
    | '/$org/settings/audit'
    | '/$org/$project'
    | '/$org/$project/svc/$service/branches'
    | '/$org/$project/svc/$service/insights'
    | '/$org/$project/svc/$service'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/$org'
    | '/invite/$inviteId'
    | '/onboarding/connect'
    | '/onboarding/org'
    | '/onboarding/project'
    | '/onboarding/team'
    | '/_app/$org/new-project'
    | '/_app/$org/'
    | '/_app/$org/settings/audit'
    | '/_app/$org/$project/'
    | '/_app/$org/$project/svc/$service'
    | '/_app/$org/$project/svc/$service/branches'
    | '/_app/$org/$project/svc/$service/insights'
    | '/_app/$org/$project/svc/$service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteInviteIdRoute: typeof InviteInviteIdRoute
  OnboardingConnectRoute: typeof OnboardingConnectRoute
  OnboardingOrgRoute: typeof OnboardingOrgRoute
  OnboardingProjectRoute: typeof OnboardingProjectRoute
  OnboardingTeamRoute: typeof OnboardingTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/team': {
      id: '/onboarding/team'
      path: '/onboarding/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof OnboardingTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/project': {
      id: '/onboarding/project'
      path: '/onboarding/project'
      fullPath: '/onboarding/project'
      preLoaderRoute: typeof OnboardingProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/org': {
      id: '/onboarding/org'
      path: '/onboarding/org'
      fullPath: '/onboarding/org'
      preLoaderRoute: typeof OnboardingOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/connect': {
      id: '/onboarding/connect'
      path: '/onboarding/connect'
      fullPath: '/onboarding/connect'
      preLoaderRoute: typeof OnboardingConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$inviteId': {
      id: '/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof InviteInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$org': {
      id: '/_app/$org'
      path: '/$org'
      fullPath: '/$org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$org/': {
      id: '/_app/$org/'
      path: '/'
      fullPath: '/$org/'
      preLoaderRoute: typeof AppOrgIndexRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/new-project': {
      id: '/_app/$org/new-project'
      path: '/new-project'
      fullPath: '/$org/new-project'
      preLoaderRoute: typeof AppOrgNewProjectRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/': {
      id: '/_app/$org/$project/'
      path: '/$project'
      fullPath: '/$org/$project/'
      preLoaderRoute: typeof AppOrgProjectIndexRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/settings/audit': {
      id: '/_app/$org/settings/audit'
      path: '/settings/audit'
      fullPath: '/$org/settings/audit'
      preLoaderRoute: typeof AppOrgSettingsAuditRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/svc/$service': {
      id: '/_app/$org/$project/svc/$service'
      path: '/$project/svc/$service'
      fullPath: '/$org/$project/svc/$service'
      preLoaderRoute: typeof AppOrgProjectSvcServiceRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/svc/$service/': {
      id: '/_app/$org/$project/svc/$service/'
      path: '/'
      fullPath: '/$org/$project/svc/$service/'
      preLoaderRoute: typeof AppOrgProjectSvcServiceIndexRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/insights': {
      id: '/_app/$org/$project/svc/$service/insights'
      path: '/insights'
      fullPath: '/$org/$project/svc/$service/insights'
      preLoaderRoute: typeof AppOrgProjectSvcServiceInsightsRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/branches': {
      id: '/_app/$org/$project/svc/$service/branches'
      path: '/branches'
      fullPath: '/$org/$project/svc/$service/branches'
      preLoaderRoute: typeof AppOrgProjectSvcServiceBranchesRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
  }
}

interface AppOrgProjectSvcServiceRouteChildren {
  AppOrgProjectSvcServiceBranchesRoute: typeof AppOrgProjectSvcServiceBranchesRoute
  AppOrgProjectSvcServiceInsightsRoute: typeof AppOrgProjectSvcServiceInsightsRoute
  AppOrgProjectSvcServiceIndexRoute: typeof AppOrgProjectSvcServiceIndexRoute
}

const AppOrgProjectSvcServiceRouteChildren: AppOrgProjectSvcServiceRouteChildren =
  {
    AppOrgProjectSvcServiceBranchesRoute: AppOrgProjectSvcServiceBranchesRoute,
    AppOrgProjectSvcServiceInsightsRoute: AppOrgProjectSvcServiceInsightsRoute,
    AppOrgProjectSvcServiceIndexRoute: AppOrgProjectSvcServiceIndexRoute,
  }

const AppOrgProjectSvcServiceRouteWithChildren =
  AppOrgProjectSvcServiceRoute._addFileChildren(
    AppOrgProjectSvcServiceRouteChildren,
  )

interface AppOrgRouteChildren {
  AppOrgNewProjectRoute: typeof AppOrgNewProjectRoute
  AppOrgIndexRoute: typeof AppOrgIndexRoute
  AppOrgSettingsAuditRoute: typeof AppOrgSettingsAuditRoute
  AppOrgProjectIndexRoute: typeof AppOrgProjectIndexRoute
  AppOrgProjectSvcServiceRoute: typeof AppOrgProjectSvcServiceRouteWithChildren
}

const AppOrgRouteChildren: AppOrgRouteChildren = {
  AppOrgNewProjectRoute: AppOrgNewProjectRoute,
  AppOrgIndexRoute: AppOrgIndexRoute,
  AppOrgSettingsAuditRoute: AppOrgSettingsAuditRoute,
  AppOrgProjectIndexRoute: AppOrgProjectIndexRoute,
  AppOrgProjectSvcServiceRoute: AppOrgProjectSvcServiceRouteWithChildren,
}

const AppOrgRouteWithChildren =
  AppOrgRoute._addFileChildren(AppOrgRouteChildren)

interface AppRouteChildren {
  AppOrgRoute: typeof AppOrgRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgRoute: AppOrgRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteInviteIdRoute: InviteInviteIdRoute,
  OnboardingConnectRoute: OnboardingConnectRoute,
  OnboardingOrgRoute: OnboardingOrgRoute,
  OnboardingProjectRoute: OnboardingProjectRoute,
  OnboardingTeamRoute: OnboardingTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
