/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingTeamRouteImport } from './routes/onboarding.team'
import { Route as OnboardingProjectRouteImport } from './routes/onboarding.project'
import { Route as OnboardingOrgRouteImport } from './routes/onboarding.org'
import { Route as OnboardingConnectRouteImport } from './routes/onboarding.connect'
import { Route as InviteInviteIdRouteImport } from './routes/invite.$inviteId'
import { Route as AppWelcomeRouteImport } from './routes/_app.welcome'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppOrgRouteImport } from './routes/_app.$org'
import { Route as AppOrgIndexRouteImport } from './routes/_app.$org.index'
import { Route as AppAccountTokensRouteImport } from './routes/_app.account.tokens'
import { Route as AppAccountSessionsRouteImport } from './routes/_app.account.sessions'
import { Route as AppAccountSecurityRouteImport } from './routes/_app.account.security'
import { Route as AppAccountProfileRouteImport } from './routes/_app.account.profile'
import { Route as AppAccountNotificationsRouteImport } from './routes/_app.account.notifications'
import { Route as AppOrgNotificationsRouteImport } from './routes/_app.$org.notifications'
import { Route as AppOrgNewProjectRouteImport } from './routes/_app.$org.new-project'
import { Route as AppOrgDashboardsRouteImport } from './routes/_app.$org.dashboards'
import { Route as AppOrgCreateRouteImport } from './routes/_app.$org.create'
import { Route as AppOrgAssistantRouteImport } from './routes/_app.$org.assistant'
import { Route as AppOrgDashboardsIndexRouteImport } from './routes/_app.$org.dashboards.index'
import { Route as AppOrgProjectIndexRouteImport } from './routes/_app.$org.$project.index'
import { Route as AppOrgTemplateTplRouteImport } from './routes/_app.$org.template.$tpl'
import { Route as AppOrgSettingsTemplatesRouteImport } from './routes/_app.$org.settings.templates'
import { Route as AppOrgSettingsMembersRouteImport } from './routes/_app.$org.settings.members'
import { Route as AppOrgSettingsGeneralRouteImport } from './routes/_app.$org.settings.general'
import { Route as AppOrgSettingsCellsRouteImport } from './routes/_app.$org.settings.cells'
import { Route as AppOrgSettingsAuditRouteImport } from './routes/_app.$org.settings.audit'
import { Route as AppOrgSettingsApiKeysRouteImport } from './routes/_app.$org.settings.api-keys'
import { Route as AppOrgNewProjectTemplatesRouteImport } from './routes/_app.$org.new-project_.templates'
import { Route as AppOrgDashboardsPostgresHealthRouteImport } from './routes/_app.$org.dashboards.postgres-health'
import { Route as AppOrgDashboardsMineRouteImport } from './routes/_app.$org.dashboards.mine'
import { Route as AppOrgDashboardsLayoutsRouteImport } from './routes/_app.$org.dashboards.layouts'
import { Route as AppOrgDashboardsInfrastructureRouteImport } from './routes/_app.$org.dashboards.infrastructure'
import { Route as AppOrgDashboardsCostUsageRouteImport } from './routes/_app.$org.dashboards.cost-usage'
import { Route as AppOrgDashboardsDashIdRouteImport } from './routes/_app.$org.dashboards.$dashId'
import { Route as AppOrgBillingUsageRouteImport } from './routes/_app.$org.billing.usage'
import { Route as AppOrgBillingQuotasRouteImport } from './routes/_app.$org.billing.quotas'
import { Route as AppOrgBillingPlansRouteImport } from './routes/_app.$org.billing.plans'
import { Route as AppOrgBillingPaymentRouteImport } from './routes/_app.$org.billing.payment'
import { Route as AppOrgBillingOverviewRouteImport } from './routes/_app.$org.billing.overview'
import { Route as AppOrgBillingInvoicesRouteImport } from './routes/_app.$org.billing.invoices'
import { Route as AppOrgAssistantInsightsRouteImport } from './routes/_app.$org.assistant.insights'
import { Route as AppOrgAssistantCapabilitiesRouteImport } from './routes/_app.$org.assistant.capabilities'
import { Route as AppOrgAssistantAskRouteImport } from './routes/_app.$org.assistant.ask'
import { Route as AppOrgAssistantActivityRouteImport } from './routes/_app.$org.assistant.activity'
import { Route as AppOrgProjectObserveRouteImport } from './routes/_app.$org.$project.observe'
import { Route as AppOrgProjectNewEnvRouteImport } from './routes/_app.$org.$project.new-env'
import { Route as AppOrgProjectEnvironmentsRouteImport } from './routes/_app.$org.$project.environments'
import { Route as AppOrgProjectDeployRouteImport } from './routes/_app.$org.$project.deploy'
import { Route as AppOrgSettingsPoliciesIndexRouteImport } from './routes/_app.$org.settings.policies.index'
import { Route as AppOrgProjectDeployIndexRouteImport } from './routes/_app.$org.$project.deploy.index'
import { Route as AppOrgSettingsPoliciesNewRouteImport } from './routes/_app.$org.settings.policies.new'
import { Route as AppOrgSettingsPoliciesAiAssistantRouteImport } from './routes/_app.$org.settings.policies.ai-assistant'
import { Route as AppOrgProjectSvcServiceRouteImport } from './routes/_app.$org.$project.svc.$service'
import { Route as AppOrgProjectSettingsPoliciesRouteImport } from './routes/_app.$org.$project.settings.policies'
import { Route as AppOrgProjectSettingsMembersRouteImport } from './routes/_app.$org.$project.settings.members'
import { Route as AppOrgProjectSettingsGitRouteImport } from './routes/_app.$org.$project.settings.git'
import { Route as AppOrgProjectSettingsGeneralRouteImport } from './routes/_app.$org.$project.settings.general'
import { Route as AppOrgProjectObserveTracesRouteImport } from './routes/_app.$org.$project.observe.traces'
import { Route as AppOrgProjectObserveMetricsRouteImport } from './routes/_app.$org.$project.observe.metrics'
import { Route as AppOrgProjectObserveLogsRouteImport } from './routes/_app.$org.$project.observe.logs'
import { Route as AppOrgProjectObserveHealthRouteImport } from './routes/_app.$org.$project.observe.health'
import { Route as AppOrgProjectObserveEventsRouteImport } from './routes/_app.$org.$project.observe.events'
import { Route as AppOrgProjectObserveAlertsRouteImport } from './routes/_app.$org.$project.observe.alerts'
import { Route as AppOrgProjectInstancesProductRouteImport } from './routes/_app.$org.$project.instances.$product'
import { Route as AppOrgProjectDeployPreviewsRouteImport } from './routes/_app.$org.$project.deploy.previews'
import { Route as AppOrgProjectDeployDepRouteImport } from './routes/_app.$org.$project.deploy.$dep'
import { Route as AppOrgProjectSvcServiceIndexRouteImport } from './routes/_app.$org.$project.svc.$service.index'
import { Route as AppOrgProjectSvcServiceTablesRouteImport } from './routes/_app.$org.$project.svc.$service.tables'
import { Route as AppOrgProjectSvcServiceSqlEditorRouteImport } from './routes/_app.$org.$project.svc.$service.sql-editor'
import { Route as AppOrgProjectSvcServiceShellRouteImport } from './routes/_app.$org.$project.svc.$service.shell'
import { Route as AppOrgProjectSvcServiceSettingsRouteImport } from './routes/_app.$org.$project.svc.$service.settings'
import { Route as AppOrgProjectSvcServiceSchedulesRouteImport } from './routes/_app.$org.$project.svc.$service.schedules'
import { Route as AppOrgProjectSvcServiceScalingRouteImport } from './routes/_app.$org.$project.svc.$service.scaling'
import { Route as AppOrgProjectSvcServiceObjectsRouteImport } from './routes/_app.$org.$project.svc.$service.objects'
import { Route as AppOrgProjectSvcServiceMetricsRouteImport } from './routes/_app.$org.$project.svc.$service.metrics'
import { Route as AppOrgProjectSvcServiceMessagesRouteImport } from './routes/_app.$org.$project.svc.$service.messages'
import { Route as AppOrgProjectSvcServiceLogsRouteImport } from './routes/_app.$org.$project.svc.$service.logs'
import { Route as AppOrgProjectSvcServiceLifecycleRouteImport } from './routes/_app.$org.$project.svc.$service.lifecycle'
import { Route as AppOrgProjectSvcServiceInsightsRouteImport } from './routes/_app.$org.$project.svc.$service.insights'
import { Route as AppOrgProjectSvcServiceDomainsRouteImport } from './routes/_app.$org.$project.svc.$service.domains'
import { Route as AppOrgProjectSvcServiceDeploymentsRouteImport } from './routes/_app.$org.$project.svc.$service.deployments'
import { Route as AppOrgProjectSvcServiceDataBrowserRouteImport } from './routes/_app.$org.$project.svc.$service.data-browser'
import { Route as AppOrgProjectSvcServiceCliRouteImport } from './routes/_app.$org.$project.svc.$service.cli'
import { Route as AppOrgProjectSvcServiceBranchesRouteImport } from './routes/_app.$org.$project.svc.$service.branches'
import { Route as AppOrgProjectSvcServiceBindingsRouteImport } from './routes/_app.$org.$project.svc.$service.bindings'
import { Route as AppOrgProjectSvcServiceBackupsRouteImport } from './routes/_app.$org.$project.svc.$service.backups'
import { Route as AppOrgProjectSvcServiceAiRouteImport } from './routes/_app.$org.$project.svc.$service.ai'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTeamRoute = OnboardingTeamRouteImport.update({
  id: '/onboarding/team',
  path: '/onboarding/team',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProjectRoute = OnboardingProjectRouteImport.update({
  id: '/onboarding/project',
  path: '/onboarding/project',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOrgRoute = OnboardingOrgRouteImport.update({
  id: '/onboarding/org',
  path: '/onboarding/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingConnectRoute = OnboardingConnectRouteImport.update({
  id: '/onboarding/connect',
  path: '/onboarding/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInviteIdRoute = InviteInviteIdRouteImport.update({
  id: '/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/$org',
  path: '/$org',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgIndexRoute = AppOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppAccountTokensRoute = AppAccountTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountSessionsRoute = AppAccountSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountSecurityRoute = AppAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountProfileRoute = AppAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountNotificationsRoute = AppAccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppOrgNotificationsRoute = AppOrgNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgNewProjectRoute = AppOrgNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgDashboardsRoute = AppOrgDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgCreateRoute = AppOrgCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgAssistantRoute = AppOrgAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgDashboardsIndexRoute = AppOrgDashboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgDashboardsRoute,
} as any)
const AppOrgProjectIndexRoute = AppOrgProjectIndexRouteImport.update({
  id: '/$project/',
  path: '/$project/',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgTemplateTplRoute = AppOrgTemplateTplRouteImport.update({
  id: '/template/$tpl',
  path: '/template/$tpl',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSettingsTemplatesRoute = AppOrgSettingsTemplatesRouteImport.update({
  id: '/settings/templates',
  path: '/settings/templates',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSettingsMembersRoute = AppOrgSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSettingsGeneralRoute = AppOrgSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSettingsCellsRoute = AppOrgSettingsCellsRouteImport.update({
  id: '/settings/cells',
  path: '/settings/cells',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSettingsAuditRoute = AppOrgSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSettingsApiKeysRoute = AppOrgSettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgNewProjectTemplatesRoute =
  AppOrgNewProjectTemplatesRouteImport.update({
    id: '/new-project_/templates',
    path: '/new-project/templates',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgDashboardsPostgresHealthRoute =
  AppOrgDashboardsPostgresHealthRouteImport.update({
    id: '/postgres-health',
    path: '/postgres-health',
    getParentRoute: () => AppOrgDashboardsRoute,
  } as any)
const AppOrgDashboardsMineRoute = AppOrgDashboardsMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => AppOrgDashboardsRoute,
} as any)
const AppOrgDashboardsLayoutsRoute = AppOrgDashboardsLayoutsRouteImport.update({
  id: '/layouts',
  path: '/layouts',
  getParentRoute: () => AppOrgDashboardsRoute,
} as any)
const AppOrgDashboardsInfrastructureRoute =
  AppOrgDashboardsInfrastructureRouteImport.update({
    id: '/infrastructure',
    path: '/infrastructure',
    getParentRoute: () => AppOrgDashboardsRoute,
  } as any)
const AppOrgDashboardsCostUsageRoute =
  AppOrgDashboardsCostUsageRouteImport.update({
    id: '/cost-usage',
    path: '/cost-usage',
    getParentRoute: () => AppOrgDashboardsRoute,
  } as any)
const AppOrgDashboardsDashIdRoute = AppOrgDashboardsDashIdRouteImport.update({
  id: '/$dashId',
  path: '/$dashId',
  getParentRoute: () => AppOrgDashboardsRoute,
} as any)
const AppOrgBillingUsageRoute = AppOrgBillingUsageRouteImport.update({
  id: '/billing/usage',
  path: '/billing/usage',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgBillingQuotasRoute = AppOrgBillingQuotasRouteImport.update({
  id: '/billing/quotas',
  path: '/billing/quotas',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgBillingPlansRoute = AppOrgBillingPlansRouteImport.update({
  id: '/billing/plans',
  path: '/billing/plans',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgBillingPaymentRoute = AppOrgBillingPaymentRouteImport.update({
  id: '/billing/payment',
  path: '/billing/payment',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgBillingOverviewRoute = AppOrgBillingOverviewRouteImport.update({
  id: '/billing/overview',
  path: '/billing/overview',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgBillingInvoicesRoute = AppOrgBillingInvoicesRouteImport.update({
  id: '/billing/invoices',
  path: '/billing/invoices',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgAssistantInsightsRoute = AppOrgAssistantInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppOrgAssistantRoute,
} as any)
const AppOrgAssistantCapabilitiesRoute =
  AppOrgAssistantCapabilitiesRouteImport.update({
    id: '/capabilities',
    path: '/capabilities',
    getParentRoute: () => AppOrgAssistantRoute,
  } as any)
const AppOrgAssistantAskRoute = AppOrgAssistantAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppOrgAssistantRoute,
} as any)
const AppOrgAssistantActivityRoute = AppOrgAssistantActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppOrgAssistantRoute,
} as any)
const AppOrgProjectObserveRoute = AppOrgProjectObserveRouteImport.update({
  id: '/$project/observe',
  path: '/$project/observe',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgProjectNewEnvRoute = AppOrgProjectNewEnvRouteImport.update({
  id: '/$project/new-env',
  path: '/$project/new-env',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgProjectEnvironmentsRoute =
  AppOrgProjectEnvironmentsRouteImport.update({
    id: '/$project/environments',
    path: '/$project/environments',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgProjectDeployRoute = AppOrgProjectDeployRouteImport.update({
  id: '/$project/deploy',
  path: '/$project/deploy',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSettingsPoliciesIndexRoute =
  AppOrgSettingsPoliciesIndexRouteImport.update({
    id: '/settings/policies/',
    path: '/settings/policies/',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgProjectDeployIndexRoute =
  AppOrgProjectDeployIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrgProjectDeployRoute,
  } as any)
const AppOrgSettingsPoliciesNewRoute =
  AppOrgSettingsPoliciesNewRouteImport.update({
    id: '/settings/policies/new',
    path: '/settings/policies/new',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgSettingsPoliciesAiAssistantRoute =
  AppOrgSettingsPoliciesAiAssistantRouteImport.update({
    id: '/settings/policies/ai-assistant',
    path: '/settings/policies/ai-assistant',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgProjectSvcServiceRoute = AppOrgProjectSvcServiceRouteImport.update({
  id: '/$project/svc/$service',
  path: '/$project/svc/$service',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgProjectSettingsPoliciesRoute =
  AppOrgProjectSettingsPoliciesRouteImport.update({
    id: '/$project/settings/policies',
    path: '/$project/settings/policies',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgProjectSettingsMembersRoute =
  AppOrgProjectSettingsMembersRouteImport.update({
    id: '/$project/settings/members',
    path: '/$project/settings/members',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgProjectSettingsGitRoute =
  AppOrgProjectSettingsGitRouteImport.update({
    id: '/$project/settings/git',
    path: '/$project/settings/git',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgProjectSettingsGeneralRoute =
  AppOrgProjectSettingsGeneralRouteImport.update({
    id: '/$project/settings/general',
    path: '/$project/settings/general',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgProjectObserveTracesRoute =
  AppOrgProjectObserveTracesRouteImport.update({
    id: '/traces',
    path: '/traces',
    getParentRoute: () => AppOrgProjectObserveRoute,
  } as any)
const AppOrgProjectObserveMetricsRoute =
  AppOrgProjectObserveMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AppOrgProjectObserveRoute,
  } as any)
const AppOrgProjectObserveLogsRoute =
  AppOrgProjectObserveLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppOrgProjectObserveRoute,
  } as any)
const AppOrgProjectObserveHealthRoute =
  AppOrgProjectObserveHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AppOrgProjectObserveRoute,
  } as any)
const AppOrgProjectObserveEventsRoute =
  AppOrgProjectObserveEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AppOrgProjectObserveRoute,
  } as any)
const AppOrgProjectObserveAlertsRoute =
  AppOrgProjectObserveAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AppOrgProjectObserveRoute,
  } as any)
const AppOrgProjectInstancesProductRoute =
  AppOrgProjectInstancesProductRouteImport.update({
    id: '/$project/instances/$product',
    path: '/$project/instances/$product',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgProjectDeployPreviewsRoute =
  AppOrgProjectDeployPreviewsRouteImport.update({
    id: '/previews',
    path: '/previews',
    getParentRoute: () => AppOrgProjectDeployRoute,
  } as any)
const AppOrgProjectDeployDepRoute = AppOrgProjectDeployDepRouteImport.update({
  id: '/$dep',
  path: '/$dep',
  getParentRoute: () => AppOrgProjectDeployRoute,
} as any)
const AppOrgProjectSvcServiceIndexRoute =
  AppOrgProjectSvcServiceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceTablesRoute =
  AppOrgProjectSvcServiceTablesRouteImport.update({
    id: '/tables',
    path: '/tables',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceSqlEditorRoute =
  AppOrgProjectSvcServiceSqlEditorRouteImport.update({
    id: '/sql-editor',
    path: '/sql-editor',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceShellRoute =
  AppOrgProjectSvcServiceShellRouteImport.update({
    id: '/shell',
    path: '/shell',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceSettingsRoute =
  AppOrgProjectSvcServiceSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceSchedulesRoute =
  AppOrgProjectSvcServiceSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceScalingRoute =
  AppOrgProjectSvcServiceScalingRouteImport.update({
    id: '/scaling',
    path: '/scaling',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceObjectsRoute =
  AppOrgProjectSvcServiceObjectsRouteImport.update({
    id: '/objects',
    path: '/objects',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceMetricsRoute =
  AppOrgProjectSvcServiceMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceMessagesRoute =
  AppOrgProjectSvcServiceMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceLogsRoute =
  AppOrgProjectSvcServiceLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceLifecycleRoute =
  AppOrgProjectSvcServiceLifecycleRouteImport.update({
    id: '/lifecycle',
    path: '/lifecycle',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceInsightsRoute =
  AppOrgProjectSvcServiceInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceDomainsRoute =
  AppOrgProjectSvcServiceDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceDeploymentsRoute =
  AppOrgProjectSvcServiceDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceDataBrowserRoute =
  AppOrgProjectSvcServiceDataBrowserRouteImport.update({
    id: '/data-browser',
    path: '/data-browser',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceCliRoute =
  AppOrgProjectSvcServiceCliRouteImport.update({
    id: '/cli',
    path: '/cli',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceBranchesRoute =
  AppOrgProjectSvcServiceBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceBindingsRoute =
  AppOrgProjectSvcServiceBindingsRouteImport.update({
    id: '/bindings',
    path: '/bindings',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceBackupsRoute =
  AppOrgProjectSvcServiceBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)
const AppOrgProjectSvcServiceAiRoute =
  AppOrgProjectSvcServiceAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => AppOrgProjectSvcServiceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/$org': typeof AppOrgRouteWithChildren
  '/account': typeof AppAccountRouteWithChildren
  '/welcome': typeof AppWelcomeRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/org': typeof OnboardingOrgRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/$org/assistant': typeof AppOrgAssistantRouteWithChildren
  '/$org/create': typeof AppOrgCreateRoute
  '/$org/dashboards': typeof AppOrgDashboardsRouteWithChildren
  '/$org/new-project': typeof AppOrgNewProjectRoute
  '/$org/notifications': typeof AppOrgNotificationsRoute
  '/account/notifications': typeof AppAccountNotificationsRoute
  '/account/profile': typeof AppAccountProfileRoute
  '/account/security': typeof AppAccountSecurityRoute
  '/account/sessions': typeof AppAccountSessionsRoute
  '/account/tokens': typeof AppAccountTokensRoute
  '/$org/': typeof AppOrgIndexRoute
  '/$org/$project/deploy': typeof AppOrgProjectDeployRouteWithChildren
  '/$org/$project/environments': typeof AppOrgProjectEnvironmentsRoute
  '/$org/$project/new-env': typeof AppOrgProjectNewEnvRoute
  '/$org/$project/observe': typeof AppOrgProjectObserveRouteWithChildren
  '/$org/assistant/activity': typeof AppOrgAssistantActivityRoute
  '/$org/assistant/ask': typeof AppOrgAssistantAskRoute
  '/$org/assistant/capabilities': typeof AppOrgAssistantCapabilitiesRoute
  '/$org/assistant/insights': typeof AppOrgAssistantInsightsRoute
  '/$org/billing/invoices': typeof AppOrgBillingInvoicesRoute
  '/$org/billing/overview': typeof AppOrgBillingOverviewRoute
  '/$org/billing/payment': typeof AppOrgBillingPaymentRoute
  '/$org/billing/plans': typeof AppOrgBillingPlansRoute
  '/$org/billing/quotas': typeof AppOrgBillingQuotasRoute
  '/$org/billing/usage': typeof AppOrgBillingUsageRoute
  '/$org/dashboards/$dashId': typeof AppOrgDashboardsDashIdRoute
  '/$org/dashboards/cost-usage': typeof AppOrgDashboardsCostUsageRoute
  '/$org/dashboards/infrastructure': typeof AppOrgDashboardsInfrastructureRoute
  '/$org/dashboards/layouts': typeof AppOrgDashboardsLayoutsRoute
  '/$org/dashboards/mine': typeof AppOrgDashboardsMineRoute
  '/$org/dashboards/postgres-health': typeof AppOrgDashboardsPostgresHealthRoute
  '/$org/new-project/templates': typeof AppOrgNewProjectTemplatesRoute
  '/$org/settings/api-keys': typeof AppOrgSettingsApiKeysRoute
  '/$org/settings/audit': typeof AppOrgSettingsAuditRoute
  '/$org/settings/cells': typeof AppOrgSettingsCellsRoute
  '/$org/settings/general': typeof AppOrgSettingsGeneralRoute
  '/$org/settings/members': typeof AppOrgSettingsMembersRoute
  '/$org/settings/templates': typeof AppOrgSettingsTemplatesRoute
  '/$org/template/$tpl': typeof AppOrgTemplateTplRoute
  '/$org/$project/': typeof AppOrgProjectIndexRoute
  '/$org/dashboards/': typeof AppOrgDashboardsIndexRoute
  '/$org/$project/deploy/$dep': typeof AppOrgProjectDeployDepRoute
  '/$org/$project/deploy/previews': typeof AppOrgProjectDeployPreviewsRoute
  '/$org/$project/instances/$product': typeof AppOrgProjectInstancesProductRoute
  '/$org/$project/observe/alerts': typeof AppOrgProjectObserveAlertsRoute
  '/$org/$project/observe/events': typeof AppOrgProjectObserveEventsRoute
  '/$org/$project/observe/health': typeof AppOrgProjectObserveHealthRoute
  '/$org/$project/observe/logs': typeof AppOrgProjectObserveLogsRoute
  '/$org/$project/observe/metrics': typeof AppOrgProjectObserveMetricsRoute
  '/$org/$project/observe/traces': typeof AppOrgProjectObserveTracesRoute
  '/$org/$project/settings/general': typeof AppOrgProjectSettingsGeneralRoute
  '/$org/$project/settings/git': typeof AppOrgProjectSettingsGitRoute
  '/$org/$project/settings/members': typeof AppOrgProjectSettingsMembersRoute
  '/$org/$project/settings/policies': typeof AppOrgProjectSettingsPoliciesRoute
  '/$org/$project/svc/$service': typeof AppOrgProjectSvcServiceRouteWithChildren
  '/$org/settings/policies/ai-assistant': typeof AppOrgSettingsPoliciesAiAssistantRoute
  '/$org/settings/policies/new': typeof AppOrgSettingsPoliciesNewRoute
  '/$org/$project/deploy/': typeof AppOrgProjectDeployIndexRoute
  '/$org/settings/policies/': typeof AppOrgSettingsPoliciesIndexRoute
  '/$org/$project/svc/$service/ai': typeof AppOrgProjectSvcServiceAiRoute
  '/$org/$project/svc/$service/backups': typeof AppOrgProjectSvcServiceBackupsRoute
  '/$org/$project/svc/$service/bindings': typeof AppOrgProjectSvcServiceBindingsRoute
  '/$org/$project/svc/$service/branches': typeof AppOrgProjectSvcServiceBranchesRoute
  '/$org/$project/svc/$service/cli': typeof AppOrgProjectSvcServiceCliRoute
  '/$org/$project/svc/$service/data-browser': typeof AppOrgProjectSvcServiceDataBrowserRoute
  '/$org/$project/svc/$service/deployments': typeof AppOrgProjectSvcServiceDeploymentsRoute
  '/$org/$project/svc/$service/domains': typeof AppOrgProjectSvcServiceDomainsRoute
  '/$org/$project/svc/$service/insights': typeof AppOrgProjectSvcServiceInsightsRoute
  '/$org/$project/svc/$service/lifecycle': typeof AppOrgProjectSvcServiceLifecycleRoute
  '/$org/$project/svc/$service/logs': typeof AppOrgProjectSvcServiceLogsRoute
  '/$org/$project/svc/$service/messages': typeof AppOrgProjectSvcServiceMessagesRoute
  '/$org/$project/svc/$service/metrics': typeof AppOrgProjectSvcServiceMetricsRoute
  '/$org/$project/svc/$service/objects': typeof AppOrgProjectSvcServiceObjectsRoute
  '/$org/$project/svc/$service/scaling': typeof AppOrgProjectSvcServiceScalingRoute
  '/$org/$project/svc/$service/schedules': typeof AppOrgProjectSvcServiceSchedulesRoute
  '/$org/$project/svc/$service/settings': typeof AppOrgProjectSvcServiceSettingsRoute
  '/$org/$project/svc/$service/shell': typeof AppOrgProjectSvcServiceShellRoute
  '/$org/$project/svc/$service/sql-editor': typeof AppOrgProjectSvcServiceSqlEditorRoute
  '/$org/$project/svc/$service/tables': typeof AppOrgProjectSvcServiceTablesRoute
  '/$org/$project/svc/$service/': typeof AppOrgProjectSvcServiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AppAccountRouteWithChildren
  '/welcome': typeof AppWelcomeRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/org': typeof OnboardingOrgRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/$org/assistant': typeof AppOrgAssistantRouteWithChildren
  '/$org/create': typeof AppOrgCreateRoute
  '/$org/new-project': typeof AppOrgNewProjectRoute
  '/$org/notifications': typeof AppOrgNotificationsRoute
  '/account/notifications': typeof AppAccountNotificationsRoute
  '/account/profile': typeof AppAccountProfileRoute
  '/account/security': typeof AppAccountSecurityRoute
  '/account/sessions': typeof AppAccountSessionsRoute
  '/account/tokens': typeof AppAccountTokensRoute
  '/$org': typeof AppOrgIndexRoute
  '/$org/$project/environments': typeof AppOrgProjectEnvironmentsRoute
  '/$org/$project/new-env': typeof AppOrgProjectNewEnvRoute
  '/$org/$project/observe': typeof AppOrgProjectObserveRouteWithChildren
  '/$org/assistant/activity': typeof AppOrgAssistantActivityRoute
  '/$org/assistant/ask': typeof AppOrgAssistantAskRoute
  '/$org/assistant/capabilities': typeof AppOrgAssistantCapabilitiesRoute
  '/$org/assistant/insights': typeof AppOrgAssistantInsightsRoute
  '/$org/billing/invoices': typeof AppOrgBillingInvoicesRoute
  '/$org/billing/overview': typeof AppOrgBillingOverviewRoute
  '/$org/billing/payment': typeof AppOrgBillingPaymentRoute
  '/$org/billing/plans': typeof AppOrgBillingPlansRoute
  '/$org/billing/quotas': typeof AppOrgBillingQuotasRoute
  '/$org/billing/usage': typeof AppOrgBillingUsageRoute
  '/$org/dashboards/$dashId': typeof AppOrgDashboardsDashIdRoute
  '/$org/dashboards/cost-usage': typeof AppOrgDashboardsCostUsageRoute
  '/$org/dashboards/infrastructure': typeof AppOrgDashboardsInfrastructureRoute
  '/$org/dashboards/layouts': typeof AppOrgDashboardsLayoutsRoute
  '/$org/dashboards/mine': typeof AppOrgDashboardsMineRoute
  '/$org/dashboards/postgres-health': typeof AppOrgDashboardsPostgresHealthRoute
  '/$org/new-project/templates': typeof AppOrgNewProjectTemplatesRoute
  '/$org/settings/api-keys': typeof AppOrgSettingsApiKeysRoute
  '/$org/settings/audit': typeof AppOrgSettingsAuditRoute
  '/$org/settings/cells': typeof AppOrgSettingsCellsRoute
  '/$org/settings/general': typeof AppOrgSettingsGeneralRoute
  '/$org/settings/members': typeof AppOrgSettingsMembersRoute
  '/$org/settings/templates': typeof AppOrgSettingsTemplatesRoute
  '/$org/template/$tpl': typeof AppOrgTemplateTplRoute
  '/$org/$project': typeof AppOrgProjectIndexRoute
  '/$org/dashboards': typeof AppOrgDashboardsIndexRoute
  '/$org/$project/deploy/$dep': typeof AppOrgProjectDeployDepRoute
  '/$org/$project/deploy/previews': typeof AppOrgProjectDeployPreviewsRoute
  '/$org/$project/instances/$product': typeof AppOrgProjectInstancesProductRoute
  '/$org/$project/observe/alerts': typeof AppOrgProjectObserveAlertsRoute
  '/$org/$project/observe/events': typeof AppOrgProjectObserveEventsRoute
  '/$org/$project/observe/health': typeof AppOrgProjectObserveHealthRoute
  '/$org/$project/observe/logs': typeof AppOrgProjectObserveLogsRoute
  '/$org/$project/observe/metrics': typeof AppOrgProjectObserveMetricsRoute
  '/$org/$project/observe/traces': typeof AppOrgProjectObserveTracesRoute
  '/$org/$project/settings/general': typeof AppOrgProjectSettingsGeneralRoute
  '/$org/$project/settings/git': typeof AppOrgProjectSettingsGitRoute
  '/$org/$project/settings/members': typeof AppOrgProjectSettingsMembersRoute
  '/$org/$project/settings/policies': typeof AppOrgProjectSettingsPoliciesRoute
  '/$org/settings/policies/ai-assistant': typeof AppOrgSettingsPoliciesAiAssistantRoute
  '/$org/settings/policies/new': typeof AppOrgSettingsPoliciesNewRoute
  '/$org/$project/deploy': typeof AppOrgProjectDeployIndexRoute
  '/$org/settings/policies': typeof AppOrgSettingsPoliciesIndexRoute
  '/$org/$project/svc/$service/ai': typeof AppOrgProjectSvcServiceAiRoute
  '/$org/$project/svc/$service/backups': typeof AppOrgProjectSvcServiceBackupsRoute
  '/$org/$project/svc/$service/bindings': typeof AppOrgProjectSvcServiceBindingsRoute
  '/$org/$project/svc/$service/branches': typeof AppOrgProjectSvcServiceBranchesRoute
  '/$org/$project/svc/$service/cli': typeof AppOrgProjectSvcServiceCliRoute
  '/$org/$project/svc/$service/data-browser': typeof AppOrgProjectSvcServiceDataBrowserRoute
  '/$org/$project/svc/$service/deployments': typeof AppOrgProjectSvcServiceDeploymentsRoute
  '/$org/$project/svc/$service/domains': typeof AppOrgProjectSvcServiceDomainsRoute
  '/$org/$project/svc/$service/insights': typeof AppOrgProjectSvcServiceInsightsRoute
  '/$org/$project/svc/$service/lifecycle': typeof AppOrgProjectSvcServiceLifecycleRoute
  '/$org/$project/svc/$service/logs': typeof AppOrgProjectSvcServiceLogsRoute
  '/$org/$project/svc/$service/messages': typeof AppOrgProjectSvcServiceMessagesRoute
  '/$org/$project/svc/$service/metrics': typeof AppOrgProjectSvcServiceMetricsRoute
  '/$org/$project/svc/$service/objects': typeof AppOrgProjectSvcServiceObjectsRoute
  '/$org/$project/svc/$service/scaling': typeof AppOrgProjectSvcServiceScalingRoute
  '/$org/$project/svc/$service/schedules': typeof AppOrgProjectSvcServiceSchedulesRoute
  '/$org/$project/svc/$service/settings': typeof AppOrgProjectSvcServiceSettingsRoute
  '/$org/$project/svc/$service/shell': typeof AppOrgProjectSvcServiceShellRoute
  '/$org/$project/svc/$service/sql-editor': typeof AppOrgProjectSvcServiceSqlEditorRoute
  '/$org/$project/svc/$service/tables': typeof AppOrgProjectSvcServiceTablesRoute
  '/$org/$project/svc/$service': typeof AppOrgProjectSvcServiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/$org': typeof AppOrgRouteWithChildren
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/welcome': typeof AppWelcomeRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/org': typeof OnboardingOrgRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/_app/$org/assistant': typeof AppOrgAssistantRouteWithChildren
  '/_app/$org/create': typeof AppOrgCreateRoute
  '/_app/$org/dashboards': typeof AppOrgDashboardsRouteWithChildren
  '/_app/$org/new-project': typeof AppOrgNewProjectRoute
  '/_app/$org/notifications': typeof AppOrgNotificationsRoute
  '/_app/account/notifications': typeof AppAccountNotificationsRoute
  '/_app/account/profile': typeof AppAccountProfileRoute
  '/_app/account/security': typeof AppAccountSecurityRoute
  '/_app/account/sessions': typeof AppAccountSessionsRoute
  '/_app/account/tokens': typeof AppAccountTokensRoute
  '/_app/$org/': typeof AppOrgIndexRoute
  '/_app/$org/$project/deploy': typeof AppOrgProjectDeployRouteWithChildren
  '/_app/$org/$project/environments': typeof AppOrgProjectEnvironmentsRoute
  '/_app/$org/$project/new-env': typeof AppOrgProjectNewEnvRoute
  '/_app/$org/$project/observe': typeof AppOrgProjectObserveRouteWithChildren
  '/_app/$org/assistant/activity': typeof AppOrgAssistantActivityRoute
  '/_app/$org/assistant/ask': typeof AppOrgAssistantAskRoute
  '/_app/$org/assistant/capabilities': typeof AppOrgAssistantCapabilitiesRoute
  '/_app/$org/assistant/insights': typeof AppOrgAssistantInsightsRoute
  '/_app/$org/billing/invoices': typeof AppOrgBillingInvoicesRoute
  '/_app/$org/billing/overview': typeof AppOrgBillingOverviewRoute
  '/_app/$org/billing/payment': typeof AppOrgBillingPaymentRoute
  '/_app/$org/billing/plans': typeof AppOrgBillingPlansRoute
  '/_app/$org/billing/quotas': typeof AppOrgBillingQuotasRoute
  '/_app/$org/billing/usage': typeof AppOrgBillingUsageRoute
  '/_app/$org/dashboards/$dashId': typeof AppOrgDashboardsDashIdRoute
  '/_app/$org/dashboards/cost-usage': typeof AppOrgDashboardsCostUsageRoute
  '/_app/$org/dashboards/infrastructure': typeof AppOrgDashboardsInfrastructureRoute
  '/_app/$org/dashboards/layouts': typeof AppOrgDashboardsLayoutsRoute
  '/_app/$org/dashboards/mine': typeof AppOrgDashboardsMineRoute
  '/_app/$org/dashboards/postgres-health': typeof AppOrgDashboardsPostgresHealthRoute
  '/_app/$org/new-project_/templates': typeof AppOrgNewProjectTemplatesRoute
  '/_app/$org/settings/api-keys': typeof AppOrgSettingsApiKeysRoute
  '/_app/$org/settings/audit': typeof AppOrgSettingsAuditRoute
  '/_app/$org/settings/cells': typeof AppOrgSettingsCellsRoute
  '/_app/$org/settings/general': typeof AppOrgSettingsGeneralRoute
  '/_app/$org/settings/members': typeof AppOrgSettingsMembersRoute
  '/_app/$org/settings/templates': typeof AppOrgSettingsTemplatesRoute
  '/_app/$org/template/$tpl': typeof AppOrgTemplateTplRoute
  '/_app/$org/$project/': typeof AppOrgProjectIndexRoute
  '/_app/$org/dashboards/': typeof AppOrgDashboardsIndexRoute
  '/_app/$org/$project/deploy/$dep': typeof AppOrgProjectDeployDepRoute
  '/_app/$org/$project/deploy/previews': typeof AppOrgProjectDeployPreviewsRoute
  '/_app/$org/$project/instances/$product': typeof AppOrgProjectInstancesProductRoute
  '/_app/$org/$project/observe/alerts': typeof AppOrgProjectObserveAlertsRoute
  '/_app/$org/$project/observe/events': typeof AppOrgProjectObserveEventsRoute
  '/_app/$org/$project/observe/health': typeof AppOrgProjectObserveHealthRoute
  '/_app/$org/$project/observe/logs': typeof AppOrgProjectObserveLogsRoute
  '/_app/$org/$project/observe/metrics': typeof AppOrgProjectObserveMetricsRoute
  '/_app/$org/$project/observe/traces': typeof AppOrgProjectObserveTracesRoute
  '/_app/$org/$project/settings/general': typeof AppOrgProjectSettingsGeneralRoute
  '/_app/$org/$project/settings/git': typeof AppOrgProjectSettingsGitRoute
  '/_app/$org/$project/settings/members': typeof AppOrgProjectSettingsMembersRoute
  '/_app/$org/$project/settings/policies': typeof AppOrgProjectSettingsPoliciesRoute
  '/_app/$org/$project/svc/$service': typeof AppOrgProjectSvcServiceRouteWithChildren
  '/_app/$org/settings/policies/ai-assistant': typeof AppOrgSettingsPoliciesAiAssistantRoute
  '/_app/$org/settings/policies/new': typeof AppOrgSettingsPoliciesNewRoute
  '/_app/$org/$project/deploy/': typeof AppOrgProjectDeployIndexRoute
  '/_app/$org/settings/policies/': typeof AppOrgSettingsPoliciesIndexRoute
  '/_app/$org/$project/svc/$service/ai': typeof AppOrgProjectSvcServiceAiRoute
  '/_app/$org/$project/svc/$service/backups': typeof AppOrgProjectSvcServiceBackupsRoute
  '/_app/$org/$project/svc/$service/bindings': typeof AppOrgProjectSvcServiceBindingsRoute
  '/_app/$org/$project/svc/$service/branches': typeof AppOrgProjectSvcServiceBranchesRoute
  '/_app/$org/$project/svc/$service/cli': typeof AppOrgProjectSvcServiceCliRoute
  '/_app/$org/$project/svc/$service/data-browser': typeof AppOrgProjectSvcServiceDataBrowserRoute
  '/_app/$org/$project/svc/$service/deployments': typeof AppOrgProjectSvcServiceDeploymentsRoute
  '/_app/$org/$project/svc/$service/domains': typeof AppOrgProjectSvcServiceDomainsRoute
  '/_app/$org/$project/svc/$service/insights': typeof AppOrgProjectSvcServiceInsightsRoute
  '/_app/$org/$project/svc/$service/lifecycle': typeof AppOrgProjectSvcServiceLifecycleRoute
  '/_app/$org/$project/svc/$service/logs': typeof AppOrgProjectSvcServiceLogsRoute
  '/_app/$org/$project/svc/$service/messages': typeof AppOrgProjectSvcServiceMessagesRoute
  '/_app/$org/$project/svc/$service/metrics': typeof AppOrgProjectSvcServiceMetricsRoute
  '/_app/$org/$project/svc/$service/objects': typeof AppOrgProjectSvcServiceObjectsRoute
  '/_app/$org/$project/svc/$service/scaling': typeof AppOrgProjectSvcServiceScalingRoute
  '/_app/$org/$project/svc/$service/schedules': typeof AppOrgProjectSvcServiceSchedulesRoute
  '/_app/$org/$project/svc/$service/settings': typeof AppOrgProjectSvcServiceSettingsRoute
  '/_app/$org/$project/svc/$service/shell': typeof AppOrgProjectSvcServiceShellRoute
  '/_app/$org/$project/svc/$service/sql-editor': typeof AppOrgProjectSvcServiceSqlEditorRoute
  '/_app/$org/$project/svc/$service/tables': typeof AppOrgProjectSvcServiceTablesRoute
  '/_app/$org/$project/svc/$service/': typeof AppOrgProjectSvcServiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/$org'
    | '/account'
    | '/welcome'
    | '/invite/$inviteId'
    | '/onboarding/connect'
    | '/onboarding/org'
    | '/onboarding/project'
    | '/onboarding/team'
    | '/$org/assistant'
    | '/$org/create'
    | '/$org/dashboards'
    | '/$org/new-project'
    | '/$org/notifications'
    | '/account/notifications'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/account/tokens'
    | '/$org/'
    | '/$org/$project/deploy'
    | '/$org/$project/environments'
    | '/$org/$project/new-env'
    | '/$org/$project/observe'
    | '/$org/assistant/activity'
    | '/$org/assistant/ask'
    | '/$org/assistant/capabilities'
    | '/$org/assistant/insights'
    | '/$org/billing/invoices'
    | '/$org/billing/overview'
    | '/$org/billing/payment'
    | '/$org/billing/plans'
    | '/$org/billing/quotas'
    | '/$org/billing/usage'
    | '/$org/dashboards/$dashId'
    | '/$org/dashboards/cost-usage'
    | '/$org/dashboards/infrastructure'
    | '/$org/dashboards/layouts'
    | '/$org/dashboards/mine'
    | '/$org/dashboards/postgres-health'
    | '/$org/new-project/templates'
    | '/$org/settings/api-keys'
    | '/$org/settings/audit'
    | '/$org/settings/cells'
    | '/$org/settings/general'
    | '/$org/settings/members'
    | '/$org/settings/templates'
    | '/$org/template/$tpl'
    | '/$org/$project/'
    | '/$org/dashboards/'
    | '/$org/$project/deploy/$dep'
    | '/$org/$project/deploy/previews'
    | '/$org/$project/instances/$product'
    | '/$org/$project/observe/alerts'
    | '/$org/$project/observe/events'
    | '/$org/$project/observe/health'
    | '/$org/$project/observe/logs'
    | '/$org/$project/observe/metrics'
    | '/$org/$project/observe/traces'
    | '/$org/$project/settings/general'
    | '/$org/$project/settings/git'
    | '/$org/$project/settings/members'
    | '/$org/$project/settings/policies'
    | '/$org/$project/svc/$service'
    | '/$org/settings/policies/ai-assistant'
    | '/$org/settings/policies/new'
    | '/$org/$project/deploy/'
    | '/$org/settings/policies/'
    | '/$org/$project/svc/$service/ai'
    | '/$org/$project/svc/$service/backups'
    | '/$org/$project/svc/$service/bindings'
    | '/$org/$project/svc/$service/branches'
    | '/$org/$project/svc/$service/cli'
    | '/$org/$project/svc/$service/data-browser'
    | '/$org/$project/svc/$service/deployments'
    | '/$org/$project/svc/$service/domains'
    | '/$org/$project/svc/$service/insights'
    | '/$org/$project/svc/$service/lifecycle'
    | '/$org/$project/svc/$service/logs'
    | '/$org/$project/svc/$service/messages'
    | '/$org/$project/svc/$service/metrics'
    | '/$org/$project/svc/$service/objects'
    | '/$org/$project/svc/$service/scaling'
    | '/$org/$project/svc/$service/schedules'
    | '/$org/$project/svc/$service/settings'
    | '/$org/$project/svc/$service/shell'
    | '/$org/$project/svc/$service/sql-editor'
    | '/$org/$project/svc/$service/tables'
    | '/$org/$project/svc/$service/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/welcome'
    | '/invite/$inviteId'
    | '/onboarding/connect'
    | '/onboarding/org'
    | '/onboarding/project'
    | '/onboarding/team'
    | '/$org/assistant'
    | '/$org/create'
    | '/$org/new-project'
    | '/$org/notifications'
    | '/account/notifications'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/account/tokens'
    | '/$org'
    | '/$org/$project/environments'
    | '/$org/$project/new-env'
    | '/$org/$project/observe'
    | '/$org/assistant/activity'
    | '/$org/assistant/ask'
    | '/$org/assistant/capabilities'
    | '/$org/assistant/insights'
    | '/$org/billing/invoices'
    | '/$org/billing/overview'
    | '/$org/billing/payment'
    | '/$org/billing/plans'
    | '/$org/billing/quotas'
    | '/$org/billing/usage'
    | '/$org/dashboards/$dashId'
    | '/$org/dashboards/cost-usage'
    | '/$org/dashboards/infrastructure'
    | '/$org/dashboards/layouts'
    | '/$org/dashboards/mine'
    | '/$org/dashboards/postgres-health'
    | '/$org/new-project/templates'
    | '/$org/settings/api-keys'
    | '/$org/settings/audit'
    | '/$org/settings/cells'
    | '/$org/settings/general'
    | '/$org/settings/members'
    | '/$org/settings/templates'
    | '/$org/template/$tpl'
    | '/$org/$project'
    | '/$org/dashboards'
    | '/$org/$project/deploy/$dep'
    | '/$org/$project/deploy/previews'
    | '/$org/$project/instances/$product'
    | '/$org/$project/observe/alerts'
    | '/$org/$project/observe/events'
    | '/$org/$project/observe/health'
    | '/$org/$project/observe/logs'
    | '/$org/$project/observe/metrics'
    | '/$org/$project/observe/traces'
    | '/$org/$project/settings/general'
    | '/$org/$project/settings/git'
    | '/$org/$project/settings/members'
    | '/$org/$project/settings/policies'
    | '/$org/settings/policies/ai-assistant'
    | '/$org/settings/policies/new'
    | '/$org/$project/deploy'
    | '/$org/settings/policies'
    | '/$org/$project/svc/$service/ai'
    | '/$org/$project/svc/$service/backups'
    | '/$org/$project/svc/$service/bindings'
    | '/$org/$project/svc/$service/branches'
    | '/$org/$project/svc/$service/cli'
    | '/$org/$project/svc/$service/data-browser'
    | '/$org/$project/svc/$service/deployments'
    | '/$org/$project/svc/$service/domains'
    | '/$org/$project/svc/$service/insights'
    | '/$org/$project/svc/$service/lifecycle'
    | '/$org/$project/svc/$service/logs'
    | '/$org/$project/svc/$service/messages'
    | '/$org/$project/svc/$service/metrics'
    | '/$org/$project/svc/$service/objects'
    | '/$org/$project/svc/$service/scaling'
    | '/$org/$project/svc/$service/schedules'
    | '/$org/$project/svc/$service/settings'
    | '/$org/$project/svc/$service/shell'
    | '/$org/$project/svc/$service/sql-editor'
    | '/$org/$project/svc/$service/tables'
    | '/$org/$project/svc/$service'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/$org'
    | '/_app/account'
    | '/_app/welcome'
    | '/invite/$inviteId'
    | '/onboarding/connect'
    | '/onboarding/org'
    | '/onboarding/project'
    | '/onboarding/team'
    | '/_app/$org/assistant'
    | '/_app/$org/create'
    | '/_app/$org/dashboards'
    | '/_app/$org/new-project'
    | '/_app/$org/notifications'
    | '/_app/account/notifications'
    | '/_app/account/profile'
    | '/_app/account/security'
    | '/_app/account/sessions'
    | '/_app/account/tokens'
    | '/_app/$org/'
    | '/_app/$org/$project/deploy'
    | '/_app/$org/$project/environments'
    | '/_app/$org/$project/new-env'
    | '/_app/$org/$project/observe'
    | '/_app/$org/assistant/activity'
    | '/_app/$org/assistant/ask'
    | '/_app/$org/assistant/capabilities'
    | '/_app/$org/assistant/insights'
    | '/_app/$org/billing/invoices'
    | '/_app/$org/billing/overview'
    | '/_app/$org/billing/payment'
    | '/_app/$org/billing/plans'
    | '/_app/$org/billing/quotas'
    | '/_app/$org/billing/usage'
    | '/_app/$org/dashboards/$dashId'
    | '/_app/$org/dashboards/cost-usage'
    | '/_app/$org/dashboards/infrastructure'
    | '/_app/$org/dashboards/layouts'
    | '/_app/$org/dashboards/mine'
    | '/_app/$org/dashboards/postgres-health'
    | '/_app/$org/new-project_/templates'
    | '/_app/$org/settings/api-keys'
    | '/_app/$org/settings/audit'
    | '/_app/$org/settings/cells'
    | '/_app/$org/settings/general'
    | '/_app/$org/settings/members'
    | '/_app/$org/settings/templates'
    | '/_app/$org/template/$tpl'
    | '/_app/$org/$project/'
    | '/_app/$org/dashboards/'
    | '/_app/$org/$project/deploy/$dep'
    | '/_app/$org/$project/deploy/previews'
    | '/_app/$org/$project/instances/$product'
    | '/_app/$org/$project/observe/alerts'
    | '/_app/$org/$project/observe/events'
    | '/_app/$org/$project/observe/health'
    | '/_app/$org/$project/observe/logs'
    | '/_app/$org/$project/observe/metrics'
    | '/_app/$org/$project/observe/traces'
    | '/_app/$org/$project/settings/general'
    | '/_app/$org/$project/settings/git'
    | '/_app/$org/$project/settings/members'
    | '/_app/$org/$project/settings/policies'
    | '/_app/$org/$project/svc/$service'
    | '/_app/$org/settings/policies/ai-assistant'
    | '/_app/$org/settings/policies/new'
    | '/_app/$org/$project/deploy/'
    | '/_app/$org/settings/policies/'
    | '/_app/$org/$project/svc/$service/ai'
    | '/_app/$org/$project/svc/$service/backups'
    | '/_app/$org/$project/svc/$service/bindings'
    | '/_app/$org/$project/svc/$service/branches'
    | '/_app/$org/$project/svc/$service/cli'
    | '/_app/$org/$project/svc/$service/data-browser'
    | '/_app/$org/$project/svc/$service/deployments'
    | '/_app/$org/$project/svc/$service/domains'
    | '/_app/$org/$project/svc/$service/insights'
    | '/_app/$org/$project/svc/$service/lifecycle'
    | '/_app/$org/$project/svc/$service/logs'
    | '/_app/$org/$project/svc/$service/messages'
    | '/_app/$org/$project/svc/$service/metrics'
    | '/_app/$org/$project/svc/$service/objects'
    | '/_app/$org/$project/svc/$service/scaling'
    | '/_app/$org/$project/svc/$service/schedules'
    | '/_app/$org/$project/svc/$service/settings'
    | '/_app/$org/$project/svc/$service/shell'
    | '/_app/$org/$project/svc/$service/sql-editor'
    | '/_app/$org/$project/svc/$service/tables'
    | '/_app/$org/$project/svc/$service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteInviteIdRoute: typeof InviteInviteIdRoute
  OnboardingConnectRoute: typeof OnboardingConnectRoute
  OnboardingOrgRoute: typeof OnboardingOrgRoute
  OnboardingProjectRoute: typeof OnboardingProjectRoute
  OnboardingTeamRoute: typeof OnboardingTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/team': {
      id: '/onboarding/team'
      path: '/onboarding/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof OnboardingTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/project': {
      id: '/onboarding/project'
      path: '/onboarding/project'
      fullPath: '/onboarding/project'
      preLoaderRoute: typeof OnboardingProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/org': {
      id: '/onboarding/org'
      path: '/onboarding/org'
      fullPath: '/onboarding/org'
      preLoaderRoute: typeof OnboardingOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/connect': {
      id: '/onboarding/connect'
      path: '/onboarding/connect'
      fullPath: '/onboarding/connect'
      preLoaderRoute: typeof OnboardingConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$inviteId': {
      id: '/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof InviteInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$org': {
      id: '/_app/$org'
      path: '/$org'
      fullPath: '/$org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$org/': {
      id: '/_app/$org/'
      path: '/'
      fullPath: '/$org/'
      preLoaderRoute: typeof AppOrgIndexRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/account/tokens': {
      id: '/_app/account/tokens'
      path: '/tokens'
      fullPath: '/account/tokens'
      preLoaderRoute: typeof AppAccountTokensRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/sessions': {
      id: '/_app/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AppAccountSessionsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/security': {
      id: '/_app/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AppAccountSecurityRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/profile': {
      id: '/_app/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AppAccountProfileRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/notifications': {
      id: '/_app/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AppAccountNotificationsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/$org/notifications': {
      id: '/_app/$org/notifications'
      path: '/notifications'
      fullPath: '/$org/notifications'
      preLoaderRoute: typeof AppOrgNotificationsRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/new-project': {
      id: '/_app/$org/new-project'
      path: '/new-project'
      fullPath: '/$org/new-project'
      preLoaderRoute: typeof AppOrgNewProjectRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/dashboards': {
      id: '/_app/$org/dashboards'
      path: '/dashboards'
      fullPath: '/$org/dashboards'
      preLoaderRoute: typeof AppOrgDashboardsRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/create': {
      id: '/_app/$org/create'
      path: '/create'
      fullPath: '/$org/create'
      preLoaderRoute: typeof AppOrgCreateRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/assistant': {
      id: '/_app/$org/assistant'
      path: '/assistant'
      fullPath: '/$org/assistant'
      preLoaderRoute: typeof AppOrgAssistantRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/dashboards/': {
      id: '/_app/$org/dashboards/'
      path: '/'
      fullPath: '/$org/dashboards/'
      preLoaderRoute: typeof AppOrgDashboardsIndexRouteImport
      parentRoute: typeof AppOrgDashboardsRoute
    }
    '/_app/$org/$project/': {
      id: '/_app/$org/$project/'
      path: '/$project'
      fullPath: '/$org/$project/'
      preLoaderRoute: typeof AppOrgProjectIndexRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/template/$tpl': {
      id: '/_app/$org/template/$tpl'
      path: '/template/$tpl'
      fullPath: '/$org/template/$tpl'
      preLoaderRoute: typeof AppOrgTemplateTplRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/settings/templates': {
      id: '/_app/$org/settings/templates'
      path: '/settings/templates'
      fullPath: '/$org/settings/templates'
      preLoaderRoute: typeof AppOrgSettingsTemplatesRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/settings/members': {
      id: '/_app/$org/settings/members'
      path: '/settings/members'
      fullPath: '/$org/settings/members'
      preLoaderRoute: typeof AppOrgSettingsMembersRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/settings/general': {
      id: '/_app/$org/settings/general'
      path: '/settings/general'
      fullPath: '/$org/settings/general'
      preLoaderRoute: typeof AppOrgSettingsGeneralRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/settings/cells': {
      id: '/_app/$org/settings/cells'
      path: '/settings/cells'
      fullPath: '/$org/settings/cells'
      preLoaderRoute: typeof AppOrgSettingsCellsRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/settings/audit': {
      id: '/_app/$org/settings/audit'
      path: '/settings/audit'
      fullPath: '/$org/settings/audit'
      preLoaderRoute: typeof AppOrgSettingsAuditRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/settings/api-keys': {
      id: '/_app/$org/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/$org/settings/api-keys'
      preLoaderRoute: typeof AppOrgSettingsApiKeysRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/new-project_/templates': {
      id: '/_app/$org/new-project_/templates'
      path: '/new-project/templates'
      fullPath: '/$org/new-project/templates'
      preLoaderRoute: typeof AppOrgNewProjectTemplatesRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/dashboards/postgres-health': {
      id: '/_app/$org/dashboards/postgres-health'
      path: '/postgres-health'
      fullPath: '/$org/dashboards/postgres-health'
      preLoaderRoute: typeof AppOrgDashboardsPostgresHealthRouteImport
      parentRoute: typeof AppOrgDashboardsRoute
    }
    '/_app/$org/dashboards/mine': {
      id: '/_app/$org/dashboards/mine'
      path: '/mine'
      fullPath: '/$org/dashboards/mine'
      preLoaderRoute: typeof AppOrgDashboardsMineRouteImport
      parentRoute: typeof AppOrgDashboardsRoute
    }
    '/_app/$org/dashboards/layouts': {
      id: '/_app/$org/dashboards/layouts'
      path: '/layouts'
      fullPath: '/$org/dashboards/layouts'
      preLoaderRoute: typeof AppOrgDashboardsLayoutsRouteImport
      parentRoute: typeof AppOrgDashboardsRoute
    }
    '/_app/$org/dashboards/infrastructure': {
      id: '/_app/$org/dashboards/infrastructure'
      path: '/infrastructure'
      fullPath: '/$org/dashboards/infrastructure'
      preLoaderRoute: typeof AppOrgDashboardsInfrastructureRouteImport
      parentRoute: typeof AppOrgDashboardsRoute
    }
    '/_app/$org/dashboards/cost-usage': {
      id: '/_app/$org/dashboards/cost-usage'
      path: '/cost-usage'
      fullPath: '/$org/dashboards/cost-usage'
      preLoaderRoute: typeof AppOrgDashboardsCostUsageRouteImport
      parentRoute: typeof AppOrgDashboardsRoute
    }
    '/_app/$org/dashboards/$dashId': {
      id: '/_app/$org/dashboards/$dashId'
      path: '/$dashId'
      fullPath: '/$org/dashboards/$dashId'
      preLoaderRoute: typeof AppOrgDashboardsDashIdRouteImport
      parentRoute: typeof AppOrgDashboardsRoute
    }
    '/_app/$org/billing/usage': {
      id: '/_app/$org/billing/usage'
      path: '/billing/usage'
      fullPath: '/$org/billing/usage'
      preLoaderRoute: typeof AppOrgBillingUsageRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/billing/quotas': {
      id: '/_app/$org/billing/quotas'
      path: '/billing/quotas'
      fullPath: '/$org/billing/quotas'
      preLoaderRoute: typeof AppOrgBillingQuotasRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/billing/plans': {
      id: '/_app/$org/billing/plans'
      path: '/billing/plans'
      fullPath: '/$org/billing/plans'
      preLoaderRoute: typeof AppOrgBillingPlansRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/billing/payment': {
      id: '/_app/$org/billing/payment'
      path: '/billing/payment'
      fullPath: '/$org/billing/payment'
      preLoaderRoute: typeof AppOrgBillingPaymentRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/billing/overview': {
      id: '/_app/$org/billing/overview'
      path: '/billing/overview'
      fullPath: '/$org/billing/overview'
      preLoaderRoute: typeof AppOrgBillingOverviewRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/billing/invoices': {
      id: '/_app/$org/billing/invoices'
      path: '/billing/invoices'
      fullPath: '/$org/billing/invoices'
      preLoaderRoute: typeof AppOrgBillingInvoicesRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/assistant/insights': {
      id: '/_app/$org/assistant/insights'
      path: '/insights'
      fullPath: '/$org/assistant/insights'
      preLoaderRoute: typeof AppOrgAssistantInsightsRouteImport
      parentRoute: typeof AppOrgAssistantRoute
    }
    '/_app/$org/assistant/capabilities': {
      id: '/_app/$org/assistant/capabilities'
      path: '/capabilities'
      fullPath: '/$org/assistant/capabilities'
      preLoaderRoute: typeof AppOrgAssistantCapabilitiesRouteImport
      parentRoute: typeof AppOrgAssistantRoute
    }
    '/_app/$org/assistant/ask': {
      id: '/_app/$org/assistant/ask'
      path: '/ask'
      fullPath: '/$org/assistant/ask'
      preLoaderRoute: typeof AppOrgAssistantAskRouteImport
      parentRoute: typeof AppOrgAssistantRoute
    }
    '/_app/$org/assistant/activity': {
      id: '/_app/$org/assistant/activity'
      path: '/activity'
      fullPath: '/$org/assistant/activity'
      preLoaderRoute: typeof AppOrgAssistantActivityRouteImport
      parentRoute: typeof AppOrgAssistantRoute
    }
    '/_app/$org/$project/observe': {
      id: '/_app/$org/$project/observe'
      path: '/$project/observe'
      fullPath: '/$org/$project/observe'
      preLoaderRoute: typeof AppOrgProjectObserveRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/new-env': {
      id: '/_app/$org/$project/new-env'
      path: '/$project/new-env'
      fullPath: '/$org/$project/new-env'
      preLoaderRoute: typeof AppOrgProjectNewEnvRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/environments': {
      id: '/_app/$org/$project/environments'
      path: '/$project/environments'
      fullPath: '/$org/$project/environments'
      preLoaderRoute: typeof AppOrgProjectEnvironmentsRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/deploy': {
      id: '/_app/$org/$project/deploy'
      path: '/$project/deploy'
      fullPath: '/$org/$project/deploy'
      preLoaderRoute: typeof AppOrgProjectDeployRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/settings/policies/': {
      id: '/_app/$org/settings/policies/'
      path: '/settings/policies'
      fullPath: '/$org/settings/policies/'
      preLoaderRoute: typeof AppOrgSettingsPoliciesIndexRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/deploy/': {
      id: '/_app/$org/$project/deploy/'
      path: '/'
      fullPath: '/$org/$project/deploy/'
      preLoaderRoute: typeof AppOrgProjectDeployIndexRouteImport
      parentRoute: typeof AppOrgProjectDeployRoute
    }
    '/_app/$org/settings/policies/new': {
      id: '/_app/$org/settings/policies/new'
      path: '/settings/policies/new'
      fullPath: '/$org/settings/policies/new'
      preLoaderRoute: typeof AppOrgSettingsPoliciesNewRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/settings/policies/ai-assistant': {
      id: '/_app/$org/settings/policies/ai-assistant'
      path: '/settings/policies/ai-assistant'
      fullPath: '/$org/settings/policies/ai-assistant'
      preLoaderRoute: typeof AppOrgSettingsPoliciesAiAssistantRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/svc/$service': {
      id: '/_app/$org/$project/svc/$service'
      path: '/$project/svc/$service'
      fullPath: '/$org/$project/svc/$service'
      preLoaderRoute: typeof AppOrgProjectSvcServiceRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/settings/policies': {
      id: '/_app/$org/$project/settings/policies'
      path: '/$project/settings/policies'
      fullPath: '/$org/$project/settings/policies'
      preLoaderRoute: typeof AppOrgProjectSettingsPoliciesRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/settings/members': {
      id: '/_app/$org/$project/settings/members'
      path: '/$project/settings/members'
      fullPath: '/$org/$project/settings/members'
      preLoaderRoute: typeof AppOrgProjectSettingsMembersRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/settings/git': {
      id: '/_app/$org/$project/settings/git'
      path: '/$project/settings/git'
      fullPath: '/$org/$project/settings/git'
      preLoaderRoute: typeof AppOrgProjectSettingsGitRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/settings/general': {
      id: '/_app/$org/$project/settings/general'
      path: '/$project/settings/general'
      fullPath: '/$org/$project/settings/general'
      preLoaderRoute: typeof AppOrgProjectSettingsGeneralRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/observe/traces': {
      id: '/_app/$org/$project/observe/traces'
      path: '/traces'
      fullPath: '/$org/$project/observe/traces'
      preLoaderRoute: typeof AppOrgProjectObserveTracesRouteImport
      parentRoute: typeof AppOrgProjectObserveRoute
    }
    '/_app/$org/$project/observe/metrics': {
      id: '/_app/$org/$project/observe/metrics'
      path: '/metrics'
      fullPath: '/$org/$project/observe/metrics'
      preLoaderRoute: typeof AppOrgProjectObserveMetricsRouteImport
      parentRoute: typeof AppOrgProjectObserveRoute
    }
    '/_app/$org/$project/observe/logs': {
      id: '/_app/$org/$project/observe/logs'
      path: '/logs'
      fullPath: '/$org/$project/observe/logs'
      preLoaderRoute: typeof AppOrgProjectObserveLogsRouteImport
      parentRoute: typeof AppOrgProjectObserveRoute
    }
    '/_app/$org/$project/observe/health': {
      id: '/_app/$org/$project/observe/health'
      path: '/health'
      fullPath: '/$org/$project/observe/health'
      preLoaderRoute: typeof AppOrgProjectObserveHealthRouteImport
      parentRoute: typeof AppOrgProjectObserveRoute
    }
    '/_app/$org/$project/observe/events': {
      id: '/_app/$org/$project/observe/events'
      path: '/events'
      fullPath: '/$org/$project/observe/events'
      preLoaderRoute: typeof AppOrgProjectObserveEventsRouteImport
      parentRoute: typeof AppOrgProjectObserveRoute
    }
    '/_app/$org/$project/observe/alerts': {
      id: '/_app/$org/$project/observe/alerts'
      path: '/alerts'
      fullPath: '/$org/$project/observe/alerts'
      preLoaderRoute: typeof AppOrgProjectObserveAlertsRouteImport
      parentRoute: typeof AppOrgProjectObserveRoute
    }
    '/_app/$org/$project/instances/$product': {
      id: '/_app/$org/$project/instances/$product'
      path: '/$project/instances/$product'
      fullPath: '/$org/$project/instances/$product'
      preLoaderRoute: typeof AppOrgProjectInstancesProductRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/$org/$project/deploy/previews': {
      id: '/_app/$org/$project/deploy/previews'
      path: '/previews'
      fullPath: '/$org/$project/deploy/previews'
      preLoaderRoute: typeof AppOrgProjectDeployPreviewsRouteImport
      parentRoute: typeof AppOrgProjectDeployRoute
    }
    '/_app/$org/$project/deploy/$dep': {
      id: '/_app/$org/$project/deploy/$dep'
      path: '/$dep'
      fullPath: '/$org/$project/deploy/$dep'
      preLoaderRoute: typeof AppOrgProjectDeployDepRouteImport
      parentRoute: typeof AppOrgProjectDeployRoute
    }
    '/_app/$org/$project/svc/$service/': {
      id: '/_app/$org/$project/svc/$service/'
      path: '/'
      fullPath: '/$org/$project/svc/$service/'
      preLoaderRoute: typeof AppOrgProjectSvcServiceIndexRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/tables': {
      id: '/_app/$org/$project/svc/$service/tables'
      path: '/tables'
      fullPath: '/$org/$project/svc/$service/tables'
      preLoaderRoute: typeof AppOrgProjectSvcServiceTablesRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/sql-editor': {
      id: '/_app/$org/$project/svc/$service/sql-editor'
      path: '/sql-editor'
      fullPath: '/$org/$project/svc/$service/sql-editor'
      preLoaderRoute: typeof AppOrgProjectSvcServiceSqlEditorRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/shell': {
      id: '/_app/$org/$project/svc/$service/shell'
      path: '/shell'
      fullPath: '/$org/$project/svc/$service/shell'
      preLoaderRoute: typeof AppOrgProjectSvcServiceShellRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/settings': {
      id: '/_app/$org/$project/svc/$service/settings'
      path: '/settings'
      fullPath: '/$org/$project/svc/$service/settings'
      preLoaderRoute: typeof AppOrgProjectSvcServiceSettingsRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/schedules': {
      id: '/_app/$org/$project/svc/$service/schedules'
      path: '/schedules'
      fullPath: '/$org/$project/svc/$service/schedules'
      preLoaderRoute: typeof AppOrgProjectSvcServiceSchedulesRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/scaling': {
      id: '/_app/$org/$project/svc/$service/scaling'
      path: '/scaling'
      fullPath: '/$org/$project/svc/$service/scaling'
      preLoaderRoute: typeof AppOrgProjectSvcServiceScalingRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/objects': {
      id: '/_app/$org/$project/svc/$service/objects'
      path: '/objects'
      fullPath: '/$org/$project/svc/$service/objects'
      preLoaderRoute: typeof AppOrgProjectSvcServiceObjectsRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/metrics': {
      id: '/_app/$org/$project/svc/$service/metrics'
      path: '/metrics'
      fullPath: '/$org/$project/svc/$service/metrics'
      preLoaderRoute: typeof AppOrgProjectSvcServiceMetricsRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/messages': {
      id: '/_app/$org/$project/svc/$service/messages'
      path: '/messages'
      fullPath: '/$org/$project/svc/$service/messages'
      preLoaderRoute: typeof AppOrgProjectSvcServiceMessagesRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/logs': {
      id: '/_app/$org/$project/svc/$service/logs'
      path: '/logs'
      fullPath: '/$org/$project/svc/$service/logs'
      preLoaderRoute: typeof AppOrgProjectSvcServiceLogsRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/lifecycle': {
      id: '/_app/$org/$project/svc/$service/lifecycle'
      path: '/lifecycle'
      fullPath: '/$org/$project/svc/$service/lifecycle'
      preLoaderRoute: typeof AppOrgProjectSvcServiceLifecycleRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/insights': {
      id: '/_app/$org/$project/svc/$service/insights'
      path: '/insights'
      fullPath: '/$org/$project/svc/$service/insights'
      preLoaderRoute: typeof AppOrgProjectSvcServiceInsightsRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/domains': {
      id: '/_app/$org/$project/svc/$service/domains'
      path: '/domains'
      fullPath: '/$org/$project/svc/$service/domains'
      preLoaderRoute: typeof AppOrgProjectSvcServiceDomainsRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/deployments': {
      id: '/_app/$org/$project/svc/$service/deployments'
      path: '/deployments'
      fullPath: '/$org/$project/svc/$service/deployments'
      preLoaderRoute: typeof AppOrgProjectSvcServiceDeploymentsRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/data-browser': {
      id: '/_app/$org/$project/svc/$service/data-browser'
      path: '/data-browser'
      fullPath: '/$org/$project/svc/$service/data-browser'
      preLoaderRoute: typeof AppOrgProjectSvcServiceDataBrowserRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/cli': {
      id: '/_app/$org/$project/svc/$service/cli'
      path: '/cli'
      fullPath: '/$org/$project/svc/$service/cli'
      preLoaderRoute: typeof AppOrgProjectSvcServiceCliRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/branches': {
      id: '/_app/$org/$project/svc/$service/branches'
      path: '/branches'
      fullPath: '/$org/$project/svc/$service/branches'
      preLoaderRoute: typeof AppOrgProjectSvcServiceBranchesRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/bindings': {
      id: '/_app/$org/$project/svc/$service/bindings'
      path: '/bindings'
      fullPath: '/$org/$project/svc/$service/bindings'
      preLoaderRoute: typeof AppOrgProjectSvcServiceBindingsRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/backups': {
      id: '/_app/$org/$project/svc/$service/backups'
      path: '/backups'
      fullPath: '/$org/$project/svc/$service/backups'
      preLoaderRoute: typeof AppOrgProjectSvcServiceBackupsRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
    '/_app/$org/$project/svc/$service/ai': {
      id: '/_app/$org/$project/svc/$service/ai'
      path: '/ai'
      fullPath: '/$org/$project/svc/$service/ai'
      preLoaderRoute: typeof AppOrgProjectSvcServiceAiRouteImport
      parentRoute: typeof AppOrgProjectSvcServiceRoute
    }
  }
}

interface AppOrgAssistantRouteChildren {
  AppOrgAssistantActivityRoute: typeof AppOrgAssistantActivityRoute
  AppOrgAssistantAskRoute: typeof AppOrgAssistantAskRoute
  AppOrgAssistantCapabilitiesRoute: typeof AppOrgAssistantCapabilitiesRoute
  AppOrgAssistantInsightsRoute: typeof AppOrgAssistantInsightsRoute
}

const AppOrgAssistantRouteChildren: AppOrgAssistantRouteChildren = {
  AppOrgAssistantActivityRoute: AppOrgAssistantActivityRoute,
  AppOrgAssistantAskRoute: AppOrgAssistantAskRoute,
  AppOrgAssistantCapabilitiesRoute: AppOrgAssistantCapabilitiesRoute,
  AppOrgAssistantInsightsRoute: AppOrgAssistantInsightsRoute,
}

const AppOrgAssistantRouteWithChildren = AppOrgAssistantRoute._addFileChildren(
  AppOrgAssistantRouteChildren,
)

interface AppOrgDashboardsRouteChildren {
  AppOrgDashboardsDashIdRoute: typeof AppOrgDashboardsDashIdRoute
  AppOrgDashboardsCostUsageRoute: typeof AppOrgDashboardsCostUsageRoute
  AppOrgDashboardsInfrastructureRoute: typeof AppOrgDashboardsInfrastructureRoute
  AppOrgDashboardsLayoutsRoute: typeof AppOrgDashboardsLayoutsRoute
  AppOrgDashboardsMineRoute: typeof AppOrgDashboardsMineRoute
  AppOrgDashboardsPostgresHealthRoute: typeof AppOrgDashboardsPostgresHealthRoute
  AppOrgDashboardsIndexRoute: typeof AppOrgDashboardsIndexRoute
}

const AppOrgDashboardsRouteChildren: AppOrgDashboardsRouteChildren = {
  AppOrgDashboardsDashIdRoute: AppOrgDashboardsDashIdRoute,
  AppOrgDashboardsCostUsageRoute: AppOrgDashboardsCostUsageRoute,
  AppOrgDashboardsInfrastructureRoute: AppOrgDashboardsInfrastructureRoute,
  AppOrgDashboardsLayoutsRoute: AppOrgDashboardsLayoutsRoute,
  AppOrgDashboardsMineRoute: AppOrgDashboardsMineRoute,
  AppOrgDashboardsPostgresHealthRoute: AppOrgDashboardsPostgresHealthRoute,
  AppOrgDashboardsIndexRoute: AppOrgDashboardsIndexRoute,
}

const AppOrgDashboardsRouteWithChildren =
  AppOrgDashboardsRoute._addFileChildren(AppOrgDashboardsRouteChildren)

interface AppOrgProjectDeployRouteChildren {
  AppOrgProjectDeployDepRoute: typeof AppOrgProjectDeployDepRoute
  AppOrgProjectDeployPreviewsRoute: typeof AppOrgProjectDeployPreviewsRoute
  AppOrgProjectDeployIndexRoute: typeof AppOrgProjectDeployIndexRoute
}

const AppOrgProjectDeployRouteChildren: AppOrgProjectDeployRouteChildren = {
  AppOrgProjectDeployDepRoute: AppOrgProjectDeployDepRoute,
  AppOrgProjectDeployPreviewsRoute: AppOrgProjectDeployPreviewsRoute,
  AppOrgProjectDeployIndexRoute: AppOrgProjectDeployIndexRoute,
}

const AppOrgProjectDeployRouteWithChildren =
  AppOrgProjectDeployRoute._addFileChildren(AppOrgProjectDeployRouteChildren)

interface AppOrgProjectObserveRouteChildren {
  AppOrgProjectObserveAlertsRoute: typeof AppOrgProjectObserveAlertsRoute
  AppOrgProjectObserveEventsRoute: typeof AppOrgProjectObserveEventsRoute
  AppOrgProjectObserveHealthRoute: typeof AppOrgProjectObserveHealthRoute
  AppOrgProjectObserveLogsRoute: typeof AppOrgProjectObserveLogsRoute
  AppOrgProjectObserveMetricsRoute: typeof AppOrgProjectObserveMetricsRoute
  AppOrgProjectObserveTracesRoute: typeof AppOrgProjectObserveTracesRoute
}

const AppOrgProjectObserveRouteChildren: AppOrgProjectObserveRouteChildren = {
  AppOrgProjectObserveAlertsRoute: AppOrgProjectObserveAlertsRoute,
  AppOrgProjectObserveEventsRoute: AppOrgProjectObserveEventsRoute,
  AppOrgProjectObserveHealthRoute: AppOrgProjectObserveHealthRoute,
  AppOrgProjectObserveLogsRoute: AppOrgProjectObserveLogsRoute,
  AppOrgProjectObserveMetricsRoute: AppOrgProjectObserveMetricsRoute,
  AppOrgProjectObserveTracesRoute: AppOrgProjectObserveTracesRoute,
}

const AppOrgProjectObserveRouteWithChildren =
  AppOrgProjectObserveRoute._addFileChildren(AppOrgProjectObserveRouteChildren)

interface AppOrgProjectSvcServiceRouteChildren {
  AppOrgProjectSvcServiceAiRoute: typeof AppOrgProjectSvcServiceAiRoute
  AppOrgProjectSvcServiceBackupsRoute: typeof AppOrgProjectSvcServiceBackupsRoute
  AppOrgProjectSvcServiceBindingsRoute: typeof AppOrgProjectSvcServiceBindingsRoute
  AppOrgProjectSvcServiceBranchesRoute: typeof AppOrgProjectSvcServiceBranchesRoute
  AppOrgProjectSvcServiceCliRoute: typeof AppOrgProjectSvcServiceCliRoute
  AppOrgProjectSvcServiceDataBrowserRoute: typeof AppOrgProjectSvcServiceDataBrowserRoute
  AppOrgProjectSvcServiceDeploymentsRoute: typeof AppOrgProjectSvcServiceDeploymentsRoute
  AppOrgProjectSvcServiceDomainsRoute: typeof AppOrgProjectSvcServiceDomainsRoute
  AppOrgProjectSvcServiceInsightsRoute: typeof AppOrgProjectSvcServiceInsightsRoute
  AppOrgProjectSvcServiceLifecycleRoute: typeof AppOrgProjectSvcServiceLifecycleRoute
  AppOrgProjectSvcServiceLogsRoute: typeof AppOrgProjectSvcServiceLogsRoute
  AppOrgProjectSvcServiceMessagesRoute: typeof AppOrgProjectSvcServiceMessagesRoute
  AppOrgProjectSvcServiceMetricsRoute: typeof AppOrgProjectSvcServiceMetricsRoute
  AppOrgProjectSvcServiceObjectsRoute: typeof AppOrgProjectSvcServiceObjectsRoute
  AppOrgProjectSvcServiceScalingRoute: typeof AppOrgProjectSvcServiceScalingRoute
  AppOrgProjectSvcServiceSchedulesRoute: typeof AppOrgProjectSvcServiceSchedulesRoute
  AppOrgProjectSvcServiceSettingsRoute: typeof AppOrgProjectSvcServiceSettingsRoute
  AppOrgProjectSvcServiceShellRoute: typeof AppOrgProjectSvcServiceShellRoute
  AppOrgProjectSvcServiceSqlEditorRoute: typeof AppOrgProjectSvcServiceSqlEditorRoute
  AppOrgProjectSvcServiceTablesRoute: typeof AppOrgProjectSvcServiceTablesRoute
  AppOrgProjectSvcServiceIndexRoute: typeof AppOrgProjectSvcServiceIndexRoute
}

const AppOrgProjectSvcServiceRouteChildren: AppOrgProjectSvcServiceRouteChildren =
  {
    AppOrgProjectSvcServiceAiRoute: AppOrgProjectSvcServiceAiRoute,
    AppOrgProjectSvcServiceBackupsRoute: AppOrgProjectSvcServiceBackupsRoute,
    AppOrgProjectSvcServiceBindingsRoute: AppOrgProjectSvcServiceBindingsRoute,
    AppOrgProjectSvcServiceBranchesRoute: AppOrgProjectSvcServiceBranchesRoute,
    AppOrgProjectSvcServiceCliRoute: AppOrgProjectSvcServiceCliRoute,
    AppOrgProjectSvcServiceDataBrowserRoute:
      AppOrgProjectSvcServiceDataBrowserRoute,
    AppOrgProjectSvcServiceDeploymentsRoute:
      AppOrgProjectSvcServiceDeploymentsRoute,
    AppOrgProjectSvcServiceDomainsRoute: AppOrgProjectSvcServiceDomainsRoute,
    AppOrgProjectSvcServiceInsightsRoute: AppOrgProjectSvcServiceInsightsRoute,
    AppOrgProjectSvcServiceLifecycleRoute:
      AppOrgProjectSvcServiceLifecycleRoute,
    AppOrgProjectSvcServiceLogsRoute: AppOrgProjectSvcServiceLogsRoute,
    AppOrgProjectSvcServiceMessagesRoute: AppOrgProjectSvcServiceMessagesRoute,
    AppOrgProjectSvcServiceMetricsRoute: AppOrgProjectSvcServiceMetricsRoute,
    AppOrgProjectSvcServiceObjectsRoute: AppOrgProjectSvcServiceObjectsRoute,
    AppOrgProjectSvcServiceScalingRoute: AppOrgProjectSvcServiceScalingRoute,
    AppOrgProjectSvcServiceSchedulesRoute:
      AppOrgProjectSvcServiceSchedulesRoute,
    AppOrgProjectSvcServiceSettingsRoute: AppOrgProjectSvcServiceSettingsRoute,
    AppOrgProjectSvcServiceShellRoute: AppOrgProjectSvcServiceShellRoute,
    AppOrgProjectSvcServiceSqlEditorRoute:
      AppOrgProjectSvcServiceSqlEditorRoute,
    AppOrgProjectSvcServiceTablesRoute: AppOrgProjectSvcServiceTablesRoute,
    AppOrgProjectSvcServiceIndexRoute: AppOrgProjectSvcServiceIndexRoute,
  }

const AppOrgProjectSvcServiceRouteWithChildren =
  AppOrgProjectSvcServiceRoute._addFileChildren(
    AppOrgProjectSvcServiceRouteChildren,
  )

interface AppOrgRouteChildren {
  AppOrgAssistantRoute: typeof AppOrgAssistantRouteWithChildren
  AppOrgCreateRoute: typeof AppOrgCreateRoute
  AppOrgDashboardsRoute: typeof AppOrgDashboardsRouteWithChildren
  AppOrgNewProjectRoute: typeof AppOrgNewProjectRoute
  AppOrgNotificationsRoute: typeof AppOrgNotificationsRoute
  AppOrgIndexRoute: typeof AppOrgIndexRoute
  AppOrgProjectDeployRoute: typeof AppOrgProjectDeployRouteWithChildren
  AppOrgProjectEnvironmentsRoute: typeof AppOrgProjectEnvironmentsRoute
  AppOrgProjectNewEnvRoute: typeof AppOrgProjectNewEnvRoute
  AppOrgProjectObserveRoute: typeof AppOrgProjectObserveRouteWithChildren
  AppOrgBillingInvoicesRoute: typeof AppOrgBillingInvoicesRoute
  AppOrgBillingOverviewRoute: typeof AppOrgBillingOverviewRoute
  AppOrgBillingPaymentRoute: typeof AppOrgBillingPaymentRoute
  AppOrgBillingPlansRoute: typeof AppOrgBillingPlansRoute
  AppOrgBillingQuotasRoute: typeof AppOrgBillingQuotasRoute
  AppOrgBillingUsageRoute: typeof AppOrgBillingUsageRoute
  AppOrgNewProjectTemplatesRoute: typeof AppOrgNewProjectTemplatesRoute
  AppOrgSettingsApiKeysRoute: typeof AppOrgSettingsApiKeysRoute
  AppOrgSettingsAuditRoute: typeof AppOrgSettingsAuditRoute
  AppOrgSettingsCellsRoute: typeof AppOrgSettingsCellsRoute
  AppOrgSettingsGeneralRoute: typeof AppOrgSettingsGeneralRoute
  AppOrgSettingsMembersRoute: typeof AppOrgSettingsMembersRoute
  AppOrgSettingsTemplatesRoute: typeof AppOrgSettingsTemplatesRoute
  AppOrgTemplateTplRoute: typeof AppOrgTemplateTplRoute
  AppOrgProjectIndexRoute: typeof AppOrgProjectIndexRoute
  AppOrgProjectInstancesProductRoute: typeof AppOrgProjectInstancesProductRoute
  AppOrgProjectSettingsGeneralRoute: typeof AppOrgProjectSettingsGeneralRoute
  AppOrgProjectSettingsGitRoute: typeof AppOrgProjectSettingsGitRoute
  AppOrgProjectSettingsMembersRoute: typeof AppOrgProjectSettingsMembersRoute
  AppOrgProjectSettingsPoliciesRoute: typeof AppOrgProjectSettingsPoliciesRoute
  AppOrgProjectSvcServiceRoute: typeof AppOrgProjectSvcServiceRouteWithChildren
  AppOrgSettingsPoliciesAiAssistantRoute: typeof AppOrgSettingsPoliciesAiAssistantRoute
  AppOrgSettingsPoliciesNewRoute: typeof AppOrgSettingsPoliciesNewRoute
  AppOrgSettingsPoliciesIndexRoute: typeof AppOrgSettingsPoliciesIndexRoute
}

const AppOrgRouteChildren: AppOrgRouteChildren = {
  AppOrgAssistantRoute: AppOrgAssistantRouteWithChildren,
  AppOrgCreateRoute: AppOrgCreateRoute,
  AppOrgDashboardsRoute: AppOrgDashboardsRouteWithChildren,
  AppOrgNewProjectRoute: AppOrgNewProjectRoute,
  AppOrgNotificationsRoute: AppOrgNotificationsRoute,
  AppOrgIndexRoute: AppOrgIndexRoute,
  AppOrgProjectDeployRoute: AppOrgProjectDeployRouteWithChildren,
  AppOrgProjectEnvironmentsRoute: AppOrgProjectEnvironmentsRoute,
  AppOrgProjectNewEnvRoute: AppOrgProjectNewEnvRoute,
  AppOrgProjectObserveRoute: AppOrgProjectObserveRouteWithChildren,
  AppOrgBillingInvoicesRoute: AppOrgBillingInvoicesRoute,
  AppOrgBillingOverviewRoute: AppOrgBillingOverviewRoute,
  AppOrgBillingPaymentRoute: AppOrgBillingPaymentRoute,
  AppOrgBillingPlansRoute: AppOrgBillingPlansRoute,
  AppOrgBillingQuotasRoute: AppOrgBillingQuotasRoute,
  AppOrgBillingUsageRoute: AppOrgBillingUsageRoute,
  AppOrgNewProjectTemplatesRoute: AppOrgNewProjectTemplatesRoute,
  AppOrgSettingsApiKeysRoute: AppOrgSettingsApiKeysRoute,
  AppOrgSettingsAuditRoute: AppOrgSettingsAuditRoute,
  AppOrgSettingsCellsRoute: AppOrgSettingsCellsRoute,
  AppOrgSettingsGeneralRoute: AppOrgSettingsGeneralRoute,
  AppOrgSettingsMembersRoute: AppOrgSettingsMembersRoute,
  AppOrgSettingsTemplatesRoute: AppOrgSettingsTemplatesRoute,
  AppOrgTemplateTplRoute: AppOrgTemplateTplRoute,
  AppOrgProjectIndexRoute: AppOrgProjectIndexRoute,
  AppOrgProjectInstancesProductRoute: AppOrgProjectInstancesProductRoute,
  AppOrgProjectSettingsGeneralRoute: AppOrgProjectSettingsGeneralRoute,
  AppOrgProjectSettingsGitRoute: AppOrgProjectSettingsGitRoute,
  AppOrgProjectSettingsMembersRoute: AppOrgProjectSettingsMembersRoute,
  AppOrgProjectSettingsPoliciesRoute: AppOrgProjectSettingsPoliciesRoute,
  AppOrgProjectSvcServiceRoute: AppOrgProjectSvcServiceRouteWithChildren,
  AppOrgSettingsPoliciesAiAssistantRoute:
    AppOrgSettingsPoliciesAiAssistantRoute,
  AppOrgSettingsPoliciesNewRoute: AppOrgSettingsPoliciesNewRoute,
  AppOrgSettingsPoliciesIndexRoute: AppOrgSettingsPoliciesIndexRoute,
}

const AppOrgRouteWithChildren =
  AppOrgRoute._addFileChildren(AppOrgRouteChildren)

interface AppAccountRouteChildren {
  AppAccountNotificationsRoute: typeof AppAccountNotificationsRoute
  AppAccountProfileRoute: typeof AppAccountProfileRoute
  AppAccountSecurityRoute: typeof AppAccountSecurityRoute
  AppAccountSessionsRoute: typeof AppAccountSessionsRoute
  AppAccountTokensRoute: typeof AppAccountTokensRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountNotificationsRoute: AppAccountNotificationsRoute,
  AppAccountProfileRoute: AppAccountProfileRoute,
  AppAccountSecurityRoute: AppAccountSecurityRoute,
  AppAccountSessionsRoute: AppAccountSessionsRoute,
  AppAccountTokensRoute: AppAccountTokensRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppRouteChildren {
  AppOrgRoute: typeof AppOrgRouteWithChildren
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppWelcomeRoute: typeof AppWelcomeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgRoute: AppOrgRouteWithChildren,
  AppAccountRoute: AppAccountRouteWithChildren,
  AppWelcomeRoute: AppWelcomeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteInviteIdRoute: InviteInviteIdRoute,
  OnboardingConnectRoute: OnboardingConnectRoute,
  OnboardingOrgRoute: OnboardingOrgRoute,
  OnboardingProjectRoute: OnboardingProjectRoute,
  OnboardingTeamRoute: OnboardingTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
